// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.RequestOptions
import com.workos.android.enums.GenerateLinkIntent
import com.workos.android.internal.JsonBody
import com.workos.android.internal.Transport
import com.workos.android.models.PortalLinkResponse

/** Operations for the AdminPortal API. */
public class AdminPortal internal constructor(
    private val transport: Transport,
) {
    /**
     * Generate a Portal Link
     *
     * Generate a Portal Link scoped to an Organization.
     *
     * @param organization An [Organization](https://workos.com/docs/reference/organization) identifier.
     * @param returnUrl The URL to go to when an admin clicks on your logo in the Admin Portal. If not specified, the return URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
     * @param successUrl The URL to redirect the admin to when they finish setup. If not specified, the success URL configured on the [Redirects](https://dashboard.workos.com/redirects) page will be used.
     * @param intent The intent of the Admin Portal.
     * @param itContactEmails The email addresses of the IT contacts to grant access to the Admin Portal for the given organization. Accepts up to 20 emails.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `PortalLinkResponse` returned by the API.
     */
    public suspend fun generateLink(
        organization: String,
        returnUrl: String? = null,
        successUrl: String? = null,
        intent: GenerateLinkIntent? = null,
        itContactEmails: List<String>? = null,
        requestOptions: RequestOptions? = null,
    ): PortalLinkResponse {
        val path = "portal/generate_link"
        val payload = JsonBody()
        payload.set("return_url", returnUrl)
        payload.set("success_url", successUrl)
        payload.set("organization", organization)
        payload.set("intent", intent)
        payload.set("it_contact_emails", itContactEmails)
        return transport.request<PortalLinkResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }
}
