// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.RequestOptions
import com.workos.android.internal.JsonBody
import com.workos.android.internal.Transport
import com.workos.android.models.ClientApiTokenResponse

/** Operations for the ClientApi API. */
public class ClientApi internal constructor(
    private val transport: Transport,
) {
    /**
     * Generate a Client API token
     *
     * Generate a short-lived, session-bound token for the Client GraphQL API, scoped to an organization and user.
     *
     * @param organizationId The ID of the organization to scope the Client API token to.
     * @param userId The ID of the user to issue the Client API token for.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ClientApiTokenResponse` returned by the API.
     */
    public suspend fun createToken(
        organizationId: String,
        userId: String,
        requestOptions: RequestOptions? = null,
    ): ClientApiTokenResponse {
        val path = "client/token"
        val payload = JsonBody()
        payload.set("organization_id", organizationId)
        payload.set("user_id", userId)
        return transport.request<ClientApiTokenResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }
}
