// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.ApplicationsRegistrationTypes
import com.workos.android.enums.PaginationOrder
import com.workos.android.internal.JsonBody
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.ApplicationCredentialsListItem
import com.workos.android.models.ConnectApplication
import com.workos.android.models.CreateApplicationSecret
import com.workos.android.models.ExternalAuthCompleteResponse
import com.workos.android.models.NewConnectApplicationSecret
import com.workos.android.models.RedirectUriInput
import com.workos.android.models.UserConsentOption
import com.workos.android.models.UserObject
import kotlinx.coroutines.flow.Flow

/** Operations for the Connect API. */
public class Connect internal constructor(
    private val transport: Transport,
) {
    /**
     * Complete external authentication
     *
     * Completes an external authentication flow and returns control to AuthKit. This endpoint is used with [Standalone Connect](https://workos.com/docs/authkit/connect/standalone) to bridge your existing authentication system with the Connect OAuth API infrastructure.
     *
     * After successfully authenticating a user in your application, calling this endpoint will:
     *
     * - Create or update the user in AuthKit, using the given `id` as its `external_id`.
     * - Return a `redirect_uri` your application should redirect to in order for AuthKit to complete the flow
     *
     * Users are automatically created or updated based on the `id` and `email` provided. If a user with the same `id` exists, their information is updated. Otherwise, a new user is created.
     *
     * If you provide a new `id` with an `email` that already belongs to an existing user, the request will fail with an error as email addresses are unique to a user.
     *
     * @param externalAuthId Identifier provided when AuthKit redirected to your login page.
     * @param user The user to create or update in AuthKit.
     * @param userConsentOptions Array of [User Consent Options](https://workos.com/docs/reference/workos-connect/standalone/user-consent-options) to store with the session.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ExternalAuthCompleteResponse` returned by the API.
     */
    public suspend fun completeOAuth2(
        externalAuthId: String,
        user: UserObject,
        userConsentOptions: List<UserConsentOption>? = null,
        requestOptions: RequestOptions? = null,
    ): ExternalAuthCompleteResponse {
        val path = "authkit/oauth2/complete"
        val payload = JsonBody()
        payload.set("external_auth_id", externalAuthId)
        payload.set("user", user)
        payload.set("user_consent_options", userConsentOptions)
        return transport.request<ExternalAuthCompleteResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * List Connect Applications
     *
     * List all Connect Applications in the current environment with optional filtering.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param registrationTypes Filter Connect Applications by registration type. Specify multiple as a comma-separated list (e.g. `registration_types=dynamic,authenticated`). Defaults to `authenticated` only when not specified.
     * @param organizationId Filter Connect Applications by organization ID.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `Page<ConnectApplication>` returned by the API.
     */
    public suspend fun listApplications(
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        registrationTypes: List<ApplicationsRegistrationTypes>? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ConnectApplication> {
        val path = "connect/applications"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        registrationTypes?.let {
            for (value in it) {
                query.add(QueryParam("registration_types", value.rawValue))
            }
        }
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        return transport.request<Page<ConnectApplication>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listApplications]: emits every item across successive pages as the flow is collected.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param registrationTypes Filter Connect Applications by registration type. Specify multiple as a comma-separated list (e.g. `registration_types=dynamic,authenticated`). Defaults to `authenticated` only when not specified.
     * @param organizationId Filter Connect Applications by organization ID.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return A cold flow of `ConnectApplication` values.
     */
    public fun listApplicationsAutoPaging(
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        registrationTypes: List<ApplicationsRegistrationTypes>? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<ConnectApplication> =
        autoPagingFlow { cursor ->
            listApplications(
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                registrationTypes = registrationTypes,
                organizationId = organizationId,
                requestOptions = requestOptions,
            )
        }

    /**
     * Create oauth application
     *
     * Create a new Connect Application. Supports both OAuth and Machine-to-Machine (M2M) application types.
     *
     * @param name The name of the application.
     * @param isFirstParty Whether this is a first-party application. Third-party applications require an organization_id.
     * @param description A description for the application.
     * @param scopes The OAuth scopes granted to the application.
     * @param redirectUris Redirect URIs for the application.
     * @param usesPkce Whether the application uses PKCE (Proof Key for Code Exchange).
     * @param organizationId The organization ID this application belongs to. Required when is_first_party is false.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ConnectApplication` returned by the API.
     */
    public suspend fun createOAuthApplication(
        name: String,
        isFirstParty: Boolean,
        description: String? = null,
        scopes: List<String>? = null,
        redirectUris: List<RedirectUriInput>? = null,
        usesPkce: Boolean? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectApplication {
        val path = "connect/applications"
        val payload = JsonBody()
        payload.set("name", name)
        payload.set("is_first_party", isFirstParty)
        payload.set("description", description)
        payload.set("scopes", scopes)
        payload.set("redirect_uris", redirectUris)
        payload.set("uses_pkce", usesPkce)
        payload.set("organization_id", organizationId)
        payload.set("application_type", "oauth")
        return transport.request<ConnectApplication>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Create m2m application
     *
     * Create a new Connect Application. Supports both OAuth and Machine-to-Machine (M2M) application types.
     *
     * @param name The name of the application.
     * @param organizationId The organization ID this application belongs to.
     * @param description A description for the application.
     * @param scopes The OAuth scopes granted to the application.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ConnectApplication` returned by the API.
     */
    public suspend fun createM2MApplication(
        name: String,
        organizationId: String,
        description: String? = null,
        scopes: List<String>? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectApplication {
        val path = "connect/applications"
        val payload = JsonBody()
        payload.set("name", name)
        payload.set("organization_id", organizationId)
        payload.set("description", description)
        payload.set("scopes", scopes)
        payload.set("application_type", "m2m")
        return transport.request<ConnectApplication>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get a Connect Application
     *
     * Retrieve details for a specific Connect Application by ID or client ID.
     *
     * @param id The application ID or client ID of the Connect Application.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ConnectApplication` returned by the API.
     */
    public suspend fun getApplication(
        id: String,
        requestOptions: RequestOptions? = null,
    ): ConnectApplication {
        val path = "connect/applications/${PathEncoding.segment(id)}"
        return transport.request<ConnectApplication>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Update a Connect Application
     *
     * Update an existing Connect Application. For OAuth applications, you can update redirect URIs. For all applications, you can update the name, description, and scopes.
     *
     * @param id The application ID or client ID of the Connect Application.
     * @param name The name of the application.
     * @param description A description for the application.
     * @param scopes The OAuth scopes granted to the application.
     * @param redirectUris Updated redirect URIs for the application. OAuth applications only.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ConnectApplication` returned by the API.
     */
    public suspend fun updateApplication(
        id: String,
        name: String? = null,
        description: String? = null,
        scopes: List<String>? = null,
        redirectUris: List<RedirectUriInput>? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectApplication {
        val path = "connect/applications/${PathEncoding.segment(id)}"
        val payload = JsonBody()
        payload.set("name", name)
        payload.set("description", description)
        payload.set("scopes", scopes)
        payload.set("redirect_uris", redirectUris)
        return transport.request<ConnectApplication>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete a Connect Application
     *
     * Delete an existing Connect Application.
     *
     * @param id The application ID or client ID of the Connect Application.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     */
    public suspend fun deleteApplication(
        id: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "connect/applications/${PathEncoding.segment(id)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * List Client Secrets for a Connect Application
     *
     * List all client secrets associated with a Connect Application.
     *
     * @param id The application ID or client ID of the Connect Application.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `List<ApplicationCredentialsListItem>` returned by the API.
     */
    public suspend fun listApplicationClientSecrets(
        id: String,
        requestOptions: RequestOptions? = null,
    ): List<ApplicationCredentialsListItem> {
        val path = "connect/applications/${PathEncoding.segment(id)}/client_secrets"
        return transport.request<List<ApplicationCredentialsListItem>>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Create a new client secret for a Connect Application
     *
     * Create new secrets for a Connect Application.
     *
     * @param id The application ID or client ID of the Connect Application.
     * @param body The body value.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `NewConnectApplicationSecret` returned by the API.
     */
    public suspend fun createApplicationClientSecret(
        id: String,
        body: CreateApplicationSecret,
        requestOptions: RequestOptions? = null,
    ): NewConnectApplicationSecret {
        val path = "connect/applications/${PathEncoding.segment(id)}/client_secrets"
        val payload = JsonBody()
        payload.setRaw(CreateApplicationSecret.serializer(), body)
        return transport.request<NewConnectApplicationSecret>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete a Client Secret
     *
     * Delete (revoke) an existing client secret.
     *
     * @param id The unique ID of the client secret.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     */
    public suspend fun deleteClientSecret(
        id: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "connect/client_secrets/${PathEncoding.segment(id)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }
}
