// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.PaginationOrder
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.EventSchema
import kotlinx.coroutines.flow.Flow

/** Operations for the Events API. */
public class Events internal constructor(
    private val transport: Transport,
) {
    /**
     * List events
     *
     * List events for the current environment.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param events Filter events by one or more event types (e.g. `dsync.user.created`).
     * @param rangeStart ISO-8601 date string to filter events created after this date.
     * @param rangeEnd ISO-8601 date string to filter events created before this date.
     * @param organizationId Filter events by the [Organization](https://workos.com/docs/reference/organization) that the event is associated with.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `Page<EventSchema>` returned by the API.
     */
    public suspend fun list(
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        events: List<String>? = null,
        rangeStart: String? = null,
        rangeEnd: String? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): Page<EventSchema> {
        val path = "events"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        events?.let {
            for (value in it) {
                query.add(QueryParam("events", value))
            }
        }
        rangeStart?.let { query.add(QueryParam("range_start", it)) }
        rangeEnd?.let { query.add(QueryParam("range_end", it)) }
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        return transport.request<Page<EventSchema>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [list]: emits every item across successive pages as the flow is collected.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param events Filter events by one or more event types (e.g. `dsync.user.created`).
     * @param rangeStart ISO-8601 date string to filter events created after this date.
     * @param rangeEnd ISO-8601 date string to filter events created before this date.
     * @param organizationId Filter events by the [Organization](https://workos.com/docs/reference/organization) that the event is associated with.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return A cold flow of `EventSchema` values.
     */
    public fun listAutoPaging(
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        events: List<String>? = null,
        rangeStart: String? = null,
        rangeEnd: String? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<EventSchema> =
        autoPagingFlow { cursor ->
            list(
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                events = events,
                rangeStart = rangeStart,
                rangeEnd = rangeEnd,
                organizationId = organizationId,
                requestOptions = requestOptions,
            )
        }
}
