// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.PaginationOrder
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.FeatureFlag
import com.workos.android.models.Flag
import kotlinx.coroutines.flow.Flow

/** Operations for the FeatureFlags API. */
public class FeatureFlags internal constructor(
    private val transport: Transport,
) {
    /**
     * List feature flags
     *
     * Get a list of all of your existing feature flags matching the criteria specified.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `Page<Flag>` returned by the API.
     */
    public suspend fun list(
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<Flag> {
        val path = "feature-flags"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<Flag>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [list]: emits every item across successive pages as the flow is collected.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return A cold flow of `Flag` values.
     */
    public fun listAutoPaging(
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<Flag> =
        autoPagingFlow { cursor ->
            list(
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }

    /**
     * Get a feature flag
     *
     * Get the details of an existing feature flag by its slug.
     *
     * @param slug A unique key to reference the Feature Flag.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `Flag` returned by the API.
     */
    public suspend fun get(
        slug: String,
        requestOptions: RequestOptions? = null,
    ): Flag {
        val path = "feature-flags/${PathEncoding.segment(slug)}"
        return transport.request<Flag>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Disable a feature flag
     *
     * Disables a feature flag in the current environment.
     *
     * @param slug A unique key to reference the Feature Flag.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `FeatureFlag` returned by the API.
     */
    public suspend fun disable(
        slug: String,
        requestOptions: RequestOptions? = null,
    ): FeatureFlag {
        val path = "feature-flags/${PathEncoding.segment(slug)}/disable"
        return transport.request<FeatureFlag>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Enable a feature flag
     *
     * Enables a feature flag in the current environment.
     *
     * @param slug A unique key to reference the Feature Flag.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `FeatureFlag` returned by the API.
     */
    public suspend fun enable(
        slug: String,
        requestOptions: RequestOptions? = null,
    ): FeatureFlag {
        val path = "feature-flags/${PathEncoding.segment(slug)}/enable"
        return transport.request<FeatureFlag>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Add a feature flag target
     *
     * Enables a feature flag for a specific target in the current environment. Currently, supported targets include users and organizations.
     *
     * @param slug The unique slug identifier of the feature flag.
     * @param resourceId The resource ID in format "user_<id>" or "org_<id>".
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     */
    public suspend fun addFlagTarget(
        slug: String,
        resourceId: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "feature-flags/${PathEncoding.segment(slug)}/targets/${PathEncoding.segment(resourceId)}"
        transport.requestVoid(
            method = "POST",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Remove a feature flag target
     *
     * Removes a target from the feature flag's target list in the current environment. Currently, supported targets include users and organizations.
     *
     * @param slug The unique slug identifier of the feature flag.
     * @param resourceId The resource ID in format "user_<id>" or "org_<id>".
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     */
    public suspend fun removeFlagTarget(
        slug: String,
        resourceId: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "feature-flags/${PathEncoding.segment(slug)}/targets/${PathEncoding.segment(resourceId)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * List enabled feature flags for an organization
     *
     * Get a list of all enabled feature flags for an organization.
     *
     * @param organizationId Unique identifier of the Organization.
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `Page<Flag>` returned by the API.
     */
    public suspend fun listOrganizationFeatureFlags(
        organizationId: String,
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<Flag> {
        val path = "organizations/${PathEncoding.segment(organizationId)}/feature-flags"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<Flag>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listOrganizationFeatureFlags]: emits every item across successive pages as the flow is collected.
     *
     * @param organizationId Unique identifier of the Organization.
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return A cold flow of `Flag` values.
     */
    public fun listOrganizationFeatureFlagsAutoPaging(
        organizationId: String,
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<Flag> =
        autoPagingFlow { cursor ->
            listOrganizationFeatureFlags(
                organizationId = organizationId,
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }

    /**
     * List enabled feature flags for a user
     *
     * Get a list of all enabled feature flags for the provided user. This includes feature flags enabled specifically for the user as well as any organizations that the user is a member of.
     *
     * @param userId The ID of the user.
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `Page<Flag>` returned by the API.
     */
    public suspend fun listUserFeatureFlags(
        userId: String,
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<Flag> {
        val path = "user_management/users/${PathEncoding.segment(userId)}/feature-flags"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<Flag>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listUserFeatureFlags]: emits every item across successive pages as the flow is collected.
     *
     * @param userId The ID of the user.
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return A cold flow of `Flag` values.
     */
    public fun listUserFeatureFlagsAutoPaging(
        userId: String,
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<Flag> =
        autoPagingFlow { cursor ->
            listUserFeatureFlags(
                userId = userId,
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }
}
