// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.AuthenticationFactorsCreateRequestType
import com.workos.android.enums.PaginationOrder
import com.workos.android.internal.JsonBody
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.AuthenticationChallenge
import com.workos.android.models.AuthenticationChallengeVerifyResponse
import com.workos.android.models.AuthenticationFactor
import com.workos.android.models.AuthenticationFactorEnrolled
import com.workos.android.models.UserAuthenticationFactorEnrollResponse
import kotlinx.coroutines.flow.Flow

/** Operations for the MultiFactorAuth API. */
public class MultiFactorAuth internal constructor(
    private val transport: Transport,
) {
    /**
     * Verify Challenge
     *
     * Verifies an Authentication Challenge.
     *
     * @param id The unique ID of the Authentication Challenge.
     * @param code The one-time code to verify.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `AuthenticationChallengeVerifyResponse` returned by the API.
     */
    public suspend fun verifyChallenge(
        id: String,
        code: String,
        requestOptions: RequestOptions? = null,
    ): AuthenticationChallengeVerifyResponse {
        val path = "auth/challenges/${PathEncoding.segment(id)}/verify"
        val payload = JsonBody()
        payload.set("code", code)
        return transport.request<AuthenticationChallengeVerifyResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Enroll Factor
     *
     * Enrolls an Authentication Factor to be used as an additional factor of authentication. The returned ID should be used to create an authentication Challenge.
     *
     * @param type The type of factor to enroll.
     * @param phoneNumber Required when type is 'sms'.
     * @param totpIssuer Required when type is 'totp'.
     * @param totpUser Required when type is 'totp'.
     * @param userId The ID of the user to associate the factor with.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `AuthenticationFactorEnrolled` returned by the API.
     */
    public suspend fun enrollFactor(
        type: AuthenticationFactorsCreateRequestType,
        phoneNumber: String? = null,
        totpIssuer: String? = null,
        totpUser: String? = null,
        userId: String? = null,
        requestOptions: RequestOptions? = null,
    ): AuthenticationFactorEnrolled {
        val path = "auth/factors/enroll"
        val payload = JsonBody()
        payload.set("type", type)
        payload.set("phone_number", phoneNumber)
        payload.set("totp_issuer", totpIssuer)
        payload.set("totp_user", totpUser)
        payload.set("user_id", userId)
        return transport.request<AuthenticationFactorEnrolled>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get Factor
     *
     * Gets an Authentication Factor.
     *
     * @param id The unique ID of the Factor.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `AuthenticationFactor` returned by the API.
     */
    public suspend fun getFactor(
        id: String,
        requestOptions: RequestOptions? = null,
    ): AuthenticationFactor {
        val path = "auth/factors/${PathEncoding.segment(id)}"
        return transport.request<AuthenticationFactor>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Delete Factor
     *
     * Permanently deletes an Authentication Factor. It cannot be undone.
     *
     * @param id The unique ID of the Factor.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     */
    public suspend fun deleteFactor(
        id: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "auth/factors/${PathEncoding.segment(id)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Challenge Factor
     *
     * Creates a Challenge for an Authentication Factor.
     *
     * @param id The unique ID of the Authentication Factor to be challenged.
     * @param smsTemplate A custom template for the SMS message. Use the {{code}} placeholder to include the verification code.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `AuthenticationChallenge` returned by the API.
     */
    public suspend fun challengeFactor(
        id: String,
        smsTemplate: String? = null,
        requestOptions: RequestOptions? = null,
    ): AuthenticationChallenge {
        val path = "auth/factors/${PathEncoding.segment(id)}/challenge"
        val payload = JsonBody()
        payload.set("sms_template", smsTemplate)
        return transport.request<AuthenticationChallenge>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * List authentication factors
     *
     * Lists the [authentication factors](https://workos.com/docs/reference/authkit/mfa/authentication-factor) for a user.
     *
     * @param userlandUserId The ID of the [user](https://workos.com/docs/reference/authkit/user).
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `Page<AuthenticationFactor>` returned by the API.
     */
    public suspend fun listUserAuthFactors(
        userlandUserId: String,
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<AuthenticationFactor> {
        val path = "user_management/users/${PathEncoding.segment(userlandUserId)}/auth_factors"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<AuthenticationFactor>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listUserAuthFactors]: emits every item across successive pages as the flow is collected.
     *
     * @param userlandUserId The ID of the [user](https://workos.com/docs/reference/authkit/user).
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return A cold flow of `AuthenticationFactor` values.
     */
    public fun listUserAuthFactorsAutoPaging(
        userlandUserId: String,
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<AuthenticationFactor> =
        autoPagingFlow { cursor ->
            listUserAuthFactors(
                userlandUserId = userlandUserId,
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }

    /**
     * Enroll an authentication factor
     *
     * Enrolls a user in a new [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor).
     *
     * @param userlandUserId The ID of the [user](https://workos.com/docs/reference/authkit/user).
     * @param type The type of the factor to enroll.
     * @param totpIssuer Your application or company name displayed in the user's authenticator app.
     * @param totpUser The user's account name displayed in their authenticator app.
     * @param totpSecret The Base32-encoded shared secret for TOTP factors. This can be provided when creating the auth factor, otherwise it will be generated. The algorithm used to derive TOTP codes is SHA-1, the code length is 6 digits, and the timestep is 30 seconds – the secret must be compatible with these parameters.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `UserAuthenticationFactorEnrollResponse` returned by the API.
     */
    public suspend fun createUserAuthFactor(
        userlandUserId: String,
        type: String,
        totpIssuer: String? = null,
        totpUser: String? = null,
        totpSecret: String? = null,
        requestOptions: RequestOptions? = null,
    ): UserAuthenticationFactorEnrollResponse {
        val path = "user_management/users/${PathEncoding.segment(userlandUserId)}/auth_factors"
        val payload = JsonBody()
        payload.set("type", type)
        payload.set("totp_issuer", totpIssuer)
        payload.set("totp_user", totpUser)
        payload.set("totp_secret", totpSecret)
        return transport.request<UserAuthenticationFactorEnrollResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }
}
