// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.PaginationOrder
import com.workos.android.enums.UserManagementOrganizationMembershipStatuses
import com.workos.android.internal.JsonBody
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.Group
import com.workos.android.models.OrganizationMembership
import com.workos.android.models.UserOrganizationMembership
import kotlinx.coroutines.flow.Flow

/** Operations for the OrganizationMembershipResource API. */
public class OrganizationMembershipResource internal constructor(
    private val transport: Transport,
) {
    /**
     * List organization memberships
     *
     * Get a list of all organization memberships matching the criteria specified. At least one of `user_id` or `organization_id` must be provided. By default only active memberships are returned. Use the `statuses` parameter to filter by other statuses.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param organizationId The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
     * @param statuses Filter by the status of the organization membership. Array including any of `active`, `inactive`, or `pending`.
     * @param userId The ID of the [user](https://workos.com/docs/reference/authkit/user).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `Page<UserOrganizationMembership>` returned by the API.
     */
    public suspend fun list(
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        organizationId: String? = null,
        statuses: List<UserManagementOrganizationMembershipStatuses>? = null,
        userId: String? = null,
        requestOptions: RequestOptions? = null,
    ): Page<UserOrganizationMembership> {
        val path = "user_management/organization_memberships"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        statuses?.let {
            for (value in it) {
                query.add(QueryParam("statuses", value.rawValue))
            }
        }
        userId?.let { query.add(QueryParam("user_id", it)) }
        return transport.request<Page<UserOrganizationMembership>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [list]: emits every item across successive pages as the flow is collected.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param organizationId The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
     * @param statuses Filter by the status of the organization membership. Array including any of `active`, `inactive`, or `pending`.
     * @param userId The ID of the [user](https://workos.com/docs/reference/authkit/user).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return A cold flow of `UserOrganizationMembership` values.
     */
    public fun listAutoPaging(
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        organizationId: String? = null,
        statuses: List<UserManagementOrganizationMembershipStatuses>? = null,
        userId: String? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<UserOrganizationMembership> =
        autoPagingFlow { cursor ->
            list(
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                organizationId = organizationId,
                statuses = statuses,
                userId = userId,
                requestOptions = requestOptions,
            )
        }

    /**
     * Create an organization membership
     *
     * Creates a new `active` organization membership for the given organization and user.
     *
     * Calling this API with an organization and user that match an `inactive` organization membership will activate the membership with the specified role(s).
     *
     * @param userId The ID of the [user](https://workos.com/docs/reference/authkit/user).
     * @param organizationId The ID of the [organization](https://workos.com/docs/reference/organization) which the user belongs to.
     * @param roleSlug A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`.
     * @param roleSlugs An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `OrganizationMembership` returned by the API.
     */
    public suspend fun create(
        userId: String,
        organizationId: String,
        roleSlug: String? = null,
        roleSlugs: List<String>? = null,
        requestOptions: RequestOptions? = null,
    ): OrganizationMembership {
        val path = "user_management/organization_memberships"
        val payload = JsonBody()
        payload.set("user_id", userId)
        payload.set("organization_id", organizationId)
        payload.set("role_slug", roleSlug)
        payload.set("role_slugs", roleSlugs)
        return transport.request<OrganizationMembership>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get an organization membership
     *
     * Get the details of an existing organization membership.
     *
     * @param id The unique ID of the organization membership.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `UserOrganizationMembership` returned by the API.
     */
    public suspend fun get(
        id: String,
        requestOptions: RequestOptions? = null,
    ): UserOrganizationMembership {
        val path = "user_management/organization_memberships/${PathEncoding.segment(id)}"
        return transport.request<UserOrganizationMembership>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Update an organization membership
     *
     * Update the details of an existing organization membership.
     *
     * @param id The unique ID of the organization membership.
     * @param roleSlug A single role identifier. Defaults to `member` or the explicit default role. Mutually exclusive with `role_slugs`.
     * @param roleSlugs An array of role identifiers. Limited to one role when Multiple Roles is disabled. Mutually exclusive with `role_slug`.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `UserOrganizationMembership` returned by the API.
     */
    public suspend fun update(
        id: String,
        roleSlug: String? = null,
        roleSlugs: List<String>? = null,
        requestOptions: RequestOptions? = null,
    ): UserOrganizationMembership {
        val path = "user_management/organization_memberships/${PathEncoding.segment(id)}"
        val payload = JsonBody()
        payload.set("role_slug", roleSlug)
        payload.set("role_slugs", roleSlugs)
        return transport.request<UserOrganizationMembership>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete an organization membership
     *
     * Permanently deletes an existing organization membership. It cannot be undone.
     *
     * @param id The unique ID of the organization membership.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     */
    public suspend fun delete(
        id: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "user_management/organization_memberships/${PathEncoding.segment(id)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Deactivate an organization membership
     *
     * Deactivates an `active` organization membership. Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful deactivation.
     *
     * - Deactivating an `inactive` membership is a no-op and does not emit an event.
     * - Deactivating a `pending` membership returns an error. This membership should be [deleted](https://workos.com/docs/reference/authkit/organization-membership/delete) instead.
     *
     * See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
     *
     * @param id The unique ID of the organization membership.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `OrganizationMembership` returned by the API.
     */
    public suspend fun deactivate(
        id: String,
        requestOptions: RequestOptions? = null,
    ): OrganizationMembership {
        val path = "user_management/organization_memberships/${PathEncoding.segment(id)}/deactivate"
        return transport.request<OrganizationMembership>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Reactivate an organization membership
     *
     * Reactivates an `inactive` organization membership, retaining the pre-existing role(s). Emits an [organization_membership.updated](https://workos.com/docs/events/organization-membership) event upon successful reactivation.
     *
     * - Reactivating an `active` membership is a no-op and does not emit an event.
     * - Reactivating a `pending` membership returns an error. The user needs to [accept the invitation](https://workos.com/docs/authkit/invitations) instead.
     *
     * See the [membership management documentation](https://workos.com/docs/authkit/users-organizations/organizations/membership-management) for additional details.
     *
     * @param id The unique ID of the organization membership.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `UserOrganizationMembership` returned by the API.
     */
    public suspend fun reactivate(
        id: String,
        requestOptions: RequestOptions? = null,
    ): UserOrganizationMembership {
        val path = "user_management/organization_memberships/${PathEncoding.segment(id)}/reactivate"
        return transport.request<UserOrganizationMembership>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * List groups
     *
     * Get a list of groups that an organization membership belongs to.
     *
     * @param omId Unique identifier of the Organization Membership.
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `Page<Group>` returned by the API.
     */
    public suspend fun listGroups(
        omId: String,
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<Group> {
        val path = "user_management/organization_memberships/${PathEncoding.segment(omId)}/groups"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<Group>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listGroups]: emits every item across successive pages as the flow is collected.
     *
     * @param omId Unique identifier of the Organization Membership.
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return A cold flow of `Group` values.
     */
    public fun listGroupsAutoPaging(
        omId: String,
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<Group> =
        autoPagingFlow { cursor ->
            listGroups(
                omId = omId,
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }
}
