// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.ConnectedAccountInputState
import com.workos.android.enums.CreateDataIntegrationAuthMethods
import com.workos.android.enums.PaginationOrder
import com.workos.android.internal.JsonBody
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.ApiKeyInstallation
import com.workos.android.models.ConnectedAccount
import com.workos.android.models.CustomProviderDefinition
import com.workos.android.models.DataIntegration
import com.workos.android.models.DataIntegrationAccessTokenResponse
import com.workos.android.models.DataIntegrationAuthorizeUrlResponse
import com.workos.android.models.DataIntegrationCredentialsInput
import com.workos.android.models.DataIntegrationCredentialsResponse
import com.workos.android.models.DataIntegrationsListResponse
import com.workos.android.models.UpdateCustomProviderDefinition
import kotlinx.coroutines.flow.Flow
import kotlinx.datetime.Instant

/** Operations for the Pipes API. */
public class Pipes internal constructor(
    private val transport: Transport,
) {
    /**
     * List data integrations
     *
     * Lists the environment's data integrations configured with `custom` or `organization` credentials, including custom providers and API key integrations.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `Page<DataIntegration>` returned by the API.
     */
    public suspend fun listDataIntegrations(
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<DataIntegration> {
        val path = "data-integrations"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<DataIntegration>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listDataIntegrations]: emits every item across successive pages as the flow is collected.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return A cold flow of `DataIntegration` values.
     */
    public fun listDataIntegrationsAutoPaging(
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<DataIntegration> =
        autoPagingFlow { cursor ->
            listDataIntegrations(
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }

    /**
     * Create a data integration
     *
     * Creates a data integration for a provider. Set `credentials.type` to `custom` to use your own OAuth app credentials or `organization` to have each organization supply its own. Set `auth_methods` to `["api_key"]` to create an API key integration; you may optionally supply an `api_key` block to install a first tenant in the same call. For a built-in provider, pass its slug as `provider`. For a custom provider, pass a new slug plus a `custom_provider` definition.
     *
     * @param provider The provider to create a Data Integration for. For a built-in provider use its slug (e.g. `github`, `slack`). For a custom provider, this is the new provider slug and `custom_provider` must be supplied. A custom provider slug cannot shadow an existing global provider slug.
     * @param description An optional description of the Data Integration.
     * @param enabled Whether the Data Integration is enabled. Defaults to `false`.
     * @param scopes The OAuth scopes to request for the Data Integration. Defaults to the provider's configured scopes when omitted.
     * @param authMethods How accounts authenticate with the provider. Defaults to `["oauth"]`. Use `["api_key"]` to declare an API key integration; `credentials` is then not required and keys are supplied per-tenant (optionally via `api_key` on this request).
     * @param config Provider-specific config values (e.g. a Snowflake `account_identifier`), keyed by the config field. Only fields the built-in provider declares are accepted.
     * @param credentials The OAuth credentials to configure for the Data Integration. Required for OAuth integrations; omit when `auth_methods` is `["api_key"]`.
     * @param apiKey An optional API key to install for the first tenant on an `api_key` integration. Omit to declare a keyless integration; tenants can be added later via the per-installation API key path.
     * @param customProvider The OAuth definition for a custom provider. Supply this to define a custom provider; omit it to create an integration for a built-in provider.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegration` returned by the API.
     */
    public suspend fun createDataIntegration(
        provider: String,
        description: String? = null,
        enabled: Boolean? = null,
        scopes: List<String>? = null,
        authMethods: List<CreateDataIntegrationAuthMethods>? = null,
        config: Map<String, String>? = null,
        credentials: DataIntegrationCredentialsInput? = null,
        apiKey: ApiKeyInstallation? = null,
        customProvider: CustomProviderDefinition? = null,
        requestOptions: RequestOptions? = null,
    ): DataIntegration {
        val path = "data-integrations"
        val payload = JsonBody()
        payload.set("provider", provider)
        payload.set("description", description)
        payload.set("enabled", enabled)
        payload.set("scopes", scopes)
        payload.set("auth_methods", authMethods)
        payload.set("config", config)
        payload.set("credentials", credentials)
        payload.set("api_key", apiKey)
        payload.set("custom_provider", customProvider)
        return transport.request<DataIntegration>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get a data integration
     *
     * Retrieves a data integration by its slug.
     *
     * @param slug The slug identifier of the data integration.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegration` returned by the API.
     */
    public suspend fun getDataIntegration(
        slug: String,
        requestOptions: RequestOptions? = null,
    ): DataIntegration {
        val path = "data-integrations/${PathEncoding.segment(slug)}"
        return transport.request<DataIntegration>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Update a data integration
     *
     * Updates the description, enabled state, or custom credentials of a data integration. For custom providers, `custom_provider` updates the OAuth definition.
     *
     * @param slug The slug identifier of the data integration.
     * @param description An optional description of the Data Integration.
     * @param enabled Whether the Data Integration is enabled.
     * @param scopes The OAuth scopes to request for the Data Integration. Pass `null` to reset to the provider's configured scopes.
     * @param credentials New OAuth credentials for the Data Integration. When provided, rotates the stored client secret. Mutually exclusive with `api_key`.
     * @param apiKey An API key to install or rotate for a tenant on an `api_key` integration. Upserts the tenant installation identified by `user_id` (and optional `organization_id`).
     * @param customProvider Updates to a custom provider's OAuth definition. Only valid for custom-provider integrations.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegration` returned by the API.
     */
    public suspend fun updateDataIntegration(
        slug: String,
        description: String? = null,
        enabled: Boolean? = null,
        scopes: List<String>? = null,
        credentials: DataIntegrationCredentialsInput? = null,
        apiKey: ApiKeyInstallation? = null,
        customProvider: UpdateCustomProviderDefinition? = null,
        requestOptions: RequestOptions? = null,
    ): DataIntegration {
        val path = "data-integrations/${PathEncoding.segment(slug)}"
        val payload = JsonBody()
        payload.set("description", description)
        payload.set("enabled", enabled)
        payload.set("scopes", scopes)
        payload.set("credentials", credentials)
        payload.set("api_key", apiKey)
        payload.set("custom_provider", customProvider)
        return transport.request<DataIntegration>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete a data integration
     *
     * Deletes a data integration and all of its connected installations. For a custom provider, also deletes the custom provider definition.
     *
     * @param slug The slug identifier of the data integration.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     */
    public suspend fun deleteDataIntegration(
        slug: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "data-integrations/${PathEncoding.segment(slug)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Upsert an API key for a connected account
     *
     * Creates or updates an API-key-based installation for the specified integration and user. If an installation already exists, the stored API key is rotated to the new value.
     *
     * @param slug The identifier of the integration.
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param secret The API key secret to store for this integration.
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `ConnectedAccount` returned by the API.
     */
    public suspend fun updateDataIntegrationApiKey(
        slug: String,
        userId: String,
        secret: String,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectedAccount {
        val path = "data-integrations/${PathEncoding.segment(slug)}/api-key"
        val payload = JsonBody()
        payload.set("user_id", userId)
        payload.set("organization_id", organizationId)
        payload.set("secret", secret)
        return transport.request<ConnectedAccount>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get authorization URL
     *
     * Generates an OAuth authorization URL to initiate the connection flow for a user. Redirect the user to the returned URL to begin the OAuth flow with the third-party provider.
     *
     * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param userId The ID of the user to authorize.
     * @param organizationId An organization ID to scope the authorization to a specific organization.
     * @param returnTo The URL to redirect the user to after authorization.
     * @param config Connect-time config values for the provider-declared `installation`-scope fields (e.g. a Zendesk `subdomain`), keyed by the config field. Only fields the provider declares may be supplied, and required fields must be provided unless already pinned on the integration.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegrationAuthorizeUrlResponse` returned by the API.
     */
    public suspend fun authorizeDataIntegration(
        slug: String,
        userId: String,
        organizationId: String? = null,
        returnTo: String? = null,
        config: Map<String, String>? = null,
        requestOptions: RequestOptions? = null,
    ): DataIntegrationAuthorizeUrlResponse {
        val path = "data-integrations/${PathEncoding.segment(slug)}/authorize"
        val payload = JsonBody()
        payload.set("user_id", userId)
        payload.set("organization_id", organizationId)
        payload.set("return_to", returnTo)
        payload.set("config", config)
        return transport.request<DataIntegrationAuthorizeUrlResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Vend credentials for a connected account
     *
     * Returns credentials for a user's connected account. Branches on the installation's `auth_method`: OAuth installations return an access token (refreshed if needed); API-key installations return the stored secret.
     *
     * @param slug The identifier of the integration.
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegrationCredentialsResponse` returned by the API.
     */
    public suspend fun createDataIntegrationCredential(
        slug: String,
        userId: String,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): DataIntegrationCredentialsResponse {
        val path = "data-integrations/${PathEncoding.segment(slug)}/credentials"
        val payload = JsonBody()
        payload.set("user_id", userId)
        payload.set("organization_id", organizationId)
        return transport.request<DataIntegrationCredentialsResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get an access token for a connected account
     *
     * Fetches a valid OAuth access token for a user's connected account. WorkOS automatically handles token refresh, ensuring you always receive a valid, non-expired token.
     *
     * @param provider The identifier of the integration.
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegrationAccessTokenResponse` returned by the API.
     */
    public suspend fun getAccessToken(
        provider: String,
        userId: String,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): DataIntegrationAccessTokenResponse {
        val path = "data-integrations/${PathEncoding.segment(provider)}/token"
        val payload = JsonBody()
        payload.set("user_id", userId)
        payload.set("organization_id", organizationId)
        return transport.request<DataIntegrationAccessTokenResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Get a connected account
     *
     * Retrieves a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) for a specific provider.
     *
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `ConnectedAccount` returned by the API.
     */
    public suspend fun getUserConnectedAccount(
        userId: String,
        slug: String,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectedAccount {
        val path = "user_management/users/${PathEncoding.segment(userId)}/connected_accounts/${PathEncoding.segment(slug)}"
        val query = mutableListOf<QueryParam>()
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        return transport.request<ConnectedAccount>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Import a connected account
     *
     * Imports a [connected account](https://workos.com/docs/reference/pipes/connected-account) for a user by providing OAuth tokens directly. Use this to migrate existing connections or set up connections without going through the OAuth flow.
     *
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param accessToken The OAuth access token for the connected account.
     * @param refreshToken The OAuth refresh token for the connected account.
     * @param expiresAt The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
     * @param scopes The OAuth scopes granted for this connection.
     * @param state Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `ConnectedAccount` returned by the API.
     */
    public suspend fun createUserConnectedAccount(
        userId: String,
        slug: String,
        accessToken: String? = null,
        refreshToken: String? = null,
        expiresAt: Instant? = null,
        scopes: List<String>? = null,
        state: ConnectedAccountInputState? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectedAccount {
        val path = "user_management/users/${PathEncoding.segment(userId)}/connected_accounts/${PathEncoding.segment(slug)}"
        val query = mutableListOf<QueryParam>()
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        val payload = JsonBody()
        payload.set("access_token", accessToken)
        payload.set("refresh_token", refreshToken)
        payload.set("expires_at", expiresAt)
        payload.set("scopes", scopes)
        payload.set("state", state)
        return transport.request<ConnectedAccount>(
            method = "POST",
            path = path,
            query = query,
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Update a connected account
     *
     * Updates a user's [connected account](https://workos.com/docs/reference/pipes/connected-account) tokens, scopes, or state for a specific provider.
     *
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param accessToken The OAuth access token for the connected account.
     * @param refreshToken The OAuth refresh token for the connected account.
     * @param expiresAt The ISO-8601 timestamp when the access token expires. Required when `access_token` is provided for tokens that expire.
     * @param scopes The OAuth scopes granted for this connection.
     * @param state Explicitly set the state of the connected account. When omitted, the state is derived from the token combination provided.
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `ConnectedAccount` returned by the API.
     */
    public suspend fun updateUserConnectedAccount(
        userId: String,
        slug: String,
        accessToken: String? = null,
        refreshToken: String? = null,
        expiresAt: Instant? = null,
        scopes: List<String>? = null,
        state: ConnectedAccountInputState? = null,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): ConnectedAccount {
        val path = "user_management/users/${PathEncoding.segment(userId)}/connected_accounts/${PathEncoding.segment(slug)}"
        val query = mutableListOf<QueryParam>()
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        val payload = JsonBody()
        payload.set("access_token", accessToken)
        payload.set("refresh_token", refreshToken)
        payload.set("expires_at", expiresAt)
        payload.set("scopes", scopes)
        payload.set("state", state)
        return transport.request<ConnectedAccount>(
            method = "PUT",
            path = path,
            query = query,
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete a connected account
     *
     * Disconnects WorkOS's account for the user, including removing any stored access and refresh tokens. The user will need to reauthorize if they want to reconnect. This does not revoke access on the provider side.
     *
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier.
     * @param slug The slug identifier of the provider (e.g., `github`, `slack`, `notion`).
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter if the connection is scoped to an organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     */
    public suspend fun deleteUserConnectedAccount(
        userId: String,
        slug: String,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "user_management/users/${PathEncoding.segment(userId)}/connected_accounts/${PathEncoding.segment(slug)}"
        val query = mutableListOf<QueryParam>()
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * List providers for a user
     *
     * Retrieves a list of available providers and the user's connection status for each. Returns all providers configured for your environment, along with the user's [connected account](https://workos.com/docs/reference/pipes/connected-account) information where applicable.
     *
     * @param userId A [User](https://workos.com/docs/reference/authkit/user) identifier to list providers and connected accounts for.
     * @param organizationId An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to filter connections for a specific organization.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `DataIntegrationsListResponse` returned by the API.
     */
    public suspend fun listUserDataProviders(
        userId: String,
        organizationId: String? = null,
        requestOptions: RequestOptions? = null,
    ): DataIntegrationsListResponse {
        val path = "user_management/users/${PathEncoding.segment(userId)}/data_providers"
        val query = mutableListOf<QueryParam>()
        organizationId?.let { query.add(QueryParam("organization_id", it)) }
        return transport.request<DataIntegrationsListResponse>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }
}
