// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.VaultOrder
import com.workos.android.internal.JsonBody
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.CreateDataKeyResponse
import com.workos.android.models.DecryptResponse
import com.workos.android.models.ObjectMetadata
import com.workos.android.models.ObjectSummary
import com.workos.android.models.ObjectWithoutValue
import com.workos.android.models.VaultObject
import com.workos.android.models.VersionListResponse
import kotlinx.coroutines.flow.Flow
import kotlinx.datetime.Instant

/** Operations for the Vault API. */
public class Vault internal constructor(
    private val transport: Transport,
) {
    /**
     * Create a data key
     *
     * Generate an isolated encryption key for local encryption operations.
     *
     * @param context Map of values used to determine the encryption key.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `CreateDataKeyResponse` returned by the API.
     */
    public suspend fun createDataKey(
        context: Map<String, String>,
        requestOptions: RequestOptions? = null,
    ): CreateDataKeyResponse {
        val path = "vault/v1/keys/data-key"
        val payload = JsonBody()
        payload.set("context", context)
        return transport.request<CreateDataKeyResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Decrypt a data key
     *
     * Decrypt a previously encrypted data key from WorkOS Vault.
     *
     * @param keys Base64-encoded encrypted data key to decrypt.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `DecryptResponse` returned by the API.
     */
    public suspend fun createDecrypt(
        keys: String,
        requestOptions: RequestOptions? = null,
    ): DecryptResponse {
        val path = "vault/v1/keys/decrypt"
        val payload = JsonBody()
        payload.set("keys", keys)
        return transport.request<DecryptResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Re-encrypt a data key
     *
     * Decrypt an existing data key and re-encrypt it under a new key context.
     *
     * @param context Map of values used to determine the new encryption key.
     * @param encryptedKeys Base64-encoded encrypted data key blob to re-encrypt.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `CreateDataKeyResponse` returned by the API.
     */
    public suspend fun createRekey(
        context: Map<String, String>,
        encryptedKeys: String,
        requestOptions: RequestOptions? = null,
    ): CreateDataKeyResponse {
        val path = "vault/v1/keys/rekey"
        val payload = JsonBody()
        payload.set("context", context)
        payload.set("encrypted_keys", encryptedKeys)
        return transport.request<CreateDataKeyResponse>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * List objects
     *
     * List all encrypted objects with cursor-based pagination.
     *
     * @param limit Upper limit on the number of objects to return.
     * @param before Cursor for the previous page of results.
     * @param after Cursor for the next page of results.
     * @param order Sort direction for results.
     * @param search Filter results by name or structured search JSON.
     * @param updatedAfter ISO 8601 timestamp to filter by last modified time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `Page<ObjectSummary>` returned by the API.
     */
    public suspend fun listKv(
        limit: Long? = null,
        before: String? = null,
        after: String? = null,
        order: VaultOrder? = null,
        search: String? = null,
        updatedAfter: Instant? = null,
        requestOptions: RequestOptions? = null,
    ): Page<ObjectSummary> {
        val path = "vault/v1/kv"
        val query = mutableListOf<QueryParam>()
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        search?.let { query.add(QueryParam("search", it)) }
        updatedAfter?.let { query.add(QueryParam("updatedAfter", it.toString())) }
        return transport.request<Page<ObjectSummary>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listKv]: emits every item across successive pages as the flow is collected.
     *
     * @param limit Upper limit on the number of objects to return.
     * @param before Cursor for the previous page of results.
     * @param order Sort direction for results.
     * @param search Filter results by name or structured search JSON.
     * @param updatedAfter ISO 8601 timestamp to filter by last modified time.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return A cold flow of `ObjectSummary` values.
     */
    public fun listKvAutoPaging(
        limit: Long? = null,
        before: String? = null,
        order: VaultOrder? = null,
        search: String? = null,
        updatedAfter: Instant? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<ObjectSummary> =
        autoPagingFlow { cursor ->
            listKv(
                limit = limit,
                before = before,
                after = cursor,
                order = order,
                search = search,
                updatedAfter = updatedAfter,
                requestOptions = requestOptions,
            )
        }

    /**
     * Create an object
     *
     * Encrypt and store a new key-value object.
     *
     * @param keyContext Map of values used to determine the encryption key.
     * @param name Unique name for the object.
     * @param value Plaintext data to encrypt and store.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ObjectMetadata` returned by the API.
     */
    public suspend fun createKv(
        keyContext: Map<String, String>,
        name: String,
        value: String,
        requestOptions: RequestOptions? = null,
    ): ObjectMetadata {
        val path = "vault/v1/kv"
        val payload = JsonBody()
        payload.set("key_context", keyContext)
        payload.set("name", name)
        payload.set("value", value)
        return transport.request<ObjectMetadata>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Read an object by name
     *
     * Fetch and decrypt an object by its unique name.
     *
     * @param name Unique name of the object.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `VaultObject` returned by the API.
     */
    public suspend fun getName(
        name: String,
        requestOptions: RequestOptions? = null,
    ): VaultObject {
        val path = "vault/v1/kv/name/${PathEncoding.segment(name)}"
        return transport.request<VaultObject>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Read an object by ID
     *
     * Fetch and decrypt an object by its unique identifier.
     *
     * @param id Unique identifier of the object.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `VaultObject` returned by the API.
     */
    public suspend fun getKv(
        id: String,
        requestOptions: RequestOptions? = null,
    ): VaultObject {
        val path = "vault/v1/kv/${PathEncoding.segment(id)}"
        return transport.request<VaultObject>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Update an object
     *
     * Update the value of an existing encrypted object.
     *
     * @param id Unique identifier of the object.
     * @param value New plaintext value.
     * @param versionCheck ID of the expected current version for optimistic locking.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ObjectWithoutValue` returned by the API.
     */
    public suspend fun updateKv(
        id: String,
        value: String,
        versionCheck: String? = null,
        requestOptions: RequestOptions? = null,
    ): ObjectWithoutValue {
        val path = "vault/v1/kv/${PathEncoding.segment(id)}"
        val payload = JsonBody()
        payload.set("value", value)
        payload.set("version_check", versionCheck)
        return transport.request<ObjectWithoutValue>(
            method = "PUT",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete an object
     *
     * Delete an encrypted object.
     *
     * @param id Unique identifier of the object.
     * @param versionCheck Expected current version for optimistic locking.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     */
    public suspend fun deleteKv(
        id: String,
        versionCheck: String? = null,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "vault/v1/kv/${PathEncoding.segment(id)}"
        val query = mutableListOf<QueryParam>()
        versionCheck?.let { query.add(QueryParam("version_check", it)) }
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Describe an object
     *
     * Fetch metadata for an object without decrypting it.
     *
     * @param id Unique identifier of the object.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `ObjectWithoutValue` returned by the API.
     */
    public suspend fun listKvMetadata(
        id: String,
        requestOptions: RequestOptions? = null,
    ): ObjectWithoutValue {
        val path = "vault/v1/kv/${PathEncoding.segment(id)}/metadata"
        return transport.request<ObjectWithoutValue>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }

    /**
     * List object versions
     *
     * Retrieve all versions for a specific object.
     *
     * @param id Unique identifier of the object.
     * @param requestOptions Per-request overrides: extra headers, timeout, retries, base URL, idempotency key.
     * @return The `VersionListResponse` returned by the API.
     */
    public suspend fun listKvVersions(
        id: String,
        requestOptions: RequestOptions? = null,
    ): VersionListResponse {
        val path = "vault/v1/kv/${PathEncoding.segment(id)}/versions"
        return transport.request<VersionListResponse>(
            method = "GET",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }
}
