// This file is auto-generated by oagen. Do not edit.

package com.workos.android.resources

import com.workos.android.Page
import com.workos.android.RequestOptions
import com.workos.android.enums.CreateWebhookEndpointEvents
import com.workos.android.enums.PaginationOrder
import com.workos.android.enums.UpdateWebhookEndpointEvents
import com.workos.android.enums.UpdateWebhookEndpointStatus
import com.workos.android.internal.JsonBody
import com.workos.android.internal.PathEncoding
import com.workos.android.internal.QueryParam
import com.workos.android.internal.Transport
import com.workos.android.internal.autoPagingFlow
import com.workos.android.models.WebhookEndpoint
import kotlinx.coroutines.flow.Flow

/** Operations for the Webhooks API. */
public class Webhooks internal constructor(
    private val transport: Transport,
) {
    /**
     * List Webhook Endpoints
     *
     * Get a list of all of your existing webhook endpoints.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param after An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `after="obj_123"` to fetch a new batch of objects after `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `Page<WebhookEndpoint>` returned by the API.
     */
    public suspend fun listEndpoints(
        before: String? = null,
        after: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Page<WebhookEndpoint> {
        val path = "webhook_endpoints"
        val query = mutableListOf<QueryParam>()
        before?.let { query.add(QueryParam("before", it)) }
        after?.let { query.add(QueryParam("after", it)) }
        limit?.let { query.add(QueryParam("limit", it.toString())) }
        order?.let { query.add(QueryParam("order", it.rawValue)) }
        return transport.request<Page<WebhookEndpoint>>(
            method = "GET",
            path = path,
            query = query,
            body = null,
            options = requestOptions,
        )
    }

    /**
     * Auto-paginating variant of [listEndpoints]: emits every item across successive pages as the flow is collected.
     *
     * @param before An object ID that defines your place in the list. When the ID is not present, you are at the end of the list. For example, if you make a list request and receive 100 objects, ending with `"obj_123"`, your subsequent call can include `before="obj_123"` to fetch a new batch of objects before `"obj_123"`.
     * @param limit Upper limit on the number of objects to return, between `1` and `100`.
     * @param order Order the results by the creation time. Supported values are `"asc"` (ascending), `"desc"` (descending), and `"normal"` (descending with reversed cursor semantics where `before` fetches older records and `after` fetches newer records).
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return A cold flow of `WebhookEndpoint` values.
     */
    public fun listEndpointsAutoPaging(
        before: String? = null,
        limit: Long? = null,
        order: PaginationOrder? = null,
        requestOptions: RequestOptions? = null,
    ): Flow<WebhookEndpoint> =
        autoPagingFlow { cursor ->
            listEndpoints(
                before = before,
                after = cursor,
                limit = limit,
                order = order,
                requestOptions = requestOptions,
            )
        }

    /**
     * Create a Webhook Endpoint
     *
     * Create a new webhook endpoint to receive event notifications.
     *
     * @param endpointUrl The HTTPS URL where webhooks will be sent.
     * @param events The events that the Webhook Endpoint is subscribed to.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `WebhookEndpoint` returned by the API.
     */
    public suspend fun createEndpoint(
        endpointUrl: String,
        events: List<CreateWebhookEndpointEvents>,
        requestOptions: RequestOptions? = null,
    ): WebhookEndpoint {
        val path = "webhook_endpoints"
        val payload = JsonBody()
        payload.set("endpoint_url", endpointUrl)
        payload.set("events", events)
        return transport.request<WebhookEndpoint>(
            method = "POST",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Update a Webhook Endpoint
     *
     * Update the properties of an existing webhook endpoint.
     *
     * @param id Unique identifier of the Webhook Endpoint.
     * @param endpointUrl The HTTPS URL where webhooks will be sent.
     * @param status Whether the Webhook Endpoint is enabled or disabled.
     * @param events The events that the Webhook Endpoint is subscribed to.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     * @return The `WebhookEndpoint` returned by the API.
     */
    public suspend fun updateEndpoint(
        id: String,
        endpointUrl: String? = null,
        status: UpdateWebhookEndpointStatus? = null,
        events: List<UpdateWebhookEndpointEvents>? = null,
        requestOptions: RequestOptions? = null,
    ): WebhookEndpoint {
        val path = "webhook_endpoints/${PathEncoding.segment(id)}"
        val payload = JsonBody()
        payload.set("endpoint_url", endpointUrl)
        payload.set("status", status)
        payload.set("events", events)
        return transport.request<WebhookEndpoint>(
            method = "PATCH",
            path = path,
            query = emptyList(),
            body = payload,
            options = requestOptions,
        )
    }

    /**
     * Delete a Webhook Endpoint
     *
     * Delete an existing webhook endpoint.
     *
     * @param id Unique identifier of the Webhook Endpoint.
     * @param requestOptions Per-request overrides (idempotency key, API key, headers, timeout).
     */
    public suspend fun deleteEndpoint(
        id: String,
        requestOptions: RequestOptions? = null,
    ) {
        val path = "webhook_endpoints/${PathEncoding.segment(id)}"
        transport.requestVoid(
            method = "DELETE",
            path = path,
            query = emptyList(),
            body = null,
            options = requestOptions,
        )
    }
}
