// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AgentAdminLinkClaimAttemptToExternalUserRequest(
    /** The operation to perform on the claim attempt. Currently only `link_external_user` is supported. */
    @SerialName("type")
    public val type: String,
    /** The token identifying the claim attempt. */
    @SerialName("claim_attempt_token")
    public val claimAttemptToken: String,
    /** The user to attach to the claim attempt, identified by email and external ID. */
    @SerialName("user")
    public val user: AgentAdminLinkClaimAttemptToExternalUserRequestUser,
    /** The organization to place the agent in. Required when the user belongs to more than one organization. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
