// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AgentCredentialValidation(
    /** Whether the presented credential is valid. */
    @SerialName("valid")
    public val valid: Boolean,
    /** Identifier of the agent registration the credential belongs to, or `null` when the credential is invalid. */
    @SerialName("registration_id")
    public val registrationId: String? = null,
    /** The timestamp when the credential expires, or `null` when the credential is invalid. */
    @SerialName("expires_at")
    public val expiresAt: Instant? = null,
)
