// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class AgentRegistrationDeletedData(
    /** The agent registration that was deleted. */
    @SerialName("agent_registration_id")
    public val agentRegistrationId: String,
)
