// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The agent identity associated with this registration. */
@Serializable
public data class AgentRegistrationAgentIdentity(
    /** Unique identifier of the agent identity. */
    @SerialName("id")
    public val id: String,
    /** The timestamp when the agent identity was created. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** The timestamp when the agent identity was last updated. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** Identifier of the AuthKit user the agent identity is bound to, or `null` when the agent is not associated with a user. */
    @SerialName("userland_user_id")
    public val userlandUserId: String? = null,
)
