// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class AgentRegistrationClaimAttemptCreatedData(
    /** Distinguishes the agent registration claim attempt object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the agent registration claim attempt. */
    @SerialName("id")
    public val id: String,
    /** The ID of the agent registration. */
    @SerialName("agent_registration_id")
    public val agentRegistrationId: String,
    /** The ID of the agent registration claim. */
    @SerialName("agent_registration_claim_id")
    public val agentRegistrationClaimId: String,
    /** The login hint for the claim attempt. */
    @SerialName("login_hint")
    public val loginHint: String,
    /** The timestamp when the claim attempt expires. */
    @SerialName("expires_at")
    public val expiresAt: String,
    /** The timestamp when the claim attempt was created. */
    @SerialName("created_at")
    public val createdAt: String,
    /** The timestamp when the claim attempt was last updated. */
    @SerialName("updated_at")
    public val updatedAt: String,
)
