// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class AgentRegistrationClaimCompletedData(
    /** Distinguishes the agent registration claim object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the agent registration claim. */
    @SerialName("id")
    public val id: String,
    /** The ID of the agent registration. */
    @SerialName("agent_registration_id")
    public val agentRegistrationId: String,
    /** The ID of the claim attempt that completed the claim. */
    @SerialName("completed_by_attempt_id")
    public val completedByAttemptId: String,
    /** The user who completed the claim. */
    @SerialName("claimed_by")
    public val claimedBy: AgentRegistrationClaimCompletedDataClaimedBy,
    /** The timestamp when the claim was completed. */
    @SerialName("completed_at")
    public val completedAt: String,
    /** The timestamp when the claim was created. */
    @SerialName("created_at")
    public val createdAt: String,
    /** The timestamp when the claim was last updated. */
    @SerialName("updated_at")
    public val updatedAt: String,
)
