// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** The user who completed the claim. */
@Serializable
public data class AgentRegistrationClaimCompletedDataClaimedBy(
    /** The ID of the user who completed the claim. */
    @SerialName("user_id")
    public val userId: String,
    /** The ID of the organization the claiming user belongs to. */
    @SerialName("organization_id")
    public val organizationId: JsonElement,
)
