// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

@Serializable
public data class AgentRegistrationCredentialIssuedDataDetail(
    /** The kind of credential issued. */
    @SerialName("kind")
    public val kind: String,
    /** The ID of the issued API key. */
    @SerialName("api_key_id")
    public val apiKeyId: String? = null,
    /** The JWT ID of the issued access token. */
    @SerialName("jti")
    public val jti: String? = null,
    /** The timestamp when the access token expires. */
    @SerialName("expires_at")
    public val expiresAt: JsonElement? = null,
)
