// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class ApiKeyUpdatedData(
    /** Distinguishes the API key object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the API key. */
    @SerialName("id")
    public val id: String,
    /** The owner of the API key. */
    @SerialName("owner")
    public val owner: ApiKeyUpdatedDataOwner,
    /** The name of the API key. */
    @SerialName("name")
    public val name: String,
    /** The obfuscated value of the API key. */
    @SerialName("obfuscated_value")
    public val obfuscatedValue: String,
    /** The permissions granted to the API key. */
    @SerialName("permissions")
    public val permissions: List<String>,
    /** The timestamp when the API key was created. */
    @SerialName("created_at")
    public val createdAt: String,
    /** The timestamp when the API key was last updated. */
    @SerialName("updated_at")
    public val updatedAt: String,
    /** Previous API key attributes before the update. */
    @SerialName("previous_attributes")
    public val previousAttributes: ApiKeyUpdatedDataPreviousAttribute,
    /** The timestamp when the API key was last used. */
    @SerialName("last_used_at")
    public val lastUsedAt: String? = null,
    /** Timestamp when the API Key expires. Null means the key does not expire. */
    @SerialName("expires_at")
    public val expiresAt: Instant? = null,
)
