// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Previous API key attributes before the update. */
@Serializable
public data class ApiKeyUpdatedDataPreviousAttribute(
    /** The previous timestamp when the API Key expired. Null means the key did not expire. */
    @SerialName("expires_at")
    public val expiresAt: Instant? = null,
)
