// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ApiKeyValidationResponse(
    @SerialName("api_key")
    public val apiKey: ApiKey? = null,
    /** The ID of the agent registration this API Key was issued for. Present only when the API Key is assigned to an agent registration. */
    @SerialName("agent_registration_id")
    public val agentRegistrationId: String? = null,
)
