// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuditLogAction(
    /** Distinguishes the Audit Log Action object. */
    @SerialName("object")
    public val `object`: String,
    /** Identifier of what action was taken. */
    @SerialName("name")
    public val name: String,
    /** The schema associated with the action. */
    @SerialName("schema")
    public val schema: AuditLogSchema,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
)
