// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.AuditLogConfigurationState
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuditLogConfiguration(
    /** Unique identifier of the Organization. */
    @SerialName("organization_id")
    public val organizationId: String,
    /** The number of days Audit Log events will be retained before being permanently deleted. */
    @SerialName("retention_period_in_days")
    public val retentionPeriodInDays: Long,
    /** The current state of the audit log configuration for the organization. */
    @SerialName("state")
    public val state: AuditLogConfigurationState,
    /** The Audit Log Stream currently configured for the organization, if any. */
    @SerialName("log_stream")
    public val logStream: AuditLogConfigurationLogStream? = null,
)
