// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.AuditLogExportState
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuditLogExport(
    /** Distinguishes the Audit Log Export object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the Audit Log Export. */
    @SerialName("id")
    public val id: String,
    /** The state of the export. Possible values: pending, ready, error, expired. */
    @SerialName("state")
    public val state: AuditLogExportState,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** A URL to the CSV file. Only defined when the Audit Log Export is ready. */
    @SerialName("url")
    public val url: String? = null,
)
