// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** The metadata schema for the actor. */
@Serializable
public data class AuditLogSchemaActor(
    /** The JSON Schema definition for actor metadata. */
    @SerialName("metadata")
    public val metadata: Map<String, JsonElement>,
)
