// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuditLogExportCreation(
    /** The unique ID of the Organization. */
    @SerialName("organization_id")
    public val organizationId: String,
    /** ISO-8601 value for start of the export range. */
    @SerialName("range_start")
    public val rangeStart: Instant,
    /** ISO-8601 value for end of the export range. */
    @SerialName("range_end")
    public val rangeEnd: Instant,
    /** List of actions to filter against. */
    @SerialName("actions")
    public val actions: List<String>? = null,
    /** Deprecated. Use `actor_names` instead. */
    @Deprecated("This field is deprecated.")
    @SerialName("actors")
    public val actors: List<String>? = null,
    /** List of actor names to filter against. */
    @SerialName("actor_names")
    public val actorNames: List<String>? = null,
    /** List of actor IDs to filter against. */
    @SerialName("actor_ids")
    public val actorIds: List<String>? = null,
    /** List of target types to filter against. */
    @SerialName("targets")
    public val targets: List<String>? = null,
)
