// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.AuthenticationFactorsCreateRequestType
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuthenticationFactorsCreateRequest(
    /** The type of factor to enroll. */
    @SerialName("type")
    public val type: AuthenticationFactorsCreateRequestType,
    /** Required when type is 'sms'. */
    @SerialName("phone_number")
    public val phoneNumber: String? = null,
    /** Required when type is 'totp'. */
    @SerialName("totp_issuer")
    public val totpIssuer: String? = null,
    /** Required when type is 'totp'. */
    @SerialName("totp_user")
    public val totpUser: String? = null,
    /** The ID of the user to associate the factor with. */
    @SerialName("user_id")
    public val userId: String? = null,
)
