// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuthenticationChallengesVerifyRequest(
    /** The one-time code to verify. */
    @SerialName("code")
    public val code: String,
)
