// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuthorizationCheck(
    /** Whether the organization membership has the specified permission on the resource. */
    @SerialName("authorized")
    public val authorized: Boolean,
)
