// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** SMS-based authentication factor details. */
@Serializable
public data class AuthenticationFactorSms(
    /** The user's phone number for SMS-based authentication. */
    @SerialName("phone_number")
    public val phoneNumber: String,
)
