// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.AuthenticationRadarRiskDetectedDataAction
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class AuthenticationRadarRiskDetectedData(
    /** The authentication method used. */
    @SerialName("auth_method")
    public val authMethod: String,
    @SerialName("action")
    public val action: AuthenticationRadarRiskDetectedDataAction,
    /** The ID of the user. */
    @SerialName("user_id")
    public val userId: String,
    /** The email address of the user. */
    @SerialName("email")
    public val email: String,
    /** The control action taken for the detected risk. */
    @SerialName("control")
    public val control: String? = null,
    /** The type of blocklist that triggered the risk detection. */
    @SerialName("blocklist_type")
    public val blocklistType: String? = null,
    /** The IP address of the request. */
    @SerialName("ip_address")
    public val ipAddress: String? = null,
    /** The user agent of the request. */
    @SerialName("user_agent")
    public val userAgent: String? = null,
)
