// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** TOTP-based authentication factor details. */
@Serializable
public data class AuthenticationFactorTotp(
    /** Your application or company name displayed in the user's authenticator app. Defaults to your WorkOS team name. */
    @SerialName("issuer")
    public val issuer: String,
    /** The user's account name displayed in their authenticator app. Defaults to the user's email. */
    @SerialName("user")
    public val user: String,
)
