// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class AuthenticationChallenge(
    /** Distinguishes the authentication challenge object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the authentication challenge. */
    @SerialName("id")
    public val id: String,
    /** The unique ID of the authentication factor the challenge belongs to. */
    @SerialName("authentication_factor_id")
    public val authenticationFactorId: String,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The timestamp when the challenge will expire. Does not apply to TOTP factors. */
    @SerialName("expires_at")
    public val expiresAt: Instant? = null,
    /** The one-time code for the challenge. */
    @SerialName("code")
    public val code: String? = null,
)
