// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CheckAuthorization(
    /** The slug of the permission to check. */
    @SerialName("permission_slug")
    public val permissionSlug: String,
    /** The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`. */
    @SerialName("resource_id")
    public val resourceId: String? = null,
    /** The external ID of the resource. Required with `resource_type_slug`. Mutually exclusive with `resource_id`. */
    @SerialName("resource_external_id")
    public val resourceExternalId: String? = null,
    /** The slug of the resource type. Required with `resource_external_id`. Mutually exclusive with `resource_id`. */
    @SerialName("resource_type_slug")
    public val resourceTypeSlug: String? = null,
)
