// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ClaimViewResponseStatus
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ClaimViewResponse(
    /** The agent registration ID. */
    @SerialName("id")
    public val id: String,
    /** Current status of the agent registration. */
    @SerialName("status")
    public val status: ClaimViewResponseStatus,
    /** The user code the agent needs to complete the claim. */
    @SerialName("user_code")
    public val userCode: String,
    /** Organizations the user belongs to, offered as placement choices. */
    @SerialName("organizations")
    public val organizations: List<ClaimViewResponseOrganization>,
)
