// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ConfigureDataIntegrationBody(
    /** Whether the provider is enabled for the organization. */
    @SerialName("enabled")
    public val enabled: Boolean? = null,
    /** The OAuth scopes to request for the organization. Pass `null` to inherit the provider scopes. */
    @SerialName("scopes")
    public val scopes: List<String>? = null,
    /** The OAuth client ID of the organization's own application. Must be provided together with `client_secret`, and only for providers whose credentials are supplied by the organization. */
    @SerialName("client_id")
    public val clientId: String? = null,
    /** The OAuth client secret of the organization's own application. Must be provided together with `client_id`. */
    @SerialName("client_secret")
    public val clientSecret: String? = null,
    /** Provider-specific config values to set for the organization, keyed by config field. Only fields the provider declares are accepted, and each value must match that field's pattern. Accepted only for providers whose credentials are organization-managed; for shared or custom credential providers, config belongs on the integration itself (via the data-integrations API) and supplying it here is rejected. */
    @SerialName("config")
    public val config: Map<String, String>? = null,
)
