// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ConfirmEmailChange(
    /** The one-time code used to confirm the email change. */
    @SerialName("code")
    public val code: String,
)
