// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ConnectionDeletedDataConnectionType
import com.workos.android.enums.ConnectionDeletedDataState
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class ConnectionDeletedData(
    /** Distinguishes the connection object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the connection. */
    @SerialName("id")
    public val id: String,
    /** The current state of the connection. */
    @SerialName("state")
    public val state: ConnectionDeletedDataState,
    /** The name of the connection. */
    @SerialName("name")
    public val name: String,
    /** The type of the connection. */
    @SerialName("connection_type")
    public val connectionType: ConnectionDeletedDataConnectionType,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The ID of the organization the connection belongs to. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
