// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ConnectApplicationM2M(
    /** Distinguishes the connect application object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the connect application. */
    @SerialName("id")
    public val id: String,
    /** The client ID of the connect application. */
    @SerialName("client_id")
    public val clientId: String,
    /** The name of the connect application. */
    @SerialName("name")
    public val name: String,
    /** The scopes available for this application. */
    @SerialName("scopes")
    public val scopes: List<String>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The type of the application. */
    @SerialName("application_type")
    public val applicationType: String,
    /** The ID of the organization the application belongs to. */
    @SerialName("organization_id")
    public val organizationId: String,
    /** A description of the connect application. */
    @SerialName("description")
    public val description: String? = null,
)
