// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class ConnectionSAMLCertificateRenewedData(
    /** The connection with the renewed certificate. */
    @SerialName("connection")
    public val connection: ConnectionSAMLCertificateRenewedDataConnection,
    /** The renewed SAML certificate details. */
    @SerialName("certificate")
    public val certificate: ConnectionSAMLCertificateRenewedDataCertificate,
    /** An ISO 8601 timestamp. */
    @SerialName("renewed_at")
    public val renewedAt: Instant,
)
