// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ConnectionState
import com.workos.android.enums.ConnectionStatus
import com.workos.android.enums.ConnectionType
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class Connection(
    /** Distinguishes the Connection object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier for the Connection. */
    @SerialName("id")
    public val id: String,
    /** The type of the SSO Connection used to authenticate the user. The Connection type may be used to dynamically generate authorization URLs. */
    @SerialName("connection_type")
    public val connectionType: ConnectionType,
    /** A human-readable name for the Connection. This will most commonly be the organization's name. */
    @SerialName("name")
    public val name: String,
    /** Indicates whether a Connection is able to authenticate users. */
    @SerialName("state")
    public val state: ConnectionState,
    /** Deprecated. Use `state` instead. */
    @Deprecated("This field is deprecated.")
    @SerialName("status")
    public val status: ConnectionStatus,
    /** List of Organization Domains. */
    @SerialName("domains")
    public val domains: List<ConnectionDomain>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** Unique identifier for the Organization in which the Connection resides. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
