// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ConnectionSAMLCertificateRenewedDataCertificateCertificateType
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The renewed SAML certificate details. */
@Serializable
public data class ConnectionSAMLCertificateRenewedDataCertificate(
    /** The type of the SAML certificate. */
    @SerialName("certificate_type")
    public val certificateType: ConnectionSAMLCertificateRenewedDataCertificateCertificateType,
    /** An ISO 8601 timestamp. */
    @SerialName("expiry_date")
    public val expiryDate: Instant,
)
