// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ConnectedAccountAuthMethod
import com.workos.android.enums.ConnectedAccountState
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ConnectedAccount(
    /** Distinguishes the connected account object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique identifier of the connected account. */
    @SerialName("id")
    public val id: String,
    /** The OAuth scopes granted for this connection. */
    @SerialName("scopes")
    public val scopes: List<String>,
    /**
     * The state of the connected account:
     * - `connected`: The connection is active and tokens are valid.
     * - `needs_reauthorization`: The user needs to reauthorize the connection, typically because required scopes have changed.
     * - `disconnected`: The connection has been disconnected.
     */
    @SerialName("state")
    public val state: ConnectedAccountState,
    /** The timestamp when the connection was created. */
    @SerialName("created_at")
    public val createdAt: String,
    /** The timestamp when the connection was last updated. */
    @SerialName("updated_at")
    public val updatedAt: String,
    /** The [User](https://workos.com/docs/reference/authkit/user) identifier associated with this connection. */
    @SerialName("user_id")
    public val userId: String? = null,
    /** The [Organization](https://workos.com/docs/reference/organization) identifier associated with this connection, or `null` if not scoped to an organization. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
    /** The authentication method used for this connection (`oauth`, `api_key`, or `client_credentials`). Defaults to `oauth` if absent. */
    @SerialName("auth_method")
    public val authMethod: ConnectedAccountAuthMethod? = null,
    /** The last four characters of the API key, or `null` for OAuth connections. */
    @SerialName("api_key_last_4")
    public val apiKeyLast4: String? = null,
)
