// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The SAML certificate details. */
@Serializable
public data class ConnectionSAMLCertificateRenewalRequiredDataCertificate(
    /** The type of the SAML certificate. */
    @SerialName("certificate_type")
    public val certificateType: ConnectionSAMLCertificateRenewalRequiredDataCertificateCertificateType,
    /** An ISO 8601 timestamp. */
    @SerialName("expiry_date")
    public val expiryDate: Instant,
    /** Whether the certificate has already expired. */
    @SerialName("is_expired")
    public val isExpired: Boolean,
)
