// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The connection with the expiring certificate. */
@Serializable
public data class ConnectionSAMLCertificateRenewalRequiredDataConnection(
    /** Unique identifier of the connection. */
    @SerialName("id")
    public val id: String,
    /** The ID of the organization the connection belongs to. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
