// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ConnectionDomain(
    /** Unique identifier for the Connection Domain. */
    @SerialName("id")
    public val id: String,
    /** Distinguishes the Connection Domain object. */
    @SerialName("object")
    public val `object`: String,
    /** The domain value. */
    @SerialName("domain")
    public val domain: String,
)
