// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateOrganizationApiKey(
    /** The name for the API key. */
    @SerialName("name")
    public val name: String,
    /** The permission slugs to assign to the API key. */
    @SerialName("permissions")
    public val permissions: List<String>? = null,
    /** The timestamp when the API key should expire. Must be a future timestamp. If omitted, the key does not expire. */
    @SerialName("expires_at")
    public val expiresAt: Instant? = null,
)
