// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateObjectRequest(
    /** Map of values used to determine the encryption key. */
    @SerialName("key_context")
    public val keyContext: Map<String, String>,
    /** Unique name for the object. */
    @SerialName("name")
    public val name: String,
    /** Plaintext data to encrypt and store. */
    @SerialName("value")
    public val value: String,
)
