// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateAuthorizationPermission(
    /** A unique key to reference the permission. Must be lowercase and contain only letters, numbers, hyphens, underscores, colons, periods, and asterisks. */
    @SerialName("slug")
    public val slug: String,
    /** A descriptive name for the Permission. */
    @SerialName("name")
    public val name: String,
    /** An optional description of the Permission. */
    @SerialName("description")
    public val description: String? = null,
    /** The slug of the resource type this permission is scoped to. */
    @SerialName("resource_type_slug")
    public val resourceTypeSlug: String? = null,
)
