// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateGroupMembership(
    /** The ID of the Organization Membership to add to the group. */
    @SerialName("organization_membership_id")
    public val organizationMembershipId: String,
)
