// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateGroupRoleAssignment(
    /** The slug of the role to assign to the group. */
    @SerialName("role_slug")
    public val roleSlug: String,
    /** The ID of the resource. Omit along with the external-id fields to target the organization itself. */
    @SerialName("resource_id")
    public val resourceId: String? = null,
    /** The external ID of the resource. */
    @SerialName("resource_external_id")
    public val resourceExternalId: String? = null,
    /** The resource type slug. */
    @SerialName("resource_type_slug")
    public val resourceTypeSlug: String? = null,
)
