// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateCorsOrigin(
    /** The origin URL to allow for CORS requests. */
    @SerialName("origin")
    public val origin: String,
)
