// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CreateDataKeyRequest(
    /** Map of values used to determine the encryption key. */
    @SerialName("context")
    public val context: Map<String, String>,
)
