// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.CustomProviderDefinitionAuthenticateVia
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class CustomProviderDefinition(
    /** A descriptive name for the custom provider. */
    @SerialName("name")
    public val name: String,
    /** The provider's OAuth authorization endpoint. */
    @SerialName("authorization_url")
    public val authorizationUrl: String,
    /** The provider's OAuth token endpoint. */
    @SerialName("token_url")
    public val tokenUrl: String,
    /** The endpoint used to refresh tokens, if different from the token endpoint. */
    @SerialName("refresh_token_url")
    public val refreshTokenUrl: String? = null,
    /** Whether PKCE is used during the authorization code flow. Defaults to `true`. */
    @SerialName("pkce_enabled")
    public val pkceEnabled: Boolean? = null,
    /** The separator used to join requested scopes. Defaults to a space. */
    @SerialName("request_scope_separator")
    public val requestScopeSeparator: String? = null,
    /** Whether at least one scope must be selected when connecting an account. Defaults to `false`. */
    @SerialName("scopes_required")
    public val scopesRequired: Boolean? = null,
    /** Whether a client secret is required for this provider. Defaults to `true`. */
    @SerialName("client_secret_required")
    public val clientSecretRequired: Boolean? = null,
    /** Additional static query parameters appended to the authorization request. */
    @SerialName("additional_authorization_parameters")
    public val additionalAuthorizationParameters: Map<String, String>? = null,
    /** The Content-Type used when exchanging the token request. */
    @SerialName("token_body_content_type")
    public val tokenBodyContentType: String? = null,
    /** How client credentials are sent when exchanging authorization codes and refreshing tokens. */
    @SerialName("authenticate_via")
    public val authenticateVia: CustomProviderDefinitionAuthenticateVia? = null,
)
