// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DataIntegrationsVendCredentialsRequest(
    /** A [User](https://workos.com/docs/reference/authkit/user) identifier. */
    @SerialName("user_id")
    public val userId: String,
    /** An [Organization](https://workos.com/docs/reference/organization) identifier. Optional parameter to scope the connection to a specific organization. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
