// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.DataIntegrationCredentialsInputType
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DataIntegrationCredentialsInput(
    /** The credentials type. `custom` uses your own OAuth app credentials; `organization` has each organization supply its own credentials (configured per-organization). */
    @SerialName("type")
    public val type: DataIntegrationCredentialsInputType,
    /** OAuth client ID for the provider app. Required when `type` is `custom`; omit for `organization`. */
    @SerialName("client_id")
    public val clientId: String? = null,
    /** OAuth client secret for the provider app. Required when `type` is `custom`; omit for `organization`. */
    @SerialName("client_secret")
    public val clientSecret: String? = null,
)
