// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DataIntegrationInstallation(
    /** Unique identifier of the installation. */
    @SerialName("id")
    public val id: String,
    /** The User the API key was installed for. */
    @SerialName("user_id")
    public val userId: String,
    /** The Organization the installation is scoped to, or null when unscoped. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
    /** The last four characters of the stored API key. The full key is never returned. */
    @SerialName("api_key_last_4")
    public val apiKeyLast4: String? = null,
)
