// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The credential object containing the vended secret. */
@Serializable
public data class DataIntegrationCredentialsResponseCredential(
    /** Distinguishes the credential object. */
    @SerialName("object")
    public val `object`: String,
    /** The authentication method for this credential. Additional values may be added in the future; handle unknown values gracefully. */
    @SerialName("auth_method")
    public val authMethod: String,
    /** The OAuth access token. */
    @SerialName("value")
    public val value: String,
    /** The scopes granted to the access token. */
    @SerialName("scopes")
    public val scopes: List<String>,
    /** If the integration has requested scopes that aren't present on the access token, they're listed here. */
    @SerialName("missing_scopes")
    public val missingScopes: List<String>,
    /** The ISO-8601 formatted timestamp indicating when the credential expires. */
    @SerialName("expires_at")
    public val expiresAt: String? = null,
)
