// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.DataIntegrationAccessTokenResponseError
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DataIntegrationAccessTokenResponse(
    /** Indicates whether the access token is valid and ready for use, or if reauthorization is required. */
    @SerialName("active")
    public val active: Boolean? = null,
    /** The [access token](https://workos.com/docs/reference/pipes/access-token) object, present when `active` is `true`. */
    @SerialName("access_token")
    public val accessToken: DataIntegrationAccessTokenResponseAccessToken? = null,
    /**
     * - `"not_installed"`: The user does not have the integration installed.
     * - `"needs_reauthorization"`: The user needs to reauthorize the integration.
     */
    @SerialName("error")
    public val error: DataIntegrationAccessTokenResponseError? = null,
)
