// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.DataIntegrationAuthMethods
import com.workos.android.enums.DataIntegrationState
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DataIntegration(
    /** Distinguishes the Data Integration object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the Data Integration. */
    @SerialName("id")
    public val id: String,
    /** The provider slug for this Data Integration. */
    @SerialName("slug")
    public val slug: String,
    /** The integration type derived from the provider. */
    @SerialName("integration_type")
    public val integrationType: String,
    /** Whether the Data Integration is enabled. */
    @SerialName("enabled")
    public val enabled: Boolean,
    /** The state of the Data Integration. */
    @SerialName("state")
    public val state: DataIntegrationState,
    /** The OAuth redirect URI to register with the provider when configuring the custom application. */
    @SerialName("redirect_uri")
    public val redirectUri: String,
    /** How accounts authenticate with the provider for this Data Integration. */
    @SerialName("auth_methods")
    public val authMethods: List<DataIntegrationAuthMethods>,
    /** The credentials configured for the Data Integration. */
    @SerialName("credentials")
    public val credentials: DataIntegrationCredential,
    /** Provider-specific config values set on the Data Integration (e.g. a Snowflake `account_identifier`), keyed by config field. Only fields the provider declares are accepted. */
    @SerialName("config")
    public val config: Map<String, String>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** An optional description of the Data Integration. */
    @SerialName("description")
    public val description: String? = null,
    /** The OAuth scopes configured for the Data Integration. `null` when the provider's configured scopes are used. */
    @SerialName("scopes")
    public val scopes: List<String>? = null,
    /** The tenant installation created when an API key was supplied at creation time; `null` otherwise. Not populated on list/get responses. */
    @SerialName("installation")
    public val installation: DataIntegrationInstallation? = null,
    /** The OAuth definition when this is a custom provider; `null` for built-in providers. */
    @SerialName("custom_provider")
    public val customProvider: DataIntegrationCustomProvider? = null,
)
