// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DeleteGroupRoleAssignmentsByCriteria(
    /** The slug of the role to remove assignments for. */
    @SerialName("role_slug")
    public val roleSlug: String,
    /** The ID of the resource. Mutually exclusive with `resource_external_id` and `resource_type_slug`. */
    @SerialName("resource_id")
    public val resourceId: String? = null,
    /** The external ID of the resource. */
    @SerialName("resource_external_id")
    public val resourceExternalId: String? = null,
    /** The resource type slug. */
    @SerialName("resource_type_slug")
    public val resourceTypeSlug: String? = null,
)
