// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Counts of active and inactive directory users. */
@Serializable
public data class DirectoryMetadataUser(
    /** Count of active directory users. */
    @SerialName("active")
    public val active: Long,
    /** Count of inactive directory users. */
    @SerialName("inactive")
    public val inactive: Long,
)
