// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class DsyncUserUpdatedDataEmail(
    /** Whether this is the primary email address. */
    @SerialName("primary")
    public val primary: Boolean? = null,
    /** The type of email address. */
    @SerialName("type")
    public val type: String? = null,
    /** The email address value. */
    @SerialName("value")
    public val value: String? = null,
)
