// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.DsyncDeletedDataState
import com.workos.android.enums.DsyncDeletedDataType
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class DsyncDeletedData(
    /** Distinguishes the directory object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the directory. */
    @SerialName("id")
    public val id: String,
    /** The type of the directory. */
    @SerialName("type")
    public val type: DsyncDeletedDataType,
    /** The current state of the directory. */
    @SerialName("state")
    public val state: DsyncDeletedDataState,
    /** The name of the directory. */
    @SerialName("name")
    public val name: String,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The ID of the organization the directory belongs to. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
