// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class DsyncTokenRevokedData(
    /** Distinguishes the directory token object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the directory token. */
    @SerialName("id")
    public val id: String,
    /** The ID of the directory the token authenticates to. */
    @SerialName("directory_id")
    public val directoryId: String,
    /** The trailing characters of the bearer token, for identification only. The full token value is never included in events. */
    @SerialName("token_suffix")
    public val tokenSuffix: String,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** The ID of the organization the directory belongs to. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
)
