// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class EmailChangeConfirmation(
    /** Distinguishes the email change confirmation object. */
    @SerialName("object")
    public val `object`: String,
    /** The user object. */
    @SerialName("user")
    public val user: EmailChangeConfirmationUser,
)
