// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class EmailVerificationCreatedData(
    /** Distinguishes the email verification object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the email verification code. */
    @SerialName("id")
    public val id: String,
    /** The unique ID of the user. */
    @SerialName("user_id")
    public val userId: String,
    /** The email address of the user. */
    @SerialName("email")
    public val email: String,
    /** The timestamp when the email verification code expires. */
    @SerialName("expires_at")
    public val expiresAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
)
