// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class EnrollUserAuthenticationFactor(
    /** The type of the factor to enroll. */
    @SerialName("type")
    public val type: String,
    /** Your application or company name displayed in the user's authenticator app. */
    @SerialName("totp_issuer")
    public val totpIssuer: String? = null,
    /** The user's account name displayed in their authenticator app. */
    @SerialName("totp_user")
    public val totpUser: String? = null,
    /** The Base32-encoded shared secret for TOTP factors. This can be provided when creating the auth factor, otherwise it will be generated. The algorithm used to derive TOTP codes is SHA-1, the code length is 6 digits, and the timestep is 30 seconds – the secret must be compatible with these parameters. */
    @SerialName("totp_secret")
    public val totpSecret: String? = null,
)
