// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.EventContextActorSource
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The actor who performed the action. */
@Serializable
public data class EventContextActor(
    /** Unique identifier of the actor. */
    @SerialName("id")
    public val id: String,
    /** The source of the actor that performed the action. */
    @SerialName("source")
    public val source: EventContextActorSource,
    /** The name of the actor. */
    @SerialName("name")
    public val name: String? = null,
)
