// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JsonElement

/** Additional context about the event. */
@Serializable
public data class EventContext(
    /** The Google Analytics client ID. */
    @SerialName("google_analytics_client_id")
    public val googleAnalyticsClientId: String? = null,
    /** The Google Analytics sessions associated with the event. */
    @SerialName("google_analytics_sessions")
    public val googleAnalyticsSessions: List<EventContextGoogleAnalyticsSession>? = null,
    /** The anonymous ID from analytics. */
    @SerialName("ajs_anonymous_id")
    public val ajsAnonymousId: String? = null,
    /** The client ID associated with the event. */
    @SerialName("client_id")
    public val clientId: String? = null,
    @SerialName("actor")
    public val actor: EventContextActor? = null,
    /** Attributes that changed from their previous values. */
    @SerialName("previous_attributes")
    public val previousAttributes: Map<String, JsonElement>? = null,
)
