// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Additional context about the event. */
@Serializable
public data class FlagCreatedContext(
    /** The client ID associated with the flag event. */
    @SerialName("client_id")
    public val clientId: String,
    /** The actor who performed the action. */
    @SerialName("actor")
    public val actor: FlagCreatedContextActor,
)
