// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class FlagRuleUpdatedContextConfiguredTargetUser(
    /** The ID of the user. */
    @SerialName("id")
    public val id: String,
    /** The email of the user. */
    @SerialName("email")
    public val email: String,
)
