// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.FlagRuleUpdatedContextActorSource
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The actor who performed the action. */
@Serializable
public data class FlagRuleUpdatedContextActor(
    /** Unique identifier of the actor. */
    @SerialName("id")
    public val id: String,
    @SerialName("source")
    public val source: FlagRuleUpdatedContextActorSource,
    /** The name of the actor. */
    @SerialName("name")
    public val name: String? = null,
)
