// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class Group(
    /** The Group object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the Group. */
    @SerialName("id")
    public val id: String,
    /** The ID of the Organization the Group belongs to. */
    @SerialName("organization_id")
    public val organizationId: String,
    /** The name of the Group. */
    @SerialName("name")
    public val name: String,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** An optional description of the Group. */
    @SerialName("description")
    public val description: String? = null,
)
