// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class JwksResponse(
    /** The public keys used for verifying access tokens. */
    @SerialName("keys")
    public val keys: List<JwksResponseKeys>,
)
