// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** A static snapshot of an encrypted object. */
@Serializable
public data class ObjectVersion(
    /** Timestamp when the version was created. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** Whether this is the active version. */
    @SerialName("current_version")
    public val currentVersion: Boolean,
    /** Hash of the object value. */
    @SerialName("etag")
    public val etag: String,
    /** Unique identifier of the version. */
    @SerialName("id")
    public val id: String,
    /** Number of bytes of stored data. */
    @SerialName("size")
    public val size: Long,
)
