// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** Metadata for a stored encrypted object. */
@Serializable
public data class ObjectMetadata(
    /** Map of values used to determine the encryption key. */
    @SerialName("context")
    public val context: Map<String, String>,
    /** Environment the object belongs to. */
    @SerialName("environment_id")
    public val environmentId: String,
    /** Unique identifier of the object. */
    @SerialName("id")
    public val id: String,
    /** Encryption key identifier. */
    @SerialName("key_id")
    public val keyId: String,
    /** Timestamp of the last update. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    @SerialName("updated_by")
    public val updatedBy: Actor,
    /** Current version identifier of the object. */
    @SerialName("version_id")
    public val versionId: String? = null,
)
