// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.OrganizationDomainDataState
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class OrganizationDomainData(
    /** The domain value. */
    @SerialName("domain")
    public val domain: String,
    /** The verification state of the domain. */
    @SerialName("state")
    public val state: OrganizationDomainDataState,
)
