// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class OrganizationInput(
    /** The name of the organization. */
    @SerialName("name")
    public val name: String,
    /** Whether the organization allows profiles from outside the organization to sign in. */
    @SerialName("allow_profiles_outside_organization")
    public val allowProfilesOutsideOrganization: Boolean? = null,
    /** The domains associated with the organization. Deprecated in favor of `domain_data`. */
    @SerialName("domains")
    public val domains: List<String>? = null,
    /** The domains associated with the organization, including verification state. */
    @SerialName("domain_data")
    public val domainData: List<OrganizationDomainData>? = null,
    /** Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization. */
    @SerialName("metadata")
    public val metadata: Map<String, String>? = null,
    /** An external identifier for the Organization. */
    @SerialName("external_id")
    public val externalId: String? = null,
)
