// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class OrganizationDeletedData(
    /** Distinguishes the Organization object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the Organization. */
    @SerialName("id")
    public val id: String,
    /** A descriptive name for the Organization. This field does not need to be unique. */
    @SerialName("name")
    public val name: String,
    /** List of Organization Domains. */
    @SerialName("domains")
    public val domains: List<OrganizationDeletedDataDomain>,
    /** Object containing [metadata](https://workos.com/docs/authkit/metadata) key/value pairs associated with the Organization. */
    @SerialName("metadata")
    public val metadata: Map<String, String>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The external ID of the Organization. */
    @SerialName("external_id")
    public val externalId: String? = null,
    /** The Stripe customer ID of the Organization. */
    @SerialName("stripe_customer_id")
    public val stripeCustomerId: String? = null,
)
