// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class OrganizationRoleCreatedData(
    /** Distinguishes the organization role object. */
    @SerialName("object")
    public val `object`: String,
    /** The ID of the organization the role belongs to. */
    @SerialName("organization_id")
    public val organizationId: String,
    /** The slug identifier of the role. */
    @SerialName("slug")
    public val slug: String,
    /** The name of the role. */
    @SerialName("name")
    public val name: String,
    /** The slug of the resource type the role applies to. */
    @SerialName("resource_type_slug")
    public val resourceTypeSlug: String,
    /** The permissions granted by the role. */
    @SerialName("permissions")
    public val permissions: List<String>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** A description of the role. */
    @SerialName("description")
    public val description: String? = null,
)
