// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.OrganizationDeletedDataDomainState
import com.workos.android.enums.OrganizationDeletedDataDomainVerificationStrategy
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class OrganizationDeletedDataDomain(
    /** Distinguishes the organization domain object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the organization domain. */
    @SerialName("id")
    public val id: String,
    /** ID of the parent Organization. */
    @SerialName("organization_id")
    public val organizationId: String,
    /** Domain for the organization domain. */
    @SerialName("domain")
    public val domain: String,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** Verification state of the domain. */
    @SerialName("state")
    public val state: OrganizationDeletedDataDomainState? = null,
    /** The prefix used in DNS verification. */
    @SerialName("verification_prefix")
    public val verificationPrefix: String? = null,
    /** Validation token to be used in DNS TXT record. */
    @SerialName("verification_token")
    public val verificationToken: String? = null,
    /** Strategy used to verify the domain. */
    @SerialName("verification_strategy")
    public val verificationStrategy: OrganizationDeletedDataDomainVerificationStrategy? = null,
)
