// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class PipesConnectedAccountConnectionFailedData(
    /** The object type. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the data integration. */
    @SerialName("data_integration_id")
    public val dataIntegrationId: String,
    /** The provider slug for this connection attempt. */
    @SerialName("provider_slug")
    public val providerSlug: String,
    /** A machine-readable error code for the failure. */
    @SerialName("error_code")
    public val errorCode: String,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** The ID of the User the connection attempt belongs to. */
    @SerialName("user_id")
    public val userId: String? = null,
    /** The ID of the Organization the connection attempt belongs to. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
    /** A human-readable explanation of the failure. */
    @SerialName("error_reason")
    public val errorReason: String? = null,
    /** The raw error code returned by the OAuth provider. */
    @SerialName("provider_error")
    public val providerError: String? = null,
    /** The raw error description returned by the OAuth provider. */
    @SerialName("provider_error_description")
    public val providerErrorDescription: String? = null,
)
