// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class PortalLinkResponse(
    /** An ephemeral link to initiate the Admin Portal. */
    @SerialName("link")
    public val link: String,
)
