// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class RadarSmsChallengeCodeSessionAuthenticateRequest(
    /** The client ID of the application. */
    @SerialName("client_id")
    public val clientId: String,
    /** The client secret of the application. */
    @SerialName("client_secret")
    public val clientSecret: String,
    @SerialName("grant_type")
    public val grantType: String,
    /** The one-time code from the Radar SMS challenge. */
    @SerialName("code")
    public val code: String,
    /** The ID of the Radar SMS verification being confirmed. */
    @SerialName("verification_id")
    public val verificationId: String,
    /** The phone number the Radar SMS challenge was sent to. */
    @SerialName("phone_number")
    public val phoneNumber: String,
    /** The pending authentication token from a previous authentication attempt. */
    @SerialName("pending_authentication_token")
    public val pendingAuthenticationToken: String,
    /** The IP address of the user's request. */
    @SerialName("ip_address")
    public val ipAddress: String? = null,
    /** A unique identifier for the device. */
    @SerialName("device_id")
    public val deviceId: String? = null,
    /** The user agent string from the user's browser. */
    @SerialName("user_agent")
    public val userAgent: String? = null,
)
