// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class RadarListEntryAlreadyPresentResponse(
    /** A message indicating the entry already exists. */
    @SerialName("message")
    public val message: String,
)
