// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.RadarStandaloneAssessRequestAction
import com.workos.android.enums.RadarStandaloneAssessRequestAuthMethod
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class RadarStandaloneAssessRequest(
    /** The IP address of the request to assess. */
    @SerialName("ip_address")
    public val ipAddress: String,
    /** The user agent string of the request to assess. */
    @SerialName("user_agent")
    public val userAgent: String,
    /** The email address of the user making the request. */
    @SerialName("email")
    public val email: String,
    /** The authentication method being used. */
    @SerialName("auth_method")
    public val authMethod: RadarStandaloneAssessRequestAuthMethod,
    /** The action being performed. */
    @SerialName("action")
    public val action: RadarStandaloneAssessRequestAction,
    /** An optional Radar signals ID for the request. */
    @SerialName("signals_id")
    public val signalsId: String? = null,
)
