// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class RekeyRequest(
    /** Map of values used to determine the new encryption key. */
    @SerialName("context")
    public val context: Map<String, String>,
    /** Base64-encoded encrypted data key blob to re-encrypt. */
    @SerialName("encrypted_keys")
    public val encryptedKeys: String,
)
