// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ReplaceGroupRoleAssignments(
    /** The list of role assignments that should exist for the group. All existing assignments will be replaced. */
    @SerialName("role_assignments")
    public val roleAssignments: List<ReplaceGroupRoleAssignmentEntry>,
)
