// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.ResendUserInviteOptionsLocale
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ResendUserInviteOptions(
    /** The locale to use when rendering the invitation email. See [supported locales](https://workos.com/docs/authkit/hosted-ui/localization). */
    @SerialName("locale")
    public val locale: ResendUserInviteOptionsLocale? = null,
)
