// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class RevokeSession(
    /** The ID of the session to revoke. This can be extracted from the `sid` claim of the access token. */
    @SerialName("session_id")
    public val sessionId: String,
)
