// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.RoleType
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class Role(
    /** A unique slug for the role. */
    @SerialName("slug")
    public val slug: String,
    /** Distinguishes the role object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the role. */
    @SerialName("id")
    public val id: String,
    /** A descriptive name for the role. */
    @SerialName("name")
    public val name: String,
    /** Whether the role is scoped to the environment or an organization (custom role). */
    @SerialName("type")
    public val type: RoleType,
    /** The slug of the resource type the role is scoped to. */
    @SerialName("resource_type_slug")
    public val resourceTypeSlug: String,
    /** The permission slugs assigned to the role. */
    @SerialName("permissions")
    public val permissions: List<String>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** An optional description of the role. */
    @SerialName("description")
    public val description: String? = null,
)
