// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class RoleList(
    @SerialName("object")
    public val `object`: String,
    /** The list of records for the current page. */
    @SerialName("data")
    public val data: List<Role>,
)
