// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class SendRadarSmsChallengeResponse(
    /** The ID of the SMS verification. Pass this to the authenticate endpoint to verify the code. */
    @SerialName("verification_id")
    public val verificationId: String,
    /** The phone number the verification code was sent to. */
    @SerialName("phone_number")
    public val phoneNumber: String,
)
