// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class SetRolePermissions(
    /** The permission slugs to assign to the role. */
    @SerialName("permissions")
    public val permissions: List<String>,
)
