// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The primary role assigned to the user. */
@Serializable
public data class SlimRole(
    /** The slug of the assigned role. */
    @SerialName("slug")
    public val slug: String,
)
