// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class SSODeviceAuthorizationRequest(
    /** The WorkOS client ID for your application. */
    @SerialName("client_id")
    public val clientId: String,
)
