// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class SSOTokenResponse(
    /** The type of token issued. */
    @SerialName("token_type")
    public val tokenType: String,
    /** An access token that can be exchanged for a user profile. Access tokens are short-lived — see the `expires_in` field for the exact lifetime. */
    @SerialName("access_token")
    public val accessToken: String,
    /** The lifetime of the access token in seconds. */
    @SerialName("expires_in")
    public val expiresIn: Long,
    /** The user profile returned by the identity provider. */
    @SerialName("profile")
    public val profile: Profile,
    /** OAuth tokens issued by the identity provider, if available. */
    @SerialName("oauth_tokens")
    public val oauthTokens: SSOTokenResponseOAuthToken? = null,
)
