// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** OAuth tokens issued by the identity provider, if available. */
@Serializable
public data class SSOTokenResponseOAuthToken(
    /** The OAuth provider used for authentication. */
    @SerialName("provider")
    public val provider: String,
    /** The refresh token from the OAuth provider. */
    @SerialName("refresh_token")
    public val refreshToken: String,
    /** The access token from the OAuth provider. */
    @SerialName("access_token")
    public val accessToken: String,
    /** The timestamp at which the access token expires. */
    @SerialName("expires_at")
    public val expiresAt: Long,
    /** A list of OAuth scopes for which the access token is authorized. */
    @SerialName("scopes")
    public val scopes: List<String>,
)
