// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class TokenQuery(
    /** The client ID of the WorkOS environment. */
    @SerialName("client_id")
    public val clientId: String,
    /** The client secret of the WorkOS environment. */
    @SerialName("client_secret")
    public val clientSecret: String,
    /** The authorization code received from the authorization callback. */
    @SerialName("code")
    public val code: String,
    /** The grant type for the token request. */
    @SerialName("grant_type")
    public val grantType: String,
)
