// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.UpdateUserPasswordHashType
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UpdateUser(
    /** The email address of the user. */
    @SerialName("email")
    public val email: String? = null,
    /** The first name of the user. */
    @SerialName("first_name")
    public val firstName: String? = null,
    /** The last name of the user. */
    @SerialName("last_name")
    public val lastName: String? = null,
    /** The user's full name. */
    @SerialName("name")
    public val name: String? = null,
    /** Whether the user's email has been verified. */
    @SerialName("email_verified")
    public val emailVerified: Boolean? = null,
    /** Object containing metadata key/value pairs associated with the user. */
    @SerialName("metadata")
    public val metadata: Map<String, String>? = null,
    /** The external ID of the user. */
    @SerialName("external_id")
    public val externalId: String? = null,
    /** The user's preferred locale. */
    @SerialName("locale")
    public val locale: String? = null,
    /** The password to set for the user. Mutually exclusive with `password_hash` and `password_hash_type`. */
    @SerialName("password")
    public val password: String? = null,
    /** The hashed password to set for the user. Required with `password_hash_type`. Mutually exclusive with `password`. */
    @SerialName("password_hash")
    public val passwordHash: String? = null,
    /** The algorithm originally used to hash the password, used when providing a `password_hash`. Required with `password_hash`. Mutually exclusive with `password`. */
    @SerialName("password_hash_type")
    public val passwordHashType: UpdateUserPasswordHashType? = null,
)
