// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UpdateJWTTemplate(
    /** The JWT template content as a Liquid template string. */
    @SerialName("content")
    public val content: String,
)
