// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.UpdateWebhookEndpointEvents
import com.workos.android.enums.UpdateWebhookEndpointStatus
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UpdateWebhookEndpoint(
    /** The HTTPS URL where webhooks will be sent. */
    @SerialName("endpoint_url")
    public val endpointUrl: String? = null,
    /** Whether the Webhook Endpoint is enabled or disabled. */
    @SerialName("status")
    public val status: UpdateWebhookEndpointStatus? = null,
    /** The events that the Webhook Endpoint is subscribed to. */
    @SerialName("events")
    public val events: List<UpdateWebhookEndpointEvents>? = null,
)
