// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UpdateAuthorizationResource(
    /** A display name for the resource. */
    @SerialName("name")
    public val name: String? = null,
    /** An optional description of the resource. */
    @SerialName("description")
    public val description: String? = null,
    /** The ID of the parent resource. Mutually exclusive with `parent_resource_external_id` and `parent_resource_type_slug`. */
    @SerialName("parent_resource_id")
    public val parentResourceId: String? = null,
    /** The external ID of the parent resource. Required with `parent_resource_type_slug`. Mutually exclusive with `parent_resource_id`. */
    @SerialName("parent_resource_external_id")
    public val parentResourceExternalId: String? = null,
    /** The resource type slug of the parent resource. Required with `parent_resource_external_id`. Mutually exclusive with `parent_resource_id`. */
    @SerialName("parent_resource_type_slug")
    public val parentResourceTypeSlug: String? = null,
)
