// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UpdateOAuthApplication(
    /** The name of the application. */
    @SerialName("name")
    public val name: String? = null,
    /** A description for the application. */
    @SerialName("description")
    public val description: String? = null,
    /** The OAuth scopes granted to the application. */
    @SerialName("scopes")
    public val scopes: List<String>? = null,
    /** Updated redirect URIs for the application. OAuth applications only. */
    @SerialName("redirect_uris")
    public val redirectUris: List<RedirectUriInput>? = null,
)
