// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.UserSessionsAuthMethod
import com.workos.android.enums.UserSessionsStatus
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UserSessionsListItem(
    /** Distinguishes the session object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the session. */
    @SerialName("id")
    public val id: String,
    /** The ID of the user this session belongs to. */
    @SerialName("user_id")
    public val userId: String,
    /** The authentication method used to create this session. */
    @SerialName("auth_method")
    public val authMethod: UserSessionsAuthMethod,
    /** The current status of the session. */
    @SerialName("status")
    public val status: UserSessionsStatus,
    /** The timestamp when the session expires. */
    @SerialName("expires_at")
    public val expiresAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** Information about the impersonator if this session was created via impersonation. */
    @SerialName("impersonator")
    public val impersonator: UserSessionsImpersonator? = null,
    /** The IP address from which the session was created. */
    @SerialName("ip_address")
    public val ipAddress: String? = null,
    /** The ID of the organization this session is associated with. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
    /** The user agent string from the device that created the session. */
    @SerialName("user_agent")
    public val userAgent: String? = null,
    /** The timestamp when the session ended. */
    @SerialName("ended_at")
    public val endedAt: Instant? = null,
)
