// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UserAuthenticationFactorEnrollResponse(
    /** The [authentication factor](https://workos.com/docs/reference/authkit/mfa/authentication-factor) object that represents the additional authentication method used on top of the existing authentication strategy. */
    @SerialName("authentication_factor")
    public val authenticationFactor: AuthenticationFactorEnrolled,
    /** The [authentication challenge](https://workos.com/docs/reference/authkit/mfa/authentication-challenge) object that is used to complete the authentication process. */
    @SerialName("authentication_challenge")
    public val authenticationChallenge: AuthenticationChallenge,
)
