// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UserCreateResponse(
    /** Distinguishes the user object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the user. */
    @SerialName("id")
    public val id: String,
    /** The email address of the user. */
    @SerialName("email")
    public val email: String,
    /** Whether the user's email has been verified. */
    @SerialName("email_verified")
    public val emailVerified: Boolean,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The first name of the user. */
    @SerialName("first_name")
    public val firstName: String? = null,
    /** The last name of the user. */
    @SerialName("last_name")
    public val lastName: String? = null,
    /** The user's full name. */
    @SerialName("name")
    public val name: String? = null,
    /** A URL reference to an image representing the user. */
    @SerialName("profile_picture_url")
    public val profilePictureUrl: String? = null,
    /** The external ID of the user. */
    @SerialName("external_id")
    public val externalId: String? = null,
    /** Object containing metadata key/value pairs associated with the user. */
    @SerialName("metadata")
    public val metadata: Map<String, String>? = null,
    /** The timestamp when the user last signed in. */
    @SerialName("last_sign_in_at")
    public val lastSignInAt: Instant? = null,
    /** The user's preferred locale. */
    @SerialName("locale")
    public val locale: String? = null,
    /** The ID of the Radar authentication attempt created for this request when Radar is enabled. Pass this value to the authenticate endpoint to associate the subsequent authentication with this Radar attempt. */
    @SerialName("radar_auth_attempt_id")
    public val radarAuthAttemptId: String? = null,
)
