// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class UserConsentOption(
    /** The claim name for this consent option. */
    @SerialName("claim")
    public val claim: String,
    /** The type of consent option. */
    @SerialName("type")
    public val type: String,
    /** A human-readable label for this consent option. */
    @SerialName("label")
    public val label: String,
    /** The available choices for this consent option. */
    @SerialName("choices")
    public val choices: List<UserConsentOptionChoice>,
)
