// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class ValidateApiKey(
    /** The value for an API key. */
    @SerialName("value")
    public val value: String,
)
