// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.VaultByokKeyProvider
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class VaultByokKeyDeletedData(
    /** The unique identifier of the organization. */
    @SerialName("organization_id")
    public val organizationId: String,
    @SerialName("key_provider")
    public val keyProvider: VaultByokKeyProvider,
)
