// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.VaultDataDeletedDataActorSource
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/** The event payload. */
@Serializable
public data class VaultDataDeletedData(
    /** The unique identifier of the actor. */
    @SerialName("actor_id")
    public val actorId: String,
    @SerialName("actor_source")
    public val actorSource: VaultDataDeletedDataActorSource,
    /** The name of the actor. */
    @SerialName("actor_name")
    public val actorName: String,
    /** The name of the key-value store. */
    @SerialName("kv_name")
    public val kvName: String,
)
