// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class VersionListResponse(
    /** List of object versions. */
    @SerialName("data")
    public val data: List<ObjectVersion>,
    @SerialName("list_metadata")
    public val listMetadata: ListMetadata,
)
