// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.WaitlistUserState
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class WaitlistUser(
    /** Distinguishes the Waitlist User object. */
    @SerialName("object")
    public val `object`: String,
    /** The unique ID of the Waitlist User. */
    @SerialName("id")
    public val id: String,
    /** The email address of the Waitlist User. */
    @SerialName("email")
    public val email: String,
    /** The state of the Waitlist User. */
    @SerialName("state")
    public val state: WaitlistUserState,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
    /** The timestamp when the Waitlist User was approved, or null if not yet approved. */
    @SerialName("approved_at")
    public val approvedAt: Instant? = null,
)
