// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.WebhookEndpointStatus
import kotlinx.datetime.Instant
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class WebhookEndpoint(
    /** Distinguishes the Webhook Endpoint object. */
    @SerialName("object")
    public val `object`: String,
    /** Unique identifier of the Webhook Endpoint. */
    @SerialName("id")
    public val id: String,
    /** The URL to which webhooks are sent. */
    @SerialName("endpoint_url")
    public val endpointUrl: String,
    /** The secret used to sign webhook payloads. */
    @SerialName("secret")
    public val secret: String,
    /** Whether the Webhook Endpoint is enabled or disabled. */
    @SerialName("status")
    public val status: WebhookEndpointStatus,
    /** The events that the Webhook Endpoint is subscribed to. */
    @SerialName("events")
    public val events: List<String>,
    /** An ISO 8601 timestamp. */
    @SerialName("created_at")
    public val createdAt: Instant,
    /** An ISO 8601 timestamp. */
    @SerialName("updated_at")
    public val updatedAt: Instant,
)
