// This file is auto-generated by oagen. Do not edit.

package com.workos.android.models

import com.workos.android.enums.WidgetSessionTokenScopes
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
public data class WidgetSessionToken(
    /** The ID of the organization to scope the widget session to. Required when scopes are provided. Optional when issuing a token for user-only widgets (e.g. `UserProfile`, `UserSecurity`) that do not require organization context. */
    @SerialName("organization_id")
    public val organizationId: String? = null,
    /** The ID of the user to issue the widget session token for. */
    @SerialName("user_id")
    public val userId: String? = null,
    /** The scopes to grant the widget session. */
    @SerialName("scopes")
    public val scopes: List<WidgetSessionTokenScopes>? = null,
)
