// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid AgentRegistrationCreatedDataMethod values. */
@Serializable(with = AgentRegistrationCreatedDataMethod.Serializer::class)
public sealed class AgentRegistrationCreatedDataMethod(
    public val rawValue: String,
) {
    public data object Anonymous : AgentRegistrationCreatedDataMethod("anonymous")

    public data object ServiceAuth : AgentRegistrationCreatedDataMethod("service_auth")

    public data object IdJag : AgentRegistrationCreatedDataMethod("id_jag")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : AgentRegistrationCreatedDataMethod(value)

    public companion object {
        public val allKnownValues: List<AgentRegistrationCreatedDataMethod> = listOf(Anonymous, ServiceAuth, IdJag)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): AgentRegistrationCreatedDataMethod =
            when (rawValue) {
                "anonymous" -> Anonymous
                "service_auth" -> ServiceAuth
                "id_jag" -> IdJag
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<AgentRegistrationCreatedDataMethod> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("AgentRegistrationCreatedDataMethod", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): AgentRegistrationCreatedDataMethod = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: AgentRegistrationCreatedDataMethod,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
