// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid AgentRegistrationKind values. */
@Serializable(with = AgentRegistrationKind.Serializer::class)
public sealed class AgentRegistrationKind(
    public val rawValue: String,
) {
    public data object Anonymous : AgentRegistrationKind("anonymous")

    public data object ServiceAuth : AgentRegistrationKind("service_auth")

    public data object IdentityAssertion : AgentRegistrationKind("identity_assertion")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : AgentRegistrationKind(value)

    public companion object {
        public val allKnownValues: List<AgentRegistrationKind> = listOf(Anonymous, ServiceAuth, IdentityAssertion)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): AgentRegistrationKind =
            when (rawValue) {
                "anonymous" -> Anonymous
                "service_auth" -> ServiceAuth
                "identity_assertion" -> IdentityAssertion
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<AgentRegistrationKind> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("AgentRegistrationKind", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): AgentRegistrationKind = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: AgentRegistrationKind,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
