// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid AgentRegistrationCreatedDataStatus values. */
@Serializable(with = AgentRegistrationCreatedDataStatus.Serializer::class)
public sealed class AgentRegistrationCreatedDataStatus(
    public val rawValue: String,
) {
    public data object Unverified : AgentRegistrationCreatedDataStatus("unverified")

    public data object Verified : AgentRegistrationCreatedDataStatus("verified")

    public data object Expired : AgentRegistrationCreatedDataStatus("expired")

    public data object Revoked : AgentRegistrationCreatedDataStatus("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : AgentRegistrationCreatedDataStatus(value)

    public companion object {
        public val allKnownValues: List<AgentRegistrationCreatedDataStatus> =
            listOf(
                Unverified,
                Verified,
                Expired,
                Revoked,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): AgentRegistrationCreatedDataStatus =
            when (rawValue) {
                "unverified" -> Unverified
                "verified" -> Verified
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<AgentRegistrationCreatedDataStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("AgentRegistrationCreatedDataStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): AgentRegistrationCreatedDataStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: AgentRegistrationCreatedDataStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
