// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid AuditLogExportState values. */
@Serializable(with = AuditLogExportState.Serializer::class)
public sealed class AuditLogExportState(
    public val rawValue: String,
) {
    public data object Pending : AuditLogExportState("pending")

    public data object Ready : AuditLogExportState("ready")

    public data object Error : AuditLogExportState("error")

    public data object Expired : AuditLogExportState("expired")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : AuditLogExportState(value)

    public companion object {
        public val allKnownValues: List<AuditLogExportState> = listOf(Pending, Ready, Error, Expired)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): AuditLogExportState =
            when (rawValue) {
                "pending" -> Pending
                "ready" -> Ready
                "error" -> Error
                "expired" -> Expired
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<AuditLogExportState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("AuditLogExportState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): AuditLogExportState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: AuditLogExportState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
