// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid AuditLogConfigurationLogStreamType values. */
@Serializable(with = AuditLogConfigurationLogStreamType.Serializer::class)
public sealed class AuditLogConfigurationLogStreamType(
    public val rawValue: String,
) {
    public data object AzureSentinel : AuditLogConfigurationLogStreamType("AzureSentinel")

    public data object Datadog : AuditLogConfigurationLogStreamType("Datadog")

    public data object GenericHttps : AuditLogConfigurationLogStreamType("GenericHttps")

    public data object GoogleCloudStorage : AuditLogConfigurationLogStreamType("GoogleCloudStorage")

    public data object S3 : AuditLogConfigurationLogStreamType("S3")

    public data object Snowflake : AuditLogConfigurationLogStreamType("Snowflake")

    public data object Splunk : AuditLogConfigurationLogStreamType("Splunk")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : AuditLogConfigurationLogStreamType(value)

    public companion object {
        public val allKnownValues: List<AuditLogConfigurationLogStreamType> =
            listOf(
                AzureSentinel,
                Datadog,
                GenericHttps,
                GoogleCloudStorage,
                S3,
                Snowflake,
                Splunk,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): AuditLogConfigurationLogStreamType =
            when (rawValue) {
                "AzureSentinel" -> AzureSentinel
                "Datadog" -> Datadog
                "GenericHttps" -> GenericHttps
                "GoogleCloudStorage" -> GoogleCloudStorage
                "S3" -> S3
                "Snowflake" -> Snowflake
                "Splunk" -> Splunk
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<AuditLogConfigurationLogStreamType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("AuditLogConfigurationLogStreamType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): AuditLogConfigurationLogStreamType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: AuditLogConfigurationLogStreamType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
