// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid AuthenticationFactorsCreateRequestType values. */
@Serializable(with = AuthenticationFactorsCreateRequestType.Serializer::class)
public sealed class AuthenticationFactorsCreateRequestType(
    public val rawValue: String,
) {
    public data object GenericOtp : AuthenticationFactorsCreateRequestType("generic_otp")

    public data object Sms : AuthenticationFactorsCreateRequestType("sms")

    public data object Totp : AuthenticationFactorsCreateRequestType("totp")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : AuthenticationFactorsCreateRequestType(value)

    public companion object {
        public val allKnownValues: List<AuthenticationFactorsCreateRequestType> = listOf(GenericOtp, Sms, Totp)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): AuthenticationFactorsCreateRequestType =
            when (rawValue) {
                "generic_otp" -> GenericOtp
                "sms" -> Sms
                "totp" -> Totp
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<AuthenticationFactorsCreateRequestType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("AuthenticationFactorsCreateRequestType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): AuthenticationFactorsCreateRequestType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: AuthenticationFactorsCreateRequestType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
