// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ClaimViewResponseStatus values. */
@Serializable(with = ClaimViewResponseStatus.Serializer::class)
public sealed class ClaimViewResponseStatus(
    public val rawValue: String,
) {
    public data object Unverified : ClaimViewResponseStatus("unverified")

    public data object Verified : ClaimViewResponseStatus("verified")

    public data object Expired : ClaimViewResponseStatus("expired")

    public data object Revoked : ClaimViewResponseStatus("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ClaimViewResponseStatus(value)

    public companion object {
        public val allKnownValues: List<ClaimViewResponseStatus> = listOf(Unverified, Verified, Expired, Revoked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ClaimViewResponseStatus =
            when (rawValue) {
                "unverified" -> Unverified
                "verified" -> Verified
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ClaimViewResponseStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ClaimViewResponseStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ClaimViewResponseStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ClaimViewResponseStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
