// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ConnectionActivatedDataConnectionType values. */
@Serializable(with = ConnectionActivatedDataConnectionType.Serializer::class)
public sealed class ConnectionActivatedDataConnectionType(
    public val rawValue: String,
) {
    public data object Adfssaml : ConnectionActivatedDataConnectionType("ADFSSAML")

    public data object AdpOidc : ConnectionActivatedDataConnectionType("AdpOidc")

    public data object AppleOAuth : ConnectionActivatedDataConnectionType("AppleOAuth")

    public data object Auth0Migration : ConnectionActivatedDataConnectionType("Auth0Migration")

    public data object Auth0SAML : ConnectionActivatedDataConnectionType("Auth0SAML")

    public data object AzureSAML : ConnectionActivatedDataConnectionType("AzureSAML")

    public data object BitbucketOAuth : ConnectionActivatedDataConnectionType("BitbucketOAuth")

    public data object CasSAML : ConnectionActivatedDataConnectionType("CasSAML")

    public data object ClassLinkSAML : ConnectionActivatedDataConnectionType("ClassLinkSAML")

    public data object CleverOidc : ConnectionActivatedDataConnectionType("CleverOIDC")

    public data object CloudflareSAML : ConnectionActivatedDataConnectionType("CloudflareSAML")

    public data object CyberArkSAML : ConnectionActivatedDataConnectionType("CyberArkSAML")

    public data object DiscordOAuth : ConnectionActivatedDataConnectionType("DiscordOAuth")

    public data object DuoSAML : ConnectionActivatedDataConnectionType("DuoSAML")

    public data object EntraIdOidc : ConnectionActivatedDataConnectionType("EntraIdOIDC")

    public data object GenericOidc : ConnectionActivatedDataConnectionType("GenericOIDC")

    public data object GenericSAML : ConnectionActivatedDataConnectionType("GenericSAML")

    public data object GitHubOAuth : ConnectionActivatedDataConnectionType("GitHubOAuth")

    public data object GitLabOAuth : ConnectionActivatedDataConnectionType("GitLabOAuth")

    public data object GoogleOAuth : ConnectionActivatedDataConnectionType("GoogleOAuth")

    public data object GoogleOidc : ConnectionActivatedDataConnectionType("GoogleOIDC")

    public data object GoogleSAML : ConnectionActivatedDataConnectionType("GoogleSAML")

    public data object IntuitOAuth : ConnectionActivatedDataConnectionType("IntuitOAuth")

    public data object JumpCloudSAML : ConnectionActivatedDataConnectionType("JumpCloudSAML")

    public data object KeycloakSAML : ConnectionActivatedDataConnectionType("KeycloakSAML")

    public data object LastPassSAML : ConnectionActivatedDataConnectionType("LastPassSAML")

    public data object LinkedInOAuth : ConnectionActivatedDataConnectionType("LinkedInOAuth")

    public data object LoginGovOidc : ConnectionActivatedDataConnectionType("LoginGovOidc")

    public data object MagicLink : ConnectionActivatedDataConnectionType("MagicLink")

    public data object MicrosoftOAuth : ConnectionActivatedDataConnectionType("MicrosoftOAuth")

    public data object MiniOrangeSAML : ConnectionActivatedDataConnectionType("MiniOrangeSAML")

    public data object NetIqSAML : ConnectionActivatedDataConnectionType("NetIqSAML")

    public data object OktaOidc : ConnectionActivatedDataConnectionType("OktaOIDC")

    public data object OktaSAML : ConnectionActivatedDataConnectionType("OktaSAML")

    public data object OneLoginSAML : ConnectionActivatedDataConnectionType("OneLoginSAML")

    public data object OracleSAML : ConnectionActivatedDataConnectionType("OracleSAML")

    public data object PingFederateSAML : ConnectionActivatedDataConnectionType("PingFederateSAML")

    public data object PingOneSAML : ConnectionActivatedDataConnectionType("PingOneSAML")

    public data object RipplingSAML : ConnectionActivatedDataConnectionType("RipplingSAML")

    public data object SalesforceSAML : ConnectionActivatedDataConnectionType("SalesforceSAML")

    public data object ShibbolethGenericSAML : ConnectionActivatedDataConnectionType("ShibbolethGenericSAML")

    public data object ShibbolethSAML : ConnectionActivatedDataConnectionType("ShibbolethSAML")

    public data object SimpleSAMLPhpSAML : ConnectionActivatedDataConnectionType("SimpleSamlPhpSAML")

    public data object SalesforceOAuth : ConnectionActivatedDataConnectionType("SalesforceOAuth")

    public data object SlackOAuth : ConnectionActivatedDataConnectionType("SlackOAuth")

    public data object TestIdp : ConnectionActivatedDataConnectionType("TestIdp")

    public data object VercelMarketplaceOAuth : ConnectionActivatedDataConnectionType("VercelMarketplaceOAuth")

    public data object VercelOAuth : ConnectionActivatedDataConnectionType("VercelOAuth")

    public data object VMwareSAML : ConnectionActivatedDataConnectionType("VMwareSAML")

    public data object XeroOAuth : ConnectionActivatedDataConnectionType("XeroOAuth")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ConnectionActivatedDataConnectionType(value)

    public companion object {
        public val allKnownValues: List<ConnectionActivatedDataConnectionType> =
            listOf(
                Adfssaml,
                AdpOidc,
                AppleOAuth,
                Auth0Migration,
                Auth0SAML,
                AzureSAML,
                BitbucketOAuth,
                CasSAML,
                ClassLinkSAML,
                CleverOidc,
                CloudflareSAML,
                CyberArkSAML,
                DiscordOAuth,
                DuoSAML,
                EntraIdOidc,
                GenericOidc,
                GenericSAML,
                GitHubOAuth,
                GitLabOAuth,
                GoogleOAuth,
                GoogleOidc,
                GoogleSAML,
                IntuitOAuth,
                JumpCloudSAML,
                KeycloakSAML,
                LastPassSAML,
                LinkedInOAuth,
                LoginGovOidc,
                MagicLink,
                MicrosoftOAuth,
                MiniOrangeSAML,
                NetIqSAML,
                OktaOidc,
                OktaSAML,
                OneLoginSAML,
                OracleSAML,
                PingFederateSAML,
                PingOneSAML,
                RipplingSAML,
                SalesforceSAML,
                ShibbolethGenericSAML,
                ShibbolethSAML,
                SimpleSAMLPhpSAML,
                SalesforceOAuth,
                SlackOAuth,
                TestIdp,
                VercelMarketplaceOAuth,
                VercelOAuth,
                VMwareSAML,
                XeroOAuth,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ConnectionActivatedDataConnectionType =
            when (rawValue) {
                "ADFSSAML" -> Adfssaml
                "AdpOidc" -> AdpOidc
                "AppleOAuth" -> AppleOAuth
                "Auth0Migration" -> Auth0Migration
                "Auth0SAML" -> Auth0SAML
                "AzureSAML" -> AzureSAML
                "BitbucketOAuth" -> BitbucketOAuth
                "CasSAML" -> CasSAML
                "ClassLinkSAML" -> ClassLinkSAML
                "CleverOIDC" -> CleverOidc
                "CloudflareSAML" -> CloudflareSAML
                "CyberArkSAML" -> CyberArkSAML
                "DiscordOAuth" -> DiscordOAuth
                "DuoSAML" -> DuoSAML
                "EntraIdOIDC" -> EntraIdOidc
                "GenericOIDC" -> GenericOidc
                "GenericSAML" -> GenericSAML
                "GitHubOAuth" -> GitHubOAuth
                "GitLabOAuth" -> GitLabOAuth
                "GoogleOAuth" -> GoogleOAuth
                "GoogleOIDC" -> GoogleOidc
                "GoogleSAML" -> GoogleSAML
                "IntuitOAuth" -> IntuitOAuth
                "JumpCloudSAML" -> JumpCloudSAML
                "KeycloakSAML" -> KeycloakSAML
                "LastPassSAML" -> LastPassSAML
                "LinkedInOAuth" -> LinkedInOAuth
                "LoginGovOidc" -> LoginGovOidc
                "MagicLink" -> MagicLink
                "MicrosoftOAuth" -> MicrosoftOAuth
                "MiniOrangeSAML" -> MiniOrangeSAML
                "NetIqSAML" -> NetIqSAML
                "OktaOIDC" -> OktaOidc
                "OktaSAML" -> OktaSAML
                "OneLoginSAML" -> OneLoginSAML
                "OracleSAML" -> OracleSAML
                "PingFederateSAML" -> PingFederateSAML
                "PingOneSAML" -> PingOneSAML
                "RipplingSAML" -> RipplingSAML
                "SalesforceSAML" -> SalesforceSAML
                "ShibbolethGenericSAML" -> ShibbolethGenericSAML
                "ShibbolethSAML" -> ShibbolethSAML
                "SimpleSamlPhpSAML" -> SimpleSAMLPhpSAML
                "SalesforceOAuth" -> SalesforceOAuth
                "SlackOAuth" -> SlackOAuth
                "TestIdp" -> TestIdp
                "VercelMarketplaceOAuth" -> VercelMarketplaceOAuth
                "VercelOAuth" -> VercelOAuth
                "VMwareSAML" -> VMwareSAML
                "XeroOAuth" -> XeroOAuth
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ConnectionActivatedDataConnectionType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ConnectionActivatedDataConnectionType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ConnectionActivatedDataConnectionType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ConnectionActivatedDataConnectionType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
