// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ConnectionsConnectionType values. */
@Serializable(with = ConnectionsConnectionType.Serializer::class)
public sealed class ConnectionsConnectionType(
    public val rawValue: String,
) {
    public data object Adfssaml : ConnectionsConnectionType("ADFSSAML")

    public data object AdpOidc : ConnectionsConnectionType("AdpOidc")

    public data object AppleOAuth : ConnectionsConnectionType("AppleOAuth")

    public data object Auth0SAML : ConnectionsConnectionType("Auth0SAML")

    public data object AzureSAML : ConnectionsConnectionType("AzureSAML")

    public data object BitbucketOAuth : ConnectionsConnectionType("BitbucketOAuth")

    public data object CasSAML : ConnectionsConnectionType("CasSAML")

    public data object CloudflareSAML : ConnectionsConnectionType("CloudflareSAML")

    public data object ClassLinkSAML : ConnectionsConnectionType("ClassLinkSAML")

    public data object CleverOidc : ConnectionsConnectionType("CleverOIDC")

    public data object CyberArkSAML : ConnectionsConnectionType("CyberArkSAML")

    public data object DiscordOAuth : ConnectionsConnectionType("DiscordOAuth")

    public data object DuoSAML : ConnectionsConnectionType("DuoSAML")

    public data object EntraIdOidc : ConnectionsConnectionType("EntraIdOIDC")

    public data object GenericOidc : ConnectionsConnectionType("GenericOIDC")

    public data object GenericSAML : ConnectionsConnectionType("GenericSAML")

    public data object GithubOAuth : ConnectionsConnectionType("GithubOAuth")

    public data object GitLabOAuth : ConnectionsConnectionType("GitLabOAuth")

    public data object GoogleOAuth : ConnectionsConnectionType("GoogleOAuth")

    public data object GoogleOidc : ConnectionsConnectionType("GoogleOIDC")

    public data object GoogleSAML : ConnectionsConnectionType("GoogleSAML")

    public data object IntuitOAuth : ConnectionsConnectionType("IntuitOAuth")

    public data object JumpCloudSAML : ConnectionsConnectionType("JumpCloudSAML")

    public data object KeycloakSAML : ConnectionsConnectionType("KeycloakSAML")

    public data object LastPassSAML : ConnectionsConnectionType("LastPassSAML")

    public data object LinkedInOAuth : ConnectionsConnectionType("LinkedInOAuth")

    public data object LoginGovOidc : ConnectionsConnectionType("LoginGovOidc")

    public data object MagicLink : ConnectionsConnectionType("MagicLink")

    public data object MicrosoftOAuth : ConnectionsConnectionType("MicrosoftOAuth")

    public data object MiniOrangeSAML : ConnectionsConnectionType("MiniOrangeSAML")

    public data object NetIqSAML : ConnectionsConnectionType("NetIqSAML")

    public data object OktaOidc : ConnectionsConnectionType("OktaOIDC")

    public data object OktaSAML : ConnectionsConnectionType("OktaSAML")

    public data object OneLoginSAML : ConnectionsConnectionType("OneLoginSAML")

    public data object OracleSAML : ConnectionsConnectionType("OracleSAML")

    public data object PingFederateSAML : ConnectionsConnectionType("PingFederateSAML")

    public data object PingOneSAML : ConnectionsConnectionType("PingOneSAML")

    public data object RipplingSAML : ConnectionsConnectionType("RipplingSAML")

    public data object SalesforceSAML : ConnectionsConnectionType("SalesforceSAML")

    public data object ShibbolethGenericSAML : ConnectionsConnectionType("ShibbolethGenericSAML")

    public data object ShibbolethSAML : ConnectionsConnectionType("ShibbolethSAML")

    public data object SimpleSAMLPhpSAML : ConnectionsConnectionType("SimpleSamlPhpSAML")

    public data object SalesforceOAuth : ConnectionsConnectionType("SalesforceOAuth")

    public data object SlackOAuth : ConnectionsConnectionType("SlackOAuth")

    public data object VercelMarketplaceOAuth : ConnectionsConnectionType("VercelMarketplaceOAuth")

    public data object VercelOAuth : ConnectionsConnectionType("VercelOAuth")

    public data object VMwareSAML : ConnectionsConnectionType("VMwareSAML")

    public data object XeroOAuth : ConnectionsConnectionType("XeroOAuth")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ConnectionsConnectionType(value)

    public companion object {
        public val allKnownValues: List<ConnectionsConnectionType> =
            listOf(
                Adfssaml,
                AdpOidc,
                AppleOAuth,
                Auth0SAML,
                AzureSAML,
                BitbucketOAuth,
                CasSAML,
                CloudflareSAML,
                ClassLinkSAML,
                CleverOidc,
                CyberArkSAML,
                DiscordOAuth,
                DuoSAML,
                EntraIdOidc,
                GenericOidc,
                GenericSAML,
                GithubOAuth,
                GitLabOAuth,
                GoogleOAuth,
                GoogleOidc,
                GoogleSAML,
                IntuitOAuth,
                JumpCloudSAML,
                KeycloakSAML,
                LastPassSAML,
                LinkedInOAuth,
                LoginGovOidc,
                MagicLink,
                MicrosoftOAuth,
                MiniOrangeSAML,
                NetIqSAML,
                OktaOidc,
                OktaSAML,
                OneLoginSAML,
                OracleSAML,
                PingFederateSAML,
                PingOneSAML,
                RipplingSAML,
                SalesforceSAML,
                ShibbolethGenericSAML,
                ShibbolethSAML,
                SimpleSAMLPhpSAML,
                SalesforceOAuth,
                SlackOAuth,
                VercelMarketplaceOAuth,
                VercelOAuth,
                VMwareSAML,
                XeroOAuth,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ConnectionsConnectionType =
            when (rawValue) {
                "ADFSSAML" -> Adfssaml
                "AdpOidc" -> AdpOidc
                "AppleOAuth" -> AppleOAuth
                "Auth0SAML" -> Auth0SAML
                "AzureSAML" -> AzureSAML
                "BitbucketOAuth" -> BitbucketOAuth
                "CasSAML" -> CasSAML
                "CloudflareSAML" -> CloudflareSAML
                "ClassLinkSAML" -> ClassLinkSAML
                "CleverOIDC" -> CleverOidc
                "CyberArkSAML" -> CyberArkSAML
                "DiscordOAuth" -> DiscordOAuth
                "DuoSAML" -> DuoSAML
                "EntraIdOIDC" -> EntraIdOidc
                "GenericOIDC" -> GenericOidc
                "GenericSAML" -> GenericSAML
                "GithubOAuth" -> GithubOAuth
                "GitLabOAuth" -> GitLabOAuth
                "GoogleOAuth" -> GoogleOAuth
                "GoogleOIDC" -> GoogleOidc
                "GoogleSAML" -> GoogleSAML
                "IntuitOAuth" -> IntuitOAuth
                "JumpCloudSAML" -> JumpCloudSAML
                "KeycloakSAML" -> KeycloakSAML
                "LastPassSAML" -> LastPassSAML
                "LinkedInOAuth" -> LinkedInOAuth
                "LoginGovOidc" -> LoginGovOidc
                "MagicLink" -> MagicLink
                "MicrosoftOAuth" -> MicrosoftOAuth
                "MiniOrangeSAML" -> MiniOrangeSAML
                "NetIqSAML" -> NetIqSAML
                "OktaOIDC" -> OktaOidc
                "OktaSAML" -> OktaSAML
                "OneLoginSAML" -> OneLoginSAML
                "OracleSAML" -> OracleSAML
                "PingFederateSAML" -> PingFederateSAML
                "PingOneSAML" -> PingOneSAML
                "RipplingSAML" -> RipplingSAML
                "SalesforceSAML" -> SalesforceSAML
                "ShibbolethGenericSAML" -> ShibbolethGenericSAML
                "ShibbolethSAML" -> ShibbolethSAML
                "SimpleSamlPhpSAML" -> SimpleSAMLPhpSAML
                "SalesforceOAuth" -> SalesforceOAuth
                "SlackOAuth" -> SlackOAuth
                "VercelMarketplaceOAuth" -> VercelMarketplaceOAuth
                "VercelOAuth" -> VercelOAuth
                "VMwareSAML" -> VMwareSAML
                "XeroOAuth" -> XeroOAuth
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ConnectionsConnectionType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ConnectionsConnectionType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ConnectionsConnectionType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ConnectionsConnectionType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
