// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ConnectionSAMLCertificateRenewedDataCertificateCertificateType values. */
@Serializable(with = ConnectionSAMLCertificateRenewedDataCertificateCertificateType.Serializer::class)
public sealed class ConnectionSAMLCertificateRenewedDataCertificateCertificateType(
    public val rawValue: String,
) {
    public data object ResponseSigning : ConnectionSAMLCertificateRenewedDataCertificateCertificateType("ResponseSigning")

    public data object RequestSigning : ConnectionSAMLCertificateRenewedDataCertificateCertificateType("RequestSigning")

    public data object ResponseEncryption : ConnectionSAMLCertificateRenewedDataCertificateCertificateType("ResponseEncryption")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ConnectionSAMLCertificateRenewedDataCertificateCertificateType(value)

    public companion object {
        public val allKnownValues: List<ConnectionSAMLCertificateRenewedDataCertificateCertificateType> =
            listOf(
                ResponseSigning,
                RequestSigning,
                ResponseEncryption,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ConnectionSAMLCertificateRenewedDataCertificateCertificateType =
            when (rawValue) {
                "ResponseSigning" -> ResponseSigning
                "RequestSigning" -> RequestSigning
                "ResponseEncryption" -> ResponseEncryption
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ConnectionSAMLCertificateRenewedDataCertificateCertificateType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ConnectionSAMLCertificateRenewedDataCertificateCertificateType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ConnectionSAMLCertificateRenewedDataCertificateCertificateType =
            fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ConnectionSAMLCertificateRenewedDataCertificateCertificateType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
