// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ConnectionActivatedDataStatus values. */
@Serializable(with = ConnectionActivatedDataStatus.Serializer::class)
public sealed class ConnectionActivatedDataStatus(
    public val rawValue: String,
) {
    public data object Linked : ConnectionActivatedDataStatus("linked")

    public data object Unlinked : ConnectionActivatedDataStatus("unlinked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ConnectionActivatedDataStatus(value)

    public companion object {
        public val allKnownValues: List<ConnectionActivatedDataStatus> = listOf(Linked, Unlinked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ConnectionActivatedDataStatus =
            when (rawValue) {
                "linked" -> Linked
                "unlinked" -> Unlinked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ConnectionActivatedDataStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ConnectionActivatedDataStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ConnectionActivatedDataStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ConnectionActivatedDataStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
