// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ConnectionDeactivatedDataConnectionType values. */
@Serializable(with = ConnectionDeactivatedDataConnectionType.Serializer::class)
public sealed class ConnectionDeactivatedDataConnectionType(
    public val rawValue: String,
) {
    public data object Adfssaml : ConnectionDeactivatedDataConnectionType("ADFSSAML")

    public data object AdpOidc : ConnectionDeactivatedDataConnectionType("AdpOidc")

    public data object AppleOAuth : ConnectionDeactivatedDataConnectionType("AppleOAuth")

    public data object Auth0Migration : ConnectionDeactivatedDataConnectionType("Auth0Migration")

    public data object Auth0SAML : ConnectionDeactivatedDataConnectionType("Auth0SAML")

    public data object AzureSAML : ConnectionDeactivatedDataConnectionType("AzureSAML")

    public data object BitbucketOAuth : ConnectionDeactivatedDataConnectionType("BitbucketOAuth")

    public data object CasSAML : ConnectionDeactivatedDataConnectionType("CasSAML")

    public data object ClassLinkSAML : ConnectionDeactivatedDataConnectionType("ClassLinkSAML")

    public data object CleverOidc : ConnectionDeactivatedDataConnectionType("CleverOIDC")

    public data object CloudflareSAML : ConnectionDeactivatedDataConnectionType("CloudflareSAML")

    public data object CyberArkSAML : ConnectionDeactivatedDataConnectionType("CyberArkSAML")

    public data object DiscordOAuth : ConnectionDeactivatedDataConnectionType("DiscordOAuth")

    public data object DuoSAML : ConnectionDeactivatedDataConnectionType("DuoSAML")

    public data object EntraIdOidc : ConnectionDeactivatedDataConnectionType("EntraIdOIDC")

    public data object GenericOidc : ConnectionDeactivatedDataConnectionType("GenericOIDC")

    public data object GenericSAML : ConnectionDeactivatedDataConnectionType("GenericSAML")

    public data object GitHubOAuth : ConnectionDeactivatedDataConnectionType("GitHubOAuth")

    public data object GitLabOAuth : ConnectionDeactivatedDataConnectionType("GitLabOAuth")

    public data object GoogleOAuth : ConnectionDeactivatedDataConnectionType("GoogleOAuth")

    public data object GoogleOidc : ConnectionDeactivatedDataConnectionType("GoogleOIDC")

    public data object GoogleSAML : ConnectionDeactivatedDataConnectionType("GoogleSAML")

    public data object IntuitOAuth : ConnectionDeactivatedDataConnectionType("IntuitOAuth")

    public data object JumpCloudSAML : ConnectionDeactivatedDataConnectionType("JumpCloudSAML")

    public data object KeycloakSAML : ConnectionDeactivatedDataConnectionType("KeycloakSAML")

    public data object LastPassSAML : ConnectionDeactivatedDataConnectionType("LastPassSAML")

    public data object LinkedInOAuth : ConnectionDeactivatedDataConnectionType("LinkedInOAuth")

    public data object LoginGovOidc : ConnectionDeactivatedDataConnectionType("LoginGovOidc")

    public data object MagicLink : ConnectionDeactivatedDataConnectionType("MagicLink")

    public data object MicrosoftOAuth : ConnectionDeactivatedDataConnectionType("MicrosoftOAuth")

    public data object MiniOrangeSAML : ConnectionDeactivatedDataConnectionType("MiniOrangeSAML")

    public data object NetIqSAML : ConnectionDeactivatedDataConnectionType("NetIqSAML")

    public data object OktaOidc : ConnectionDeactivatedDataConnectionType("OktaOIDC")

    public data object OktaSAML : ConnectionDeactivatedDataConnectionType("OktaSAML")

    public data object OneLoginSAML : ConnectionDeactivatedDataConnectionType("OneLoginSAML")

    public data object OracleSAML : ConnectionDeactivatedDataConnectionType("OracleSAML")

    public data object PingFederateSAML : ConnectionDeactivatedDataConnectionType("PingFederateSAML")

    public data object PingOneSAML : ConnectionDeactivatedDataConnectionType("PingOneSAML")

    public data object RipplingSAML : ConnectionDeactivatedDataConnectionType("RipplingSAML")

    public data object SalesforceSAML : ConnectionDeactivatedDataConnectionType("SalesforceSAML")

    public data object ShibbolethGenericSAML : ConnectionDeactivatedDataConnectionType("ShibbolethGenericSAML")

    public data object ShibbolethSAML : ConnectionDeactivatedDataConnectionType("ShibbolethSAML")

    public data object SimpleSAMLPhpSAML : ConnectionDeactivatedDataConnectionType("SimpleSamlPhpSAML")

    public data object SalesforceOAuth : ConnectionDeactivatedDataConnectionType("SalesforceOAuth")

    public data object SlackOAuth : ConnectionDeactivatedDataConnectionType("SlackOAuth")

    public data object TestIdp : ConnectionDeactivatedDataConnectionType("TestIdp")

    public data object VercelMarketplaceOAuth : ConnectionDeactivatedDataConnectionType("VercelMarketplaceOAuth")

    public data object VercelOAuth : ConnectionDeactivatedDataConnectionType("VercelOAuth")

    public data object VMwareSAML : ConnectionDeactivatedDataConnectionType("VMwareSAML")

    public data object XeroOAuth : ConnectionDeactivatedDataConnectionType("XeroOAuth")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ConnectionDeactivatedDataConnectionType(value)

    public companion object {
        public val allKnownValues: List<ConnectionDeactivatedDataConnectionType> =
            listOf(
                Adfssaml,
                AdpOidc,
                AppleOAuth,
                Auth0Migration,
                Auth0SAML,
                AzureSAML,
                BitbucketOAuth,
                CasSAML,
                ClassLinkSAML,
                CleverOidc,
                CloudflareSAML,
                CyberArkSAML,
                DiscordOAuth,
                DuoSAML,
                EntraIdOidc,
                GenericOidc,
                GenericSAML,
                GitHubOAuth,
                GitLabOAuth,
                GoogleOAuth,
                GoogleOidc,
                GoogleSAML,
                IntuitOAuth,
                JumpCloudSAML,
                KeycloakSAML,
                LastPassSAML,
                LinkedInOAuth,
                LoginGovOidc,
                MagicLink,
                MicrosoftOAuth,
                MiniOrangeSAML,
                NetIqSAML,
                OktaOidc,
                OktaSAML,
                OneLoginSAML,
                OracleSAML,
                PingFederateSAML,
                PingOneSAML,
                RipplingSAML,
                SalesforceSAML,
                ShibbolethGenericSAML,
                ShibbolethSAML,
                SimpleSAMLPhpSAML,
                SalesforceOAuth,
                SlackOAuth,
                TestIdp,
                VercelMarketplaceOAuth,
                VercelOAuth,
                VMwareSAML,
                XeroOAuth,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ConnectionDeactivatedDataConnectionType =
            when (rawValue) {
                "ADFSSAML" -> Adfssaml
                "AdpOidc" -> AdpOidc
                "AppleOAuth" -> AppleOAuth
                "Auth0Migration" -> Auth0Migration
                "Auth0SAML" -> Auth0SAML
                "AzureSAML" -> AzureSAML
                "BitbucketOAuth" -> BitbucketOAuth
                "CasSAML" -> CasSAML
                "ClassLinkSAML" -> ClassLinkSAML
                "CleverOIDC" -> CleverOidc
                "CloudflareSAML" -> CloudflareSAML
                "CyberArkSAML" -> CyberArkSAML
                "DiscordOAuth" -> DiscordOAuth
                "DuoSAML" -> DuoSAML
                "EntraIdOIDC" -> EntraIdOidc
                "GenericOIDC" -> GenericOidc
                "GenericSAML" -> GenericSAML
                "GitHubOAuth" -> GitHubOAuth
                "GitLabOAuth" -> GitLabOAuth
                "GoogleOAuth" -> GoogleOAuth
                "GoogleOIDC" -> GoogleOidc
                "GoogleSAML" -> GoogleSAML
                "IntuitOAuth" -> IntuitOAuth
                "JumpCloudSAML" -> JumpCloudSAML
                "KeycloakSAML" -> KeycloakSAML
                "LastPassSAML" -> LastPassSAML
                "LinkedInOAuth" -> LinkedInOAuth
                "LoginGovOidc" -> LoginGovOidc
                "MagicLink" -> MagicLink
                "MicrosoftOAuth" -> MicrosoftOAuth
                "MiniOrangeSAML" -> MiniOrangeSAML
                "NetIqSAML" -> NetIqSAML
                "OktaOIDC" -> OktaOidc
                "OktaSAML" -> OktaSAML
                "OneLoginSAML" -> OneLoginSAML
                "OracleSAML" -> OracleSAML
                "PingFederateSAML" -> PingFederateSAML
                "PingOneSAML" -> PingOneSAML
                "RipplingSAML" -> RipplingSAML
                "SalesforceSAML" -> SalesforceSAML
                "ShibbolethGenericSAML" -> ShibbolethGenericSAML
                "ShibbolethSAML" -> ShibbolethSAML
                "SimpleSamlPhpSAML" -> SimpleSAMLPhpSAML
                "SalesforceOAuth" -> SalesforceOAuth
                "SlackOAuth" -> SlackOAuth
                "TestIdp" -> TestIdp
                "VercelMarketplaceOAuth" -> VercelMarketplaceOAuth
                "VercelOAuth" -> VercelOAuth
                "VMwareSAML" -> VMwareSAML
                "XeroOAuth" -> XeroOAuth
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ConnectionDeactivatedDataConnectionType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ConnectionDeactivatedDataConnectionType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ConnectionDeactivatedDataConnectionType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ConnectionDeactivatedDataConnectionType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
