// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid CustomProviderDefinitionAuthenticateVia values. */
@Serializable(with = CustomProviderDefinitionAuthenticateVia.Serializer::class)
public sealed class CustomProviderDefinitionAuthenticateVia(
    public val rawValue: String,
) {
    public data object RequestBody : CustomProviderDefinitionAuthenticateVia("request_body")

    public data object BasicAuthHeader : CustomProviderDefinitionAuthenticateVia("basic_auth_header")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : CustomProviderDefinitionAuthenticateVia(value)

    public companion object {
        public val allKnownValues: List<CustomProviderDefinitionAuthenticateVia> = listOf(RequestBody, BasicAuthHeader)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): CustomProviderDefinitionAuthenticateVia =
            when (rawValue) {
                "request_body" -> RequestBody
                "basic_auth_header" -> BasicAuthHeader
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<CustomProviderDefinitionAuthenticateVia> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("CustomProviderDefinitionAuthenticateVia", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): CustomProviderDefinitionAuthenticateVia = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: CustomProviderDefinitionAuthenticateVia,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
