// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid DataIntegrationCredentialsResponseError values. */
@Serializable(with = DataIntegrationCredentialsResponseError.Serializer::class)
public sealed class DataIntegrationCredentialsResponseError(
    public val rawValue: String,
) {
    public data object NotInstalled : DataIntegrationCredentialsResponseError("not_installed")

    public data object NeedsReauthorization : DataIntegrationCredentialsResponseError("needs_reauthorization")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : DataIntegrationCredentialsResponseError(value)

    public companion object {
        public val allKnownValues: List<DataIntegrationCredentialsResponseError> =
            listOf(
                NotInstalled,
                NeedsReauthorization,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): DataIntegrationCredentialsResponseError =
            when (rawValue) {
                "not_installed" -> NotInstalled
                "needs_reauthorization" -> NeedsReauthorization
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<DataIntegrationCredentialsResponseError> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("DataIntegrationCredentialsResponseError", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): DataIntegrationCredentialsResponseError = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: DataIntegrationCredentialsResponseError,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
