// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid DataIntegrationCredentialsCredentialsType values. */
@Serializable(with = DataIntegrationCredentialsCredentialsType.Serializer::class)
public sealed class DataIntegrationCredentialsCredentialsType(
    public val rawValue: String,
) {
    public data object Shared : DataIntegrationCredentialsCredentialsType("shared")

    public data object Custom : DataIntegrationCredentialsCredentialsType("custom")

    public data object Organization : DataIntegrationCredentialsCredentialsType("organization")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : DataIntegrationCredentialsCredentialsType(value)

    public companion object {
        public val allKnownValues: List<DataIntegrationCredentialsCredentialsType> =
            listOf(
                Shared,
                Custom,
                Organization,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): DataIntegrationCredentialsCredentialsType =
            when (rawValue) {
                "shared" -> Shared
                "custom" -> Custom
                "organization" -> Organization
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<DataIntegrationCredentialsCredentialsType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("DataIntegrationCredentialsCredentialsType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): DataIntegrationCredentialsCredentialsType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: DataIntegrationCredentialsCredentialsType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
