// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid DataIntegrationsListResponseDataAuthMethods values. */
@Serializable(with = DataIntegrationsListResponseDataAuthMethods.Serializer::class)
public sealed class DataIntegrationsListResponseDataAuthMethods(
    public val rawValue: String,
) {
    public data object OAuth : DataIntegrationsListResponseDataAuthMethods("oauth")

    public data object ApiKey : DataIntegrationsListResponseDataAuthMethods("api_key")

    public data object ClientCredentials : DataIntegrationsListResponseDataAuthMethods("client_credentials")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : DataIntegrationsListResponseDataAuthMethods(value)

    public companion object {
        public val allKnownValues: List<DataIntegrationsListResponseDataAuthMethods> =
            listOf(
                OAuth,
                ApiKey,
                ClientCredentials,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): DataIntegrationsListResponseDataAuthMethods =
            when (rawValue) {
                "oauth" -> OAuth
                "api_key" -> ApiKey
                "client_credentials" -> ClientCredentials
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<DataIntegrationsListResponseDataAuthMethods> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("DataIntegrationsListResponseDataAuthMethods", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): DataIntegrationsListResponseDataAuthMethods = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: DataIntegrationsListResponseDataAuthMethods,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
