// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid DirectoryUserWithGroupsState values. */
@Serializable(with = DirectoryUserWithGroupsState.Serializer::class)
public sealed class DirectoryUserWithGroupsState(
    public val rawValue: String,
) {
    public data object Active : DirectoryUserWithGroupsState("active")

    public data object Suspended : DirectoryUserWithGroupsState("suspended")

    public data object Inactive : DirectoryUserWithGroupsState("inactive")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : DirectoryUserWithGroupsState(value)

    public companion object {
        public val allKnownValues: List<DirectoryUserWithGroupsState> = listOf(Active, Suspended, Inactive)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): DirectoryUserWithGroupsState =
            when (rawValue) {
                "active" -> Active
                "suspended" -> Suspended
                "inactive" -> Inactive
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<DirectoryUserWithGroupsState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("DirectoryUserWithGroupsState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): DirectoryUserWithGroupsState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: DirectoryUserWithGroupsState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
