// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid DirectoryState values. */
@Serializable(with = DirectoryState.Serializer::class)
public sealed class DirectoryState(
    public val rawValue: String,
) {
    public data object Linked : DirectoryState("linked")

    public data object Validating : DirectoryState("validating")

    public data object InvalidCredentials : DirectoryState("invalid_credentials")

    public data object Unlinked : DirectoryState("unlinked")

    public data object Deleting : DirectoryState("deleting")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : DirectoryState(value)

    public companion object {
        public val allKnownValues: List<DirectoryState> =
            listOf(
                Linked,
                Validating,
                InvalidCredentials,
                Unlinked,
                Deleting,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): DirectoryState =
            when (rawValue) {
                "linked" -> Linked
                "validating" -> Validating
                "invalid_credentials" -> InvalidCredentials
                "unlinked" -> Unlinked
                "deleting" -> Deleting
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<DirectoryState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("DirectoryState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): DirectoryState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: DirectoryState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
