// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid DsyncDeletedDataType values. */
@Serializable(with = DsyncDeletedDataType.Serializer::class)
public sealed class DsyncDeletedDataType(
    public val rawValue: String,
) {
    public data object AzureSCIMV20 : DsyncDeletedDataType("azure scim v2.0")

    public data object Bamboohr : DsyncDeletedDataType("bamboohr")

    public data object BreatheHr : DsyncDeletedDataType("breathe hr")

    public data object CezanneHr : DsyncDeletedDataType("cezanne hr")

    public data object CyberarkSCIMV20 : DsyncDeletedDataType("cyberark scim v2.0")

    public data object FourthHr : DsyncDeletedDataType("fourth hr")

    public data object GenericSCIMV20 : DsyncDeletedDataType("generic scim v2.0")

    public data object GsuiteDirectory : DsyncDeletedDataType("gsuite directory")

    public data object Gusto : DsyncDeletedDataType("gusto")

    public data object Hibob : DsyncDeletedDataType("hibob")

    public data object JumpCloudSCIMV20 : DsyncDeletedDataType("jump cloud scim v2.0")

    public data object OktaSCIMV20 : DsyncDeletedDataType("okta scim v2.0")

    public data object OneloginSCIMV20 : DsyncDeletedDataType("onelogin scim v2.0")

    public data object PeopleHr : DsyncDeletedDataType("people hr")

    public data object Personio : DsyncDeletedDataType("personio")

    public data object PingfederateSCIMV20 : DsyncDeletedDataType("pingfederate scim v2.0")

    public data object RipplingSCIMV20 : DsyncDeletedDataType("rippling scim v2.0")

    public data object Rippling : DsyncDeletedDataType("rippling")

    public data object SailpointSCIMV20 : DsyncDeletedDataType("sailpoint scim v2.0")

    public data object S3 : DsyncDeletedDataType("s3")

    public data object Sftp : DsyncDeletedDataType("sftp")

    public data object SftpWorkday : DsyncDeletedDataType("sftp workday")

    public data object Workday : DsyncDeletedDataType("workday")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : DsyncDeletedDataType(value)

    public companion object {
        public val allKnownValues: List<DsyncDeletedDataType> =
            listOf(
                AzureSCIMV20,
                Bamboohr,
                BreatheHr,
                CezanneHr,
                CyberarkSCIMV20,
                FourthHr,
                GenericSCIMV20,
                GsuiteDirectory,
                Gusto,
                Hibob,
                JumpCloudSCIMV20,
                OktaSCIMV20,
                OneloginSCIMV20,
                PeopleHr,
                Personio,
                PingfederateSCIMV20,
                RipplingSCIMV20,
                Rippling,
                SailpointSCIMV20,
                S3,
                Sftp,
                SftpWorkday,
                Workday,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): DsyncDeletedDataType =
            when (rawValue) {
                "azure scim v2.0" -> AzureSCIMV20
                "bamboohr" -> Bamboohr
                "breathe hr" -> BreatheHr
                "cezanne hr" -> CezanneHr
                "cyberark scim v2.0" -> CyberarkSCIMV20
                "fourth hr" -> FourthHr
                "generic scim v2.0" -> GenericSCIMV20
                "gsuite directory" -> GsuiteDirectory
                "gusto" -> Gusto
                "hibob" -> Hibob
                "jump cloud scim v2.0" -> JumpCloudSCIMV20
                "okta scim v2.0" -> OktaSCIMV20
                "onelogin scim v2.0" -> OneloginSCIMV20
                "people hr" -> PeopleHr
                "personio" -> Personio
                "pingfederate scim v2.0" -> PingfederateSCIMV20
                "rippling scim v2.0" -> RipplingSCIMV20
                "rippling" -> Rippling
                "sailpoint scim v2.0" -> SailpointSCIMV20
                "s3" -> S3
                "sftp" -> Sftp
                "sftp workday" -> SftpWorkday
                "workday" -> Workday
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<DsyncDeletedDataType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("DsyncDeletedDataType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): DsyncDeletedDataType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: DsyncDeletedDataType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
