// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid EventContextActorSource values. */
@Serializable(with = EventContextActorSource.Serializer::class)
public sealed class EventContextActorSource(
    public val rawValue: String,
) {
    public data object Api : EventContextActorSource("api")

    public data object Dashboard : EventContextActorSource("dashboard")

    public data object AdminPortal : EventContextActorSource("admin_portal")

    public data object System : EventContextActorSource("system")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : EventContextActorSource(value)

    public companion object {
        public val allKnownValues: List<EventContextActorSource> = listOf(Api, Dashboard, AdminPortal, System)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): EventContextActorSource =
            when (rawValue) {
                "api" -> Api
                "dashboard" -> Dashboard
                "admin_portal" -> AdminPortal
                "system" -> System
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<EventContextActorSource> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("EventContextActorSource", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): EventContextActorSource = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: EventContextActorSource,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
