// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid FlagRuleUpdatedContextActorSource values. */
@Serializable(with = FlagRuleUpdatedContextActorSource.Serializer::class)
public sealed class FlagRuleUpdatedContextActorSource(
    public val rawValue: String,
) {
    public data object Api : FlagRuleUpdatedContextActorSource("api")

    public data object Dashboard : FlagRuleUpdatedContextActorSource("dashboard")

    public data object AdminPortal : FlagRuleUpdatedContextActorSource("admin_portal")

    public data object System : FlagRuleUpdatedContextActorSource("system")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : FlagRuleUpdatedContextActorSource(value)

    public companion object {
        public val allKnownValues: List<FlagRuleUpdatedContextActorSource> = listOf(Api, Dashboard, AdminPortal, System)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): FlagRuleUpdatedContextActorSource =
            when (rawValue) {
                "api" -> Api
                "dashboard" -> Dashboard
                "admin_portal" -> AdminPortal
                "system" -> System
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<FlagRuleUpdatedContextActorSource> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("FlagRuleUpdatedContextActorSource", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): FlagRuleUpdatedContextActorSource = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: FlagRuleUpdatedContextActorSource,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
