// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid FlagUpdatedContextActorSource values. */
@Serializable(with = FlagUpdatedContextActorSource.Serializer::class)
public sealed class FlagUpdatedContextActorSource(
    public val rawValue: String,
) {
    public data object Api : FlagUpdatedContextActorSource("api")

    public data object Dashboard : FlagUpdatedContextActorSource("dashboard")

    public data object AdminPortal : FlagUpdatedContextActorSource("admin_portal")

    public data object System : FlagUpdatedContextActorSource("system")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : FlagUpdatedContextActorSource(value)

    public companion object {
        public val allKnownValues: List<FlagUpdatedContextActorSource> = listOf(Api, Dashboard, AdminPortal, System)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): FlagUpdatedContextActorSource =
            when (rawValue) {
                "api" -> Api
                "dashboard" -> Dashboard
                "admin_portal" -> AdminPortal
                "system" -> System
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<FlagUpdatedContextActorSource> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("FlagUpdatedContextActorSource", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): FlagUpdatedContextActorSource = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: FlagUpdatedContextActorSource,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
