// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid InvitationAcceptedDataState values. */
@Serializable(with = InvitationAcceptedDataState.Serializer::class)
public sealed class InvitationAcceptedDataState(
    public val rawValue: String,
) {
    public data object Pending : InvitationAcceptedDataState("pending")

    public data object Accepted : InvitationAcceptedDataState("accepted")

    public data object Expired : InvitationAcceptedDataState("expired")

    public data object Revoked : InvitationAcceptedDataState("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : InvitationAcceptedDataState(value)

    public companion object {
        public val allKnownValues: List<InvitationAcceptedDataState> = listOf(Pending, Accepted, Expired, Revoked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): InvitationAcceptedDataState =
            when (rawValue) {
                "pending" -> Pending
                "accepted" -> Accepted
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<InvitationAcceptedDataState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("InvitationAcceptedDataState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): InvitationAcceptedDataState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: InvitationAcceptedDataState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
