// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid InvitationResentDataState values. */
@Serializable(with = InvitationResentDataState.Serializer::class)
public sealed class InvitationResentDataState(
    public val rawValue: String,
) {
    public data object Pending : InvitationResentDataState("pending")

    public data object Accepted : InvitationResentDataState("accepted")

    public data object Expired : InvitationResentDataState("expired")

    public data object Revoked : InvitationResentDataState("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : InvitationResentDataState(value)

    public companion object {
        public val allKnownValues: List<InvitationResentDataState> = listOf(Pending, Accepted, Expired, Revoked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): InvitationResentDataState =
            when (rawValue) {
                "pending" -> Pending
                "accepted" -> Accepted
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<InvitationResentDataState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("InvitationResentDataState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): InvitationResentDataState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: InvitationResentDataState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
