// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid InvitationState values. */
@Serializable(with = InvitationState.Serializer::class)
public sealed class InvitationState(
    public val rawValue: String,
) {
    public data object Pending : InvitationState("pending")

    public data object Accepted : InvitationState("accepted")

    public data object Expired : InvitationState("expired")

    public data object Revoked : InvitationState("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : InvitationState(value)

    public companion object {
        public val allKnownValues: List<InvitationState> = listOf(Pending, Accepted, Expired, Revoked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): InvitationState =
            when (rawValue) {
                "pending" -> Pending
                "accepted" -> Accepted
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<InvitationState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("InvitationState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): InvitationState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: InvitationState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
