// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationDomainCreatedDataVerificationStrategy values. */
@Serializable(with = OrganizationDomainCreatedDataVerificationStrategy.Serializer::class)
public sealed class OrganizationDomainCreatedDataVerificationStrategy(
    public val rawValue: String,
) {
    public data object Dns : OrganizationDomainCreatedDataVerificationStrategy("dns")

    public data object Manual : OrganizationDomainCreatedDataVerificationStrategy("manual")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationDomainCreatedDataVerificationStrategy(value)

    public companion object {
        public val allKnownValues: List<OrganizationDomainCreatedDataVerificationStrategy> = listOf(Dns, Manual)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationDomainCreatedDataVerificationStrategy =
            when (rawValue) {
                "dns" -> Dns
                "manual" -> Manual
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationDomainCreatedDataVerificationStrategy> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationDomainCreatedDataVerificationStrategy", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationDomainCreatedDataVerificationStrategy = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationDomainCreatedDataVerificationStrategy,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
