// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationMembershipDeletedDataStatus values. */
@Serializable(with = OrganizationMembershipDeletedDataStatus.Serializer::class)
public sealed class OrganizationMembershipDeletedDataStatus(
    public val rawValue: String,
) {
    public data object Active : OrganizationMembershipDeletedDataStatus("active")

    public data object Inactive : OrganizationMembershipDeletedDataStatus("inactive")

    public data object Pending : OrganizationMembershipDeletedDataStatus("pending")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationMembershipDeletedDataStatus(value)

    public companion object {
        public val allKnownValues: List<OrganizationMembershipDeletedDataStatus> = listOf(Active, Inactive, Pending)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationMembershipDeletedDataStatus =
            when (rawValue) {
                "active" -> Active
                "inactive" -> Inactive
                "pending" -> Pending
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationMembershipDeletedDataStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationMembershipDeletedDataStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationMembershipDeletedDataStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationMembershipDeletedDataStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
