// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationCreatedDataDomainState values. */
@Serializable(with = OrganizationCreatedDataDomainState.Serializer::class)
public sealed class OrganizationCreatedDataDomainState(
    public val rawValue: String,
) {
    public data object Failed : OrganizationCreatedDataDomainState("failed")

    public data object LegacyVerified : OrganizationCreatedDataDomainState("legacy_verified")

    public data object Pending : OrganizationCreatedDataDomainState("pending")

    public data object Unverified : OrganizationCreatedDataDomainState("unverified")

    public data object Verified : OrganizationCreatedDataDomainState("verified")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationCreatedDataDomainState(value)

    public companion object {
        public val allKnownValues: List<OrganizationCreatedDataDomainState> =
            listOf(
                Failed,
                LegacyVerified,
                Pending,
                Unverified,
                Verified,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationCreatedDataDomainState =
            when (rawValue) {
                "failed" -> Failed
                "legacy_verified" -> LegacyVerified
                "pending" -> Pending
                "unverified" -> Unverified
                "verified" -> Verified
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationCreatedDataDomainState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationCreatedDataDomainState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationCreatedDataDomainState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationCreatedDataDomainState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
