// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationDomainVerifiedDataState values. */
@Serializable(with = OrganizationDomainVerifiedDataState.Serializer::class)
public sealed class OrganizationDomainVerifiedDataState(
    public val rawValue: String,
) {
    public data object Failed : OrganizationDomainVerifiedDataState("failed")

    public data object LegacyVerified : OrganizationDomainVerifiedDataState("legacy_verified")

    public data object Pending : OrganizationDomainVerifiedDataState("pending")

    public data object Unverified : OrganizationDomainVerifiedDataState("unverified")

    public data object Verified : OrganizationDomainVerifiedDataState("verified")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationDomainVerifiedDataState(value)

    public companion object {
        public val allKnownValues: List<OrganizationDomainVerifiedDataState> =
            listOf(
                Failed,
                LegacyVerified,
                Pending,
                Unverified,
                Verified,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationDomainVerifiedDataState =
            when (rawValue) {
                "failed" -> Failed
                "legacy_verified" -> LegacyVerified
                "pending" -> Pending
                "unverified" -> Unverified
                "verified" -> Verified
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationDomainVerifiedDataState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationDomainVerifiedDataState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationDomainVerifiedDataState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationDomainVerifiedDataState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
