// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationDomainUpdatedDataVerificationStrategy values. */
@Serializable(with = OrganizationDomainUpdatedDataVerificationStrategy.Serializer::class)
public sealed class OrganizationDomainUpdatedDataVerificationStrategy(
    public val rawValue: String,
) {
    public data object Dns : OrganizationDomainUpdatedDataVerificationStrategy("dns")

    public data object Manual : OrganizationDomainUpdatedDataVerificationStrategy("manual")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationDomainUpdatedDataVerificationStrategy(value)

    public companion object {
        public val allKnownValues: List<OrganizationDomainUpdatedDataVerificationStrategy> = listOf(Dns, Manual)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationDomainUpdatedDataVerificationStrategy =
            when (rawValue) {
                "dns" -> Dns
                "manual" -> Manual
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationDomainUpdatedDataVerificationStrategy> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationDomainUpdatedDataVerificationStrategy", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationDomainUpdatedDataVerificationStrategy = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationDomainUpdatedDataVerificationStrategy,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
