// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationMembershipUpdatedDataStatus values. */
@Serializable(with = OrganizationMembershipUpdatedDataStatus.Serializer::class)
public sealed class OrganizationMembershipUpdatedDataStatus(
    public val rawValue: String,
) {
    public data object Active : OrganizationMembershipUpdatedDataStatus("active")

    public data object Inactive : OrganizationMembershipUpdatedDataStatus("inactive")

    public data object Pending : OrganizationMembershipUpdatedDataStatus("pending")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationMembershipUpdatedDataStatus(value)

    public companion object {
        public val allKnownValues: List<OrganizationMembershipUpdatedDataStatus> = listOf(Active, Inactive, Pending)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationMembershipUpdatedDataStatus =
            when (rawValue) {
                "active" -> Active
                "inactive" -> Inactive
                "pending" -> Pending
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationMembershipUpdatedDataStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationMembershipUpdatedDataStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationMembershipUpdatedDataStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationMembershipUpdatedDataStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
