// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid OrganizationDomainCreatedDataState values. */
@Serializable(with = OrganizationDomainCreatedDataState.Serializer::class)
public sealed class OrganizationDomainCreatedDataState(
    public val rawValue: String,
) {
    public data object Failed : OrganizationDomainCreatedDataState("failed")

    public data object LegacyVerified : OrganizationDomainCreatedDataState("legacy_verified")

    public data object Pending : OrganizationDomainCreatedDataState("pending")

    public data object Unverified : OrganizationDomainCreatedDataState("unverified")

    public data object Verified : OrganizationDomainCreatedDataState("verified")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : OrganizationDomainCreatedDataState(value)

    public companion object {
        public val allKnownValues: List<OrganizationDomainCreatedDataState> =
            listOf(
                Failed,
                LegacyVerified,
                Pending,
                Unverified,
                Verified,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): OrganizationDomainCreatedDataState =
            when (rawValue) {
                "failed" -> Failed
                "legacy_verified" -> LegacyVerified
                "pending" -> Pending
                "unverified" -> Unverified
                "verified" -> Verified
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<OrganizationDomainCreatedDataState> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("OrganizationDomainCreatedDataState", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): OrganizationDomainCreatedDataState = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: OrganizationDomainCreatedDataState,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
