// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid RadarStandaloneResponseVerdict values. */
@Serializable(with = RadarStandaloneResponseVerdict.Serializer::class)
public sealed class RadarStandaloneResponseVerdict(
    public val rawValue: String,
) {
    public data object Allow : RadarStandaloneResponseVerdict("allow")

    public data object Block : RadarStandaloneResponseVerdict("block")

    public data object Challenge : RadarStandaloneResponseVerdict("challenge")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : RadarStandaloneResponseVerdict(value)

    public companion object {
        public val allKnownValues: List<RadarStandaloneResponseVerdict> = listOf(Allow, Block, Challenge)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): RadarStandaloneResponseVerdict =
            when (rawValue) {
                "allow" -> Allow
                "block" -> Block
                "challenge" -> Challenge
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<RadarStandaloneResponseVerdict> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("RadarStandaloneResponseVerdict", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): RadarStandaloneResponseVerdict = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: RadarStandaloneResponseVerdict,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
