// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid RadarListType values. */
@Serializable(with = RadarListType.Serializer::class)
public sealed class RadarListType(
    public val rawValue: String,
) {
    public data object IpAddress : RadarListType("ip_address")

    public data object Domain : RadarListType("domain")

    public data object Email : RadarListType("email")

    public data object Device : RadarListType("device")

    public data object UserAgent : RadarListType("user_agent")

    public data object DeviceFingerprint : RadarListType("device_fingerprint")

    public data object Country : RadarListType("country")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : RadarListType(value)

    public companion object {
        public val allKnownValues: List<RadarListType> =
            listOf(
                IpAddress,
                Domain,
                Email,
                Device,
                UserAgent,
                DeviceFingerprint,
                Country,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): RadarListType =
            when (rawValue) {
                "ip_address" -> IpAddress
                "domain" -> Domain
                "email" -> Email
                "device" -> Device
                "user_agent" -> UserAgent
                "device_fingerprint" -> DeviceFingerprint
                "country" -> Country
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<RadarListType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("RadarListType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): RadarListType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: RadarListType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
