// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid ResendUserInviteOptionsLocale values. */
@Serializable(with = ResendUserInviteOptionsLocale.Serializer::class)
public sealed class ResendUserInviteOptionsLocale(
    public val rawValue: String,
) {
    public data object Af : ResendUserInviteOptionsLocale("af")

    public data object Am : ResendUserInviteOptionsLocale("am")

    public data object Ar : ResendUserInviteOptionsLocale("ar")

    public data object Bg : ResendUserInviteOptionsLocale("bg")

    public data object Bn : ResendUserInviteOptionsLocale("bn")

    public data object Bs : ResendUserInviteOptionsLocale("bs")

    public data object Ca : ResendUserInviteOptionsLocale("ca")

    public data object Cs : ResendUserInviteOptionsLocale("cs")

    public data object Da : ResendUserInviteOptionsLocale("da")

    public data object De : ResendUserInviteOptionsLocale("de")

    public data object DeDe : ResendUserInviteOptionsLocale("de-DE")

    public data object El : ResendUserInviteOptionsLocale("el")

    public data object En : ResendUserInviteOptionsLocale("en")

    public data object EnAu : ResendUserInviteOptionsLocale("en-AU")

    public data object EnCa : ResendUserInviteOptionsLocale("en-CA")

    public data object EnGb : ResendUserInviteOptionsLocale("en-GB")

    public data object EnUs : ResendUserInviteOptionsLocale("en-US")

    public data object Es : ResendUserInviteOptionsLocale("es")

    public data object Es419 : ResendUserInviteOptionsLocale("es-419")

    public data object EsEs : ResendUserInviteOptionsLocale("es-ES")

    public data object EsUs : ResendUserInviteOptionsLocale("es-US")

    public data object Et : ResendUserInviteOptionsLocale("et")

    public data object Fa : ResendUserInviteOptionsLocale("fa")

    public data object Fi : ResendUserInviteOptionsLocale("fi")

    public data object Fil : ResendUserInviteOptionsLocale("fil")

    public data object Fr : ResendUserInviteOptionsLocale("fr")

    public data object FrBe : ResendUserInviteOptionsLocale("fr-BE")

    public data object FrCa : ResendUserInviteOptionsLocale("fr-CA")

    public data object FrFr : ResendUserInviteOptionsLocale("fr-FR")

    public data object Fy : ResendUserInviteOptionsLocale("fy")

    public data object Gl : ResendUserInviteOptionsLocale("gl")

    public data object Gu : ResendUserInviteOptionsLocale("gu")

    public data object Ha : ResendUserInviteOptionsLocale("ha")

    public data object He : ResendUserInviteOptionsLocale("he")

    public data object Hi : ResendUserInviteOptionsLocale("hi")

    public data object Hr : ResendUserInviteOptionsLocale("hr")

    public data object Hu : ResendUserInviteOptionsLocale("hu")

    public data object Hy : ResendUserInviteOptionsLocale("hy")

    public data object Id : ResendUserInviteOptionsLocale("id")

    public data object Is : ResendUserInviteOptionsLocale("is")

    public data object It : ResendUserInviteOptionsLocale("it")

    public data object ItIt : ResendUserInviteOptionsLocale("it-IT")

    public data object Ja : ResendUserInviteOptionsLocale("ja")

    public data object Jv : ResendUserInviteOptionsLocale("jv")

    public data object Ka : ResendUserInviteOptionsLocale("ka")

    public data object Kk : ResendUserInviteOptionsLocale("kk")

    public data object Km : ResendUserInviteOptionsLocale("km")

    public data object Kn : ResendUserInviteOptionsLocale("kn")

    public data object Ko : ResendUserInviteOptionsLocale("ko")

    public data object Lt : ResendUserInviteOptionsLocale("lt")

    public data object Lv : ResendUserInviteOptionsLocale("lv")

    public data object Mk : ResendUserInviteOptionsLocale("mk")

    public data object Ml : ResendUserInviteOptionsLocale("ml")

    public data object Mn : ResendUserInviteOptionsLocale("mn")

    public data object Mr : ResendUserInviteOptionsLocale("mr")

    public data object Ms : ResendUserInviteOptionsLocale("ms")

    public data object My : ResendUserInviteOptionsLocale("my")

    public data object Nb : ResendUserInviteOptionsLocale("nb")

    public data object Ne : ResendUserInviteOptionsLocale("ne")

    public data object Nl : ResendUserInviteOptionsLocale("nl")

    public data object NlBe : ResendUserInviteOptionsLocale("nl-BE")

    public data object NlNl : ResendUserInviteOptionsLocale("nl-NL")

    public data object Nn : ResendUserInviteOptionsLocale("nn")

    public data object No : ResendUserInviteOptionsLocale("no")

    public data object Pa : ResendUserInviteOptionsLocale("pa")

    public data object Pl : ResendUserInviteOptionsLocale("pl")

    public data object Pt : ResendUserInviteOptionsLocale("pt")

    public data object PtBr : ResendUserInviteOptionsLocale("pt-BR")

    public data object PtPt : ResendUserInviteOptionsLocale("pt-PT")

    public data object Ro : ResendUserInviteOptionsLocale("ro")

    public data object Ru : ResendUserInviteOptionsLocale("ru")

    public data object Sk : ResendUserInviteOptionsLocale("sk")

    public data object Sl : ResendUserInviteOptionsLocale("sl")

    public data object Sq : ResendUserInviteOptionsLocale("sq")

    public data object Sr : ResendUserInviteOptionsLocale("sr")

    public data object Sv : ResendUserInviteOptionsLocale("sv")

    public data object Sw : ResendUserInviteOptionsLocale("sw")

    public data object Ta : ResendUserInviteOptionsLocale("ta")

    public data object Te : ResendUserInviteOptionsLocale("te")

    public data object Th : ResendUserInviteOptionsLocale("th")

    public data object Tr : ResendUserInviteOptionsLocale("tr")

    public data object Uk : ResendUserInviteOptionsLocale("uk")

    public data object Ur : ResendUserInviteOptionsLocale("ur")

    public data object Uz : ResendUserInviteOptionsLocale("uz")

    public data object Vi : ResendUserInviteOptionsLocale("vi")

    public data object Zh : ResendUserInviteOptionsLocale("zh")

    public data object ZhCn : ResendUserInviteOptionsLocale("zh-CN")

    public data object ZhHk : ResendUserInviteOptionsLocale("zh-HK")

    public data object ZhTw : ResendUserInviteOptionsLocale("zh-TW")

    public data object Zu : ResendUserInviteOptionsLocale("zu")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : ResendUserInviteOptionsLocale(value)

    public companion object {
        public val allKnownValues: List<ResendUserInviteOptionsLocale> =
            listOf(
                Af,
                Am,
                Ar,
                Bg,
                Bn,
                Bs,
                Ca,
                Cs,
                Da,
                De,
                DeDe,
                El,
                En,
                EnAu,
                EnCa,
                EnGb,
                EnUs,
                Es,
                Es419,
                EsEs,
                EsUs,
                Et,
                Fa,
                Fi,
                Fil,
                Fr,
                FrBe,
                FrCa,
                FrFr,
                Fy,
                Gl,
                Gu,
                Ha,
                He,
                Hi,
                Hr,
                Hu,
                Hy,
                Id,
                Is,
                It,
                ItIt,
                Ja,
                Jv,
                Ka,
                Kk,
                Km,
                Kn,
                Ko,
                Lt,
                Lv,
                Mk,
                Ml,
                Mn,
                Mr,
                Ms,
                My,
                Nb,
                Ne,
                Nl,
                NlBe,
                NlNl,
                Nn,
                No,
                Pa,
                Pl,
                Pt,
                PtBr,
                PtPt,
                Ro,
                Ru,
                Sk,
                Sl,
                Sq,
                Sr,
                Sv,
                Sw,
                Ta,
                Te,
                Th,
                Tr,
                Uk,
                Ur,
                Uz,
                Vi,
                Zh,
                ZhCn,
                ZhHk,
                ZhTw,
                Zu,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): ResendUserInviteOptionsLocale =
            when (rawValue) {
                "af" -> Af
                "am" -> Am
                "ar" -> Ar
                "bg" -> Bg
                "bn" -> Bn
                "bs" -> Bs
                "ca" -> Ca
                "cs" -> Cs
                "da" -> Da
                "de" -> De
                "de-DE" -> DeDe
                "el" -> El
                "en" -> En
                "en-AU" -> EnAu
                "en-CA" -> EnCa
                "en-GB" -> EnGb
                "en-US" -> EnUs
                "es" -> Es
                "es-419" -> Es419
                "es-ES" -> EsEs
                "es-US" -> EsUs
                "et" -> Et
                "fa" -> Fa
                "fi" -> Fi
                "fil" -> Fil
                "fr" -> Fr
                "fr-BE" -> FrBe
                "fr-CA" -> FrCa
                "fr-FR" -> FrFr
                "fy" -> Fy
                "gl" -> Gl
                "gu" -> Gu
                "ha" -> Ha
                "he" -> He
                "hi" -> Hi
                "hr" -> Hr
                "hu" -> Hu
                "hy" -> Hy
                "id" -> Id
                "is" -> Is
                "it" -> It
                "it-IT" -> ItIt
                "ja" -> Ja
                "jv" -> Jv
                "ka" -> Ka
                "kk" -> Kk
                "km" -> Km
                "kn" -> Kn
                "ko" -> Ko
                "lt" -> Lt
                "lv" -> Lv
                "mk" -> Mk
                "ml" -> Ml
                "mn" -> Mn
                "mr" -> Mr
                "ms" -> Ms
                "my" -> My
                "nb" -> Nb
                "ne" -> Ne
                "nl" -> Nl
                "nl-BE" -> NlBe
                "nl-NL" -> NlNl
                "nn" -> Nn
                "no" -> No
                "pa" -> Pa
                "pl" -> Pl
                "pt" -> Pt
                "pt-BR" -> PtBr
                "pt-PT" -> PtPt
                "ro" -> Ro
                "ru" -> Ru
                "sk" -> Sk
                "sl" -> Sl
                "sq" -> Sq
                "sr" -> Sr
                "sv" -> Sv
                "sw" -> Sw
                "ta" -> Ta
                "te" -> Te
                "th" -> Th
                "tr" -> Tr
                "uk" -> Uk
                "ur" -> Ur
                "uz" -> Uz
                "vi" -> Vi
                "zh" -> Zh
                "zh-CN" -> ZhCn
                "zh-HK" -> ZhHk
                "zh-TW" -> ZhTw
                "zu" -> Zu
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<ResendUserInviteOptionsLocale> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("ResendUserInviteOptionsLocale", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): ResendUserInviteOptionsLocale = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: ResendUserInviteOptionsLocale,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
