// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid SessionCreatedDataStatus values. */
@Serializable(with = SessionCreatedDataStatus.Serializer::class)
public sealed class SessionCreatedDataStatus(
    public val rawValue: String,
) {
    public data object Active : SessionCreatedDataStatus("active")

    public data object Expired : SessionCreatedDataStatus("expired")

    public data object Revoked : SessionCreatedDataStatus("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : SessionCreatedDataStatus(value)

    public companion object {
        public val allKnownValues: List<SessionCreatedDataStatus> = listOf(Active, Expired, Revoked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): SessionCreatedDataStatus =
            when (rawValue) {
                "active" -> Active
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<SessionCreatedDataStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("SessionCreatedDataStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): SessionCreatedDataStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: SessionCreatedDataStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
