// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid SSOProvider values. */
@Serializable(with = SSOProvider.Serializer::class)
public sealed class SSOProvider(
    public val rawValue: String,
) {
    public data object AppleOAuth : SSOProvider("AppleOAuth")

    public data object BitbucketOAuth : SSOProvider("BitbucketOAuth")

    public data object GitHubOAuth : SSOProvider("GitHubOAuth")

    public data object GitLabOAuth : SSOProvider("GitLabOAuth")

    public data object GoogleOAuth : SSOProvider("GoogleOAuth")

    public data object IntuitOAuth : SSOProvider("IntuitOAuth")

    public data object LinkedInOAuth : SSOProvider("LinkedInOAuth")

    public data object MicrosoftOAuth : SSOProvider("MicrosoftOAuth")

    public data object SalesforceOAuth : SSOProvider("SalesforceOAuth")

    public data object SlackOAuth : SSOProvider("SlackOAuth")

    public data object VercelMarketplaceOAuth : SSOProvider("VercelMarketplaceOAuth")

    public data object VercelOAuth : SSOProvider("VercelOAuth")

    public data object XeroOAuth : SSOProvider("XeroOAuth")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : SSOProvider(value)

    public companion object {
        public val allKnownValues: List<SSOProvider> =
            listOf(
                AppleOAuth,
                BitbucketOAuth,
                GitHubOAuth,
                GitLabOAuth,
                GoogleOAuth,
                IntuitOAuth,
                LinkedInOAuth,
                MicrosoftOAuth,
                SalesforceOAuth,
                SlackOAuth,
                VercelMarketplaceOAuth,
                VercelOAuth,
                XeroOAuth,
            )

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): SSOProvider =
            when (rawValue) {
                "AppleOAuth" -> AppleOAuth
                "BitbucketOAuth" -> BitbucketOAuth
                "GitHubOAuth" -> GitHubOAuth
                "GitLabOAuth" -> GitLabOAuth
                "GoogleOAuth" -> GoogleOAuth
                "IntuitOAuth" -> IntuitOAuth
                "LinkedInOAuth" -> LinkedInOAuth
                "MicrosoftOAuth" -> MicrosoftOAuth
                "SalesforceOAuth" -> SalesforceOAuth
                "SlackOAuth" -> SlackOAuth
                "VercelMarketplaceOAuth" -> VercelMarketplaceOAuth
                "VercelOAuth" -> VercelOAuth
                "XeroOAuth" -> XeroOAuth
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<SSOProvider> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("SSOProvider", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): SSOProvider = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: SSOProvider,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
