// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid UserRoleAssignmentSourceType values. */
@Serializable(with = UserRoleAssignmentSourceType.Serializer::class)
public sealed class UserRoleAssignmentSourceType(
    public val rawValue: String,
) {
    public data object Direct : UserRoleAssignmentSourceType("direct")

    public data object Group : UserRoleAssignmentSourceType("group")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : UserRoleAssignmentSourceType(value)

    public companion object {
        public val allKnownValues: List<UserRoleAssignmentSourceType> = listOf(Direct, Group)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): UserRoleAssignmentSourceType =
            when (rawValue) {
                "direct" -> Direct
                "group" -> Group
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<UserRoleAssignmentSourceType> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("UserRoleAssignmentSourceType", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): UserRoleAssignmentSourceType = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: UserRoleAssignmentSourceType,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
