// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid UserOrganizationMembershipStatus values. */
@Serializable(with = UserOrganizationMembershipStatus.Serializer::class)
public sealed class UserOrganizationMembershipStatus(
    public val rawValue: String,
) {
    public data object Active : UserOrganizationMembershipStatus("active")

    public data object Inactive : UserOrganizationMembershipStatus("inactive")

    public data object Pending : UserOrganizationMembershipStatus("pending")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : UserOrganizationMembershipStatus(value)

    public companion object {
        public val allKnownValues: List<UserOrganizationMembershipStatus> = listOf(Active, Inactive, Pending)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): UserOrganizationMembershipStatus =
            when (rawValue) {
                "active" -> Active
                "inactive" -> Inactive
                "pending" -> Pending
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<UserOrganizationMembershipStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("UserOrganizationMembershipStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): UserOrganizationMembershipStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: UserOrganizationMembershipStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
