// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid UserSessionsStatus values. */
@Serializable(with = UserSessionsStatus.Serializer::class)
public sealed class UserSessionsStatus(
    public val rawValue: String,
) {
    public data object Active : UserSessionsStatus("active")

    public data object Expired : UserSessionsStatus("expired")

    public data object Revoked : UserSessionsStatus("revoked")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : UserSessionsStatus(value)

    public companion object {
        public val allKnownValues: List<UserSessionsStatus> = listOf(Active, Expired, Revoked)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): UserSessionsStatus =
            when (rawValue) {
                "active" -> Active
                "expired" -> Expired
                "revoked" -> Revoked
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<UserSessionsStatus> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("UserSessionsStatus", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): UserSessionsStatus = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: UserSessionsStatus,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
