// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid VaultMetadataReadDataActorSource values. */
@Serializable(with = VaultMetadataReadDataActorSource.Serializer::class)
public sealed class VaultMetadataReadDataActorSource(
    public val rawValue: String,
) {
    public data object Api : VaultMetadataReadDataActorSource("api")

    public data object Dashboard : VaultMetadataReadDataActorSource("dashboard")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : VaultMetadataReadDataActorSource(value)

    public companion object {
        public val allKnownValues: List<VaultMetadataReadDataActorSource> = listOf(Api, Dashboard)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): VaultMetadataReadDataActorSource =
            when (rawValue) {
                "api" -> Api
                "dashboard" -> Dashboard
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<VaultMetadataReadDataActorSource> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("VaultMetadataReadDataActorSource", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): VaultMetadataReadDataActorSource = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: VaultMetadataReadDataActorSource,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
