// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid VaultDataCreatedDataActorSource values. */
@Serializable(with = VaultDataCreatedDataActorSource.Serializer::class)
public sealed class VaultDataCreatedDataActorSource(
    public val rawValue: String,
) {
    public data object Api : VaultDataCreatedDataActorSource("api")

    public data object Dashboard : VaultDataCreatedDataActorSource("dashboard")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : VaultDataCreatedDataActorSource(value)

    public companion object {
        public val allKnownValues: List<VaultDataCreatedDataActorSource> = listOf(Api, Dashboard)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): VaultDataCreatedDataActorSource =
            when (rawValue) {
                "api" -> Api
                "dashboard" -> Dashboard
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<VaultDataCreatedDataActorSource> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("VaultDataCreatedDataActorSource", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): VaultDataCreatedDataActorSource = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: VaultDataCreatedDataActorSource,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
