// This file is auto-generated by oagen. Do not edit.

package com.workos.android.enums

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder

/** Enumeration of valid VaultDekDecryptedDataActorSource values. */
@Serializable(with = VaultDekDecryptedDataActorSource.Serializer::class)
public sealed class VaultDekDecryptedDataActorSource(
    public val rawValue: String,
) {
    public data object Api : VaultDekDecryptedDataActorSource("api")

    public data object Dashboard : VaultDekDecryptedDataActorSource("dashboard")

    /** A value not known at SDK generation time. */
    public data class Unknown(
        public val value: String,
    ) : VaultDekDecryptedDataActorSource(value)

    public companion object {
        public val allKnownValues: List<VaultDekDecryptedDataActorSource> = listOf(Api, Dashboard)

        /** Parse a wire value, mapping anything unrecognized to [Unknown]. */
        public fun fromRawValue(rawValue: String): VaultDekDecryptedDataActorSource =
            when (rawValue) {
                "api" -> Api
                "dashboard" -> Dashboard
                else -> Unknown(rawValue)
            }
    }

    internal object Serializer : KSerializer<VaultDekDecryptedDataActorSource> {
        override val descriptor: SerialDescriptor =
            PrimitiveSerialDescriptor("VaultDekDecryptedDataActorSource", PrimitiveKind.STRING)

        override fun deserialize(decoder: Decoder): VaultDekDecryptedDataActorSource = fromRawValue(decoder.decodeString())

        override fun serialize(
            encoder: Encoder,
            value: VaultDekDecryptedDataActorSource,
        ) {
            encoder.encodeString(value.rawValue)
        }
    }
}
