// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.enums.AgentAdminValidateCredentialRequestType
import com.workos.android.models.AgentAdminLinkClaimAttemptToExternalUserRequestUser
import com.workos.android.support.bodyJson
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Wire-level tests for the Agents resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class AgentsTest {
    @Test
    fun `update attempts sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"id\":\"agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"status\":\"unverified\",\"user_code\":\"BCDF-GHJK\",\"organizations\":[{\"id\":\"org_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"name\":\"Acme Corp\"}]}")
            val result = client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))

            val request = server.takeRequest()
            assertEquals("PATCH", request.method)
            assertEquals("/agents/claims/attempts", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("type"))
            assertEquals("agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY", result.id)
        }

    @Test
    fun `create validate sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"valid\":true,\"registration_id\":\"agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"expires_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.agents.createValidate(type = AgentAdminValidateCredentialRequestType.fromRawValue("api_key"), credential = "test_credential")

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/agents/credentials/validate", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("type"))
            assertNotNull(result)
        }

    @Test
    fun `get registration sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"id\":\"agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"agent_identity\":{\"id\":\"agent_identity_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"userland_user_id\":\"user_01E4ZCR3C56J083X43JQXF3JK5\",\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"},\"organization_id\":\"org_01EHQMYV6MBK39QC5PZXHY59C3\",\"status\":\"verified\",\"kind\":\"service_auth\",\"claim\":{\"id\":\"agent_reg_claim_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"claim_completion\":{\"id\":\"agent_reg_claim_attempt_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\",\"expires_at\":\"2026-01-15T12:00:00.000Z\",\"claimed_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\",\"expires_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.agents.getRegistration(id = "sample-id")

            val request = server.takeRequest()
            assertEquals("GET", request.method)
            assertEquals("/agents/registrations/sample-id", request.pathOnly())
            assertEquals("agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY", result.id)
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{\"id\":\"agent_reg_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"status\":\"unverified\",\"user_code\":\"BCDF-GHJK\",\"organizations\":[{\"id\":\"org_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"name\":\"Acme Corp\"}]}")

            client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"), requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.takeRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `update attempts throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `update attempts throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `update attempts throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `update attempts throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `update attempts throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `update attempts throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.agents.updateAttempts(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))
                }

            assertEquals(500, error.statusCode)
        }
}
