// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.support.bodyJson
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.queryParam
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Wire-level tests for the ApiKeys resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class ApiKeysTest {
    @Test
    fun `delete sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{}")
            client.apiKeys.delete(id = "sample-id")

            val request = server.takeRequest()
            assertEquals("DELETE", request.method)
            assertEquals("/api_keys/sample-id", request.pathOnly())
        }

    @Test
    fun `create expire sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"api_key\",\"id\":\"api_key_01EHZNVPK3SFK441A1RGBFSHRT\",\"owner\":{\"type\":\"organization\",\"id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\"},\"name\":\"Production API Key\",\"obfuscated_value\":\"sk_...3456\",\"last_used_at\":null,\"expires_at\":null,\"permissions\":[\"posts:read\",\"posts:write\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.apiKeys.createExpire(id = "sample-id")

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/api_keys/sample-id/expire", request.pathOnly())
            assertEquals("api_key_01EHZNVPK3SFK441A1RGBFSHRT", result.id)
        }

    @Test
    fun `create validation sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"api_key\":{\"object\":\"api_key\",\"id\":\"api_key_01EHZNVPK3SFK441A1RGBFSHRT\",\"owner\":{\"type\":\"organization\",\"id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\"},\"name\":\"Production API Key\",\"obfuscated_value\":\"sk_...3456\",\"last_used_at\":null,\"expires_at\":null,\"permissions\":[\"posts:read\",\"posts:write\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"},\"agent_registration_id\":\"agent_reg_01EHZNVPK3SFK441A1RGBFSHRT\"}")
            val result = client.apiKeys.createValidation(value = "test_value")

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/api_keys/validations", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("value"))
            assertNotNull(result)
        }

    @Test
    fun `list organization api keys sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"api_key\",\"id\":\"api_key_01EHZNVPK3SFK441A1RGBFSHRT\",\"owner\":{\"type\":\"organization\",\"id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\"},\"name\":\"Production API Key\",\"obfuscated_value\":\"sk_...3456\",\"last_used_at\":null,\"expires_at\":null,\"permissions\":[\"posts:read\",\"posts:write\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")
            val result = client.apiKeys.listOrganizationApiKeys(organizationId = "sample-organizationId")

            val request = server.takeRequest()
            assertEquals("GET", request.method)
            assertEquals("/organizations/sample-organizationId/api_keys", request.pathOnly())
            assertEquals(1, result.data.size)
            assertEquals("api_key_01EHZNVPK3SFK441A1RGBFSHRT", result.data.first().id)
        }

    @Test
    fun `create organization api key sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"api_key\",\"id\":\"api_key_01EHZNVPK3SFK441A1RGBFSHRT\",\"owner\":{\"type\":\"organization\",\"id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\"},\"name\":\"Production API Key\",\"obfuscated_value\":\"sk_...3456\",\"last_used_at\":null,\"expires_at\":\"2030-01-01T00:00:00.000Z\",\"permissions\":[\"posts:read\",\"posts:write\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\",\"value\":\"sk_abcdefghijklmnop123456\"}")
            val result = client.apiKeys.createOrganizationApiKey(organizationId = "sample-organizationId", name = "test_name")

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/organizations/sample-organizationId/api_keys", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("name"))
            assertEquals("api_key_01EHZNVPK3SFK441A1RGBFSHRT", result.id)
        }

    @Test
    fun `list organization api keys returns an empty page`() =
        runTest {
            val (client, _) = testClient(responding = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}")

            val result = client.apiKeys.listOrganizationApiKeys(organizationId = "sample-organizationId")

            assertTrue(result.data.isEmpty())
        }

    @Test
    fun `list organization api keys percent-encodes special characters in query params`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"api_key\",\"id\":\"api_key_01EHZNVPK3SFK441A1RGBFSHRT\",\"owner\":{\"type\":\"organization\",\"id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\"},\"name\":\"Production API Key\",\"obfuscated_value\":\"sk_...3456\",\"last_used_at\":null,\"expires_at\":null,\"permissions\":[\"posts:read\",\"posts:write\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.apiKeys.listOrganizationApiKeys(organizationId = "sample-organizationId", before = "a b/c&d=e")

            val request = server.takeRequest()
            assertEquals("a b/c&d=e", request.queryParam("before"))
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{}")

            client.apiKeys.delete(id = "sample-id", requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.takeRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `delete throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.apiKeys.delete(id = "sample-id")
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `delete throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.apiKeys.delete(id = "sample-id")
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `delete throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.apiKeys.delete(id = "sample-id")
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `delete throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.apiKeys.delete(id = "sample-id")
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `delete throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.apiKeys.delete(id = "sample-id")
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `delete throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.apiKeys.delete(id = "sample-id")
                }

            assertEquals(500, error.statusCode)
        }
}
