// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.models.AuditLogEvent
import com.workos.android.models.AuditLogEventActor
import com.workos.android.models.AuditLogEventContext
import com.workos.android.models.AuditLogEventTarget
import com.workos.android.models.AuditLogSchemaTargetInput
import com.workos.android.support.bodyJson
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.queryParam
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import com.workos.android.support.testClientWithStubs
import kotlinx.coroutines.flow.toList
import kotlinx.coroutines.test.runTest
import kotlinx.datetime.Instant
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertTrue

/**
 * Wire-level tests for the AuditLogs resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class AuditLogsTest {
    @Test
    fun `list actions sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"audit_log_action\",\"name\":\"user.viewed_invoice\",\"schema\":{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")
            val result = client.auditLogs.listActions()

            val request = server.takeRequest()
            assertEquals("GET", request.method)
            assertEquals("/audit_logs/actions", request.pathOnly())
            assertEquals(1, result.data.size)
            assertNotNull(result.data.first())
        }

    @Test
    fun `list actions auto paging fetches all pages`() =
        runTest {
            val (client, server) =
                testClientWithStubs(
                    listOf(
                        "{\"data\":[{\"object\":\"audit_log_action\",\"name\":\"user.viewed_invoice\",\"schema\":{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":\"cursor_2\"}}",
                        "{\"data\":[{\"object\":\"audit_log_action\",\"name\":\"user.viewed_invoice\",\"schema\":{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}",
                    ),
                )

            val items = client.auditLogs.listActionsAutoPaging().toList()

            assertEquals(2, items.size)
            server.takeRequest()
            val second = server.takeRequest()
            assertEquals("cursor_2", second.queryParam("after"))
        }

    @Test
    fun `list action schemas sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")
            val result = client.auditLogs.listActionSchemas(actionName = "sample-actionName")

            val request = server.takeRequest()
            assertEquals("GET", request.method)
            assertEquals("/audit_logs/actions/sample-actionName/schemas", request.pathOnly())
            assertEquals(1, result.data.size)
            assertNotNull(result.data.first())
        }

    @Test
    fun `create schema sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.auditLogs.createSchema(actionName = "sample-actionName", targets = listOf(AuditLogSchemaTargetInput(type = "test_type")))

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/audit_logs/actions/sample-actionName/schemas", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("targets"))
            assertNotNull(result)
        }

    @Test
    fun `create event sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"success\":true}")
            val result = client.auditLogs.createEvent(organizationId = "test_organization_id", event = AuditLogEvent(action = "test_action", occurredAt = Instant.parse("2023-01-01T00:00:00Z"), actor = AuditLogEventActor(id = "test_id", type = "test_type"), targets = listOf(AuditLogEventTarget(id = "test_id", type = "test_type")), context = AuditLogEventContext(location = "test_location")))

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/audit_logs/events", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("organization_id"))
            assertNotNull(result)
        }

    @Test
    fun `create export sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"audit_log_export\",\"id\":\"audit_log_export_01GBZK5MP7TD1YCFQHFR22180V\",\"state\":\"ready\",\"url\":\"https://exports.audit-logs.com/audit-log-exports/export.csv\",\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.auditLogs.createExport(organizationId = "test_organization_id", rangeStart = Instant.parse("2023-01-01T00:00:00Z"), rangeEnd = Instant.parse("2023-01-01T00:00:00Z"))

            val request = server.takeRequest()
            assertEquals("POST", request.method)
            assertEquals("/audit_logs/exports", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("organization_id"))
            assertEquals("audit_log_export_01GBZK5MP7TD1YCFQHFR22180V", result.id)
        }

    @Test
    fun `get export sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"audit_log_export\",\"id\":\"audit_log_export_01GBZK5MP7TD1YCFQHFR22180V\",\"state\":\"ready\",\"url\":\"https://exports.audit-logs.com/audit-log-exports/export.csv\",\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.auditLogs.getExport(auditLogExportId = "sample-auditLogExportId")

            val request = server.takeRequest()
            assertEquals("GET", request.method)
            assertEquals("/audit_logs/exports/sample-auditLogExportId", request.pathOnly())
            assertEquals("audit_log_export_01GBZK5MP7TD1YCFQHFR22180V", result.id)
        }

    @Test
    fun `get organization audit logs retention sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"retention_period_in_days\":30}")
            val result = client.auditLogs.getOrganizationAuditLogsRetention(id = "sample-id")

            val request = server.takeRequest()
            assertEquals("GET", request.method)
            assertEquals("/organizations/sample-id/audit_logs_retention", request.pathOnly())
            assertNotNull(result)
        }

    @Test
    fun `update organization audit logs retention sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"retention_period_in_days\":30}")
            val result = client.auditLogs.updateOrganizationAuditLogsRetention(id = "sample-id", retentionPeriodInDays = 1L)

            val request = server.takeRequest()
            assertEquals("PUT", request.method)
            assertEquals("/organizations/sample-id/audit_logs_retention", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("retention_period_in_days"))
            assertNotNull(result)
        }

    @Test
    fun `list actions returns an empty page`() =
        runTest {
            val (client, _) = testClient(responding = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}")

            val result = client.auditLogs.listActions()

            assertTrue(result.data.isEmpty())
        }

    @Test
    fun `list actions percent-encodes special characters in query params`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"audit_log_action\",\"name\":\"user.viewed_invoice\",\"schema\":{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.auditLogs.listActions(before = "a b/c&d=e")

            val request = server.takeRequest()
            assertEquals("a b/c&d=e", request.queryParam("before"))
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"audit_log_action\",\"name\":\"user.viewed_invoice\",\"schema\":{\"object\":\"audit_log_schema\",\"version\":1,\"actor\":{\"metadata\":{\"type\":\"object\",\"properties\":{\"role\":{\"type\":\"string\"}}}},\"targets\":[{\"type\":\"invoice\",\"metadata\":{\"type\":\"object\",\"properties\":{\"cost\":{\"type\":\"number\"}}}}],\"metadata\":{\"type\":\"object\",\"properties\":{\"transactionId\":{\"type\":\"string\"}}},\"created_at\":\"2026-01-15T12:00:00.000Z\"},\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.auditLogs.listActions(requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.takeRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `list actions throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.auditLogs.listActions()
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `list actions throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.auditLogs.listActions()
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `list actions throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.auditLogs.listActions()
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `list actions throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.auditLogs.listActions()
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `list actions throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.auditLogs.listActions()
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `list actions throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.auditLogs.listActions()
                }

            assertEquals(500, error.statusCode)
        }
}
