// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.support.awaitRequest
import com.workos.android.support.bodyJson
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Wire-level tests for the ClientApi resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class ClientApiTest {
    @Test
    fun `create token sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"token\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6InNlc3Npb24...\"}")
            val result = client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")

            val request = server.awaitRequest()
            assertEquals("POST", request.method)
            assertEquals("/client/token", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("organization_id"))
            assertEquals("eyJhbGciOiJSUzI1NiIsImtpZCI6InNlc3Npb24...", result.token)
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{\"token\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6InNlc3Npb24...\"}")

            client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id", requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.awaitRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `create token throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `create token throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `create token throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `create token throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `create token throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `create token throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.clientApi.createToken(organizationId = "test_organization_id", userId = "test_user_id")
                }

            assertEquals(500, error.statusCode)
        }
}
