// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.enums.AgentAdminValidateCredentialRequestType
import com.workos.android.enums.AgentRegistrationKind
import com.workos.android.enums.AgentRegistrationStatus
import com.workos.android.enums.AuditLogConfigurationLogStreamState
import com.workos.android.enums.AuditLogConfigurationLogStreamType
import com.workos.android.enums.AuditLogConfigurationState
import com.workos.android.enums.AuditLogExportState
import com.workos.android.models.ActionAuthenticationDenied
import com.workos.android.models.ActionAuthenticationDeniedData
import com.workos.android.models.ActionUserRegistrationDenied
import com.workos.android.models.ActionUserRegistrationDeniedData
import com.workos.android.models.Actor
import com.workos.android.models.AddRolePermission
import com.workos.android.models.AgentAdminLinkClaimAttemptToExternalUserRequest
import com.workos.android.models.AgentAdminLinkClaimAttemptToExternalUserRequestUser
import com.workos.android.models.AgentAdminValidateCredentialRequest
import com.workos.android.models.AgentCredentialValidation
import com.workos.android.models.AgentRegistration
import com.workos.android.models.AgentRegistrationAgentIdentity
import com.workos.android.models.AgentRegistrationClaim
import com.workos.android.models.AgentRegistrationClaimAttemptCreated
import com.workos.android.models.AgentRegistrationClaimAttemptCreatedData
import com.workos.android.models.AgentRegistrationClaimClaimCompletion
import com.workos.android.models.AgentRegistrationDeleted
import com.workos.android.models.AgentRegistrationDeletedData
import com.workos.android.models.AgentRegistrationExpired
import com.workos.android.models.AgentRegistrationExpiredData
import com.workos.android.models.AgentRegistrationOrganizationSwitched
import com.workos.android.models.AgentRegistrationOrganizationSwitchedData
import com.workos.android.models.AgentRegistrationRefreshed
import com.workos.android.models.AgentRegistrationRefreshedData
import com.workos.android.models.AgentRegistrationRevoked
import com.workos.android.models.AgentRegistrationRevokedData
import com.workos.android.models.ApiKeyInstallation
import com.workos.android.models.ApiKeyUpdatedDataPreviousAttribute
import com.workos.android.models.ApplicationCredentialsListItem
import com.workos.android.models.AssignRole
import com.workos.android.models.AuditLogAction
import com.workos.android.models.AuditLogConfiguration
import com.workos.android.models.AuditLogConfigurationLogStream
import com.workos.android.models.AuditLogEvent
import com.workos.android.models.AuditLogEventActor
import com.workos.android.models.AuditLogEventContext
import com.workos.android.models.AuditLogEventCreateResponse
import com.workos.android.models.AuditLogEventIngestion
import com.workos.android.models.AuditLogEventTarget
import com.workos.android.models.AuditLogExport
import com.workos.android.models.AuditLogSchema
import com.workos.android.models.AuditLogSchemaTarget
import kotlinx.datetime.Instant
import kotlinx.serialization.json.Json
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

/**
 * Serialization round-trip coverage: every model here is encoded, decoded, and
 * compared for equality, so a wrong `@SerialName` or a lossy enum serializer
 * fails here rather than silently corrupting a request body.
 */
class ModelRoundTripTest {
    private val json =
        Json {
            ignoreUnknownKeys = true
            explicitNulls = false
        }

    @Test
    fun `ActionAuthenticationDenied round-trips through JSON`() {
        val original = ActionAuthenticationDenied(`object` = "event", id = "test_id", event = "action.authentication.denied", data = ActionAuthenticationDeniedData(actionEndpointId = "test_action_endpoint_id", actionExecutionId = "test_action_execution_id", type = "authentication", verdict = "Deny", userId = "test_user_id", organizationId = "test_organization_id", email = "test_email", ipAddress = "test_ip_address", userAgent = "test_user_agent"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(ActionAuthenticationDenied.serializer(), original)
        val decoded = json.decodeFromString(ActionAuthenticationDenied.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `ActionAuthenticationDeniedData round-trips through JSON`() {
        val original = ActionAuthenticationDeniedData(actionEndpointId = "test_action_endpoint_id", actionExecutionId = "test_action_execution_id", type = "authentication", verdict = "Deny", userId = "test_user_id", organizationId = "test_organization_id", email = "test_email", ipAddress = "test_ip_address", userAgent = "test_user_agent")

        val encoded = json.encodeToString(ActionAuthenticationDeniedData.serializer(), original)
        val decoded = json.decodeFromString(ActionAuthenticationDeniedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `ActionUserRegistrationDenied round-trips through JSON`() {
        val original = ActionUserRegistrationDenied(`object` = "event", id = "test_id", event = "action.user_registration.denied", data = ActionUserRegistrationDeniedData(actionEndpointId = "test_action_endpoint_id", actionExecutionId = "test_action_execution_id", type = "user_registration", verdict = "Deny", organizationId = "test_organization_id", email = "test_email", ipAddress = "test_ip_address", userAgent = "test_user_agent"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(ActionUserRegistrationDenied.serializer(), original)
        val decoded = json.decodeFromString(ActionUserRegistrationDenied.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `ActionUserRegistrationDeniedData round-trips through JSON`() {
        val original = ActionUserRegistrationDeniedData(actionEndpointId = "test_action_endpoint_id", actionExecutionId = "test_action_execution_id", type = "user_registration", verdict = "Deny", organizationId = "test_organization_id", email = "test_email", ipAddress = "test_ip_address", userAgent = "test_user_agent")

        val encoded = json.encodeToString(ActionUserRegistrationDeniedData.serializer(), original)
        val decoded = json.decodeFromString(ActionUserRegistrationDeniedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `Actor round-trips through JSON`() {
        val original = Actor(id = "test_id", name = "test_name")

        val encoded = json.encodeToString(Actor.serializer(), original)
        val decoded = json.decodeFromString(Actor.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AddRolePermission round-trips through JSON`() {
        val original = AddRolePermission(slug = "test_slug")

        val encoded = json.encodeToString(AddRolePermission.serializer(), original)
        val decoded = json.decodeFromString(AddRolePermission.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentAdminLinkClaimAttemptToExternalUserRequest round-trips through JSON`() {
        val original = AgentAdminLinkClaimAttemptToExternalUserRequest(type = "link_external_user", claimAttemptToken = "test_claim_attempt_token", user = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id"))

        val encoded = json.encodeToString(AgentAdminLinkClaimAttemptToExternalUserRequest.serializer(), original)
        val decoded = json.decodeFromString(AgentAdminLinkClaimAttemptToExternalUserRequest.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentAdminLinkClaimAttemptToExternalUserRequestUser round-trips through JSON`() {
        val original = AgentAdminLinkClaimAttemptToExternalUserRequestUser(email = "test_email", externalId = "test_external_id")

        val encoded = json.encodeToString(AgentAdminLinkClaimAttemptToExternalUserRequestUser.serializer(), original)
        val decoded = json.decodeFromString(AgentAdminLinkClaimAttemptToExternalUserRequestUser.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentAdminValidateCredentialRequest round-trips through JSON`() {
        val original = AgentAdminValidateCredentialRequest(type = AgentAdminValidateCredentialRequestType.fromRawValue("api_key"), credential = "test_credential")

        val encoded = json.encodeToString(AgentAdminValidateCredentialRequest.serializer(), original)
        val decoded = json.decodeFromString(AgentAdminValidateCredentialRequest.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentCredentialValidation round-trips through JSON`() {
        val original = AgentCredentialValidation(valid = true, registrationId = "test_registration_id", expiresAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentCredentialValidation.serializer(), original)
        val decoded = json.decodeFromString(AgentCredentialValidation.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistration round-trips through JSON`() {
        val original = AgentRegistration(id = "test_id", agentIdentity = AgentRegistrationAgentIdentity(id = "test_id", userlandUserId = "test_userland_user_id", createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z")), organizationId = "test_organization_id", status = AgentRegistrationStatus.fromRawValue("unverified"), kind = AgentRegistrationKind.fromRawValue("anonymous"), claim = AgentRegistrationClaim(id = "test_id", claimCompletion = AgentRegistrationClaimClaimCompletion(id = "test_id", createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"), expiresAt = Instant.parse("2023-01-01T00:00:00Z"), claimedAt = Instant.parse("2023-01-01T00:00:00Z")), createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"), expiresAt = Instant.parse("2023-01-01T00:00:00Z")), createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistration.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistration.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationAgentIdentity round-trips through JSON`() {
        val original = AgentRegistrationAgentIdentity(id = "test_id", userlandUserId = "test_userland_user_id", createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationAgentIdentity.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationAgentIdentity.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationClaim round-trips through JSON`() {
        val original = AgentRegistrationClaim(id = "test_id", claimCompletion = AgentRegistrationClaimClaimCompletion(id = "test_id", createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"), expiresAt = Instant.parse("2023-01-01T00:00:00Z"), claimedAt = Instant.parse("2023-01-01T00:00:00Z")), createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"), expiresAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationClaim.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationClaim.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationClaimAttemptCreated round-trips through JSON`() {
        val original = AgentRegistrationClaimAttemptCreated(`object` = "event", id = "test_id", event = "agent.registration.claim.attempt.created", data = AgentRegistrationClaimAttemptCreatedData(`object` = "agent_registration_claim_attempt", id = "test_id", agentRegistrationId = "test_agent_registration_id", agentRegistrationClaimId = "test_agent_registration_claim_id", loginHint = "test_login_hint", expiresAt = "test_expires_at", createdAt = "test_created_at", updatedAt = "test_updated_at"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationClaimAttemptCreated.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationClaimAttemptCreated.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationClaimAttemptCreatedData round-trips through JSON`() {
        val original = AgentRegistrationClaimAttemptCreatedData(`object` = "agent_registration_claim_attempt", id = "test_id", agentRegistrationId = "test_agent_registration_id", agentRegistrationClaimId = "test_agent_registration_claim_id", loginHint = "test_login_hint", expiresAt = "test_expires_at", createdAt = "test_created_at", updatedAt = "test_updated_at")

        val encoded = json.encodeToString(AgentRegistrationClaimAttemptCreatedData.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationClaimAttemptCreatedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationClaimClaimCompletion round-trips through JSON`() {
        val original = AgentRegistrationClaimClaimCompletion(id = "test_id", createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"), expiresAt = Instant.parse("2023-01-01T00:00:00Z"), claimedAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationClaimClaimCompletion.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationClaimClaimCompletion.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationDeleted round-trips through JSON`() {
        val original = AgentRegistrationDeleted(`object` = "event", id = "test_id", event = "agent.registration.deleted", data = AgentRegistrationDeletedData(agentRegistrationId = "test_agent_registration_id"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationDeleted.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationDeleted.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationDeletedData round-trips through JSON`() {
        val original = AgentRegistrationDeletedData(agentRegistrationId = "test_agent_registration_id")

        val encoded = json.encodeToString(AgentRegistrationDeletedData.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationDeletedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationExpired round-trips through JSON`() {
        val original = AgentRegistrationExpired(`object` = "event", id = "test_id", event = "agent.registration.expired", data = AgentRegistrationExpiredData(agentRegistrationId = "test_agent_registration_id"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationExpired.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationExpired.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationExpiredData round-trips through JSON`() {
        val original = AgentRegistrationExpiredData(agentRegistrationId = "test_agent_registration_id")

        val encoded = json.encodeToString(AgentRegistrationExpiredData.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationExpiredData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationOrganizationSwitched round-trips through JSON`() {
        val original = AgentRegistrationOrganizationSwitched(`object` = "event", id = "test_id", event = "agent.registration.organization.switched", data = AgentRegistrationOrganizationSwitchedData(agentRegistrationId = "test_agent_registration_id", fromOrganizationId = "test_from_organization_id", toOrganizationId = "test_to_organization_id"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationOrganizationSwitched.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationOrganizationSwitched.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationOrganizationSwitchedData round-trips through JSON`() {
        val original = AgentRegistrationOrganizationSwitchedData(agentRegistrationId = "test_agent_registration_id", fromOrganizationId = "test_from_organization_id", toOrganizationId = "test_to_organization_id")

        val encoded = json.encodeToString(AgentRegistrationOrganizationSwitchedData.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationOrganizationSwitchedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationRefreshed round-trips through JSON`() {
        val original = AgentRegistrationRefreshed(`object` = "event", id = "test_id", event = "agent.registration.refreshed", data = AgentRegistrationRefreshedData(agentRegistrationId = "test_agent_registration_id"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationRefreshed.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationRefreshed.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationRefreshedData round-trips through JSON`() {
        val original = AgentRegistrationRefreshedData(agentRegistrationId = "test_agent_registration_id")

        val encoded = json.encodeToString(AgentRegistrationRefreshedData.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationRefreshedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationRevoked round-trips through JSON`() {
        val original = AgentRegistrationRevoked(`object` = "event", id = "test_id", event = "agent.registration.revoked", data = AgentRegistrationRevokedData(agentRegistrationId = "test_agent_registration_id"), createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AgentRegistrationRevoked.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationRevoked.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AgentRegistrationRevokedData round-trips through JSON`() {
        val original = AgentRegistrationRevokedData(agentRegistrationId = "test_agent_registration_id")

        val encoded = json.encodeToString(AgentRegistrationRevokedData.serializer(), original)
        val decoded = json.decodeFromString(AgentRegistrationRevokedData.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `ApiKeyInstallation round-trips through JSON`() {
        val original = ApiKeyInstallation(secret = "test_secret", userId = "test_user_id")

        val encoded = json.encodeToString(ApiKeyInstallation.serializer(), original)
        val decoded = json.decodeFromString(ApiKeyInstallation.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `ApiKeyUpdatedDataPreviousAttribute round-trips through JSON`() {
        val original = ApiKeyUpdatedDataPreviousAttribute(expiresAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(ApiKeyUpdatedDataPreviousAttribute.serializer(), original)
        val decoded = json.decodeFromString(ApiKeyUpdatedDataPreviousAttribute.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `ApplicationCredentialsListItem round-trips through JSON`() {
        val original = ApplicationCredentialsListItem(`object` = "connect_application_secret", id = "test_id", secretHint = "test_secret_hint", lastUsedAt = Instant.parse("2023-01-01T00:00:00Z"), createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(ApplicationCredentialsListItem.serializer(), original)
        val decoded = json.decodeFromString(ApplicationCredentialsListItem.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AssignRole round-trips through JSON`() {
        val original = AssignRole(roleSlug = "test_role_slug")

        val encoded = json.encodeToString(AssignRole.serializer(), original)
        val decoded = json.decodeFromString(AssignRole.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogAction round-trips through JSON`() {
        val original = AuditLogAction(`object` = "audit_log_action", name = "test_name", schema = AuditLogSchema(`object` = "audit_log_schema", version = 1L, targets = listOf(AuditLogSchemaTarget(type = "test_type")), createdAt = Instant.parse("2023-01-01T00:00:00Z")), createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AuditLogAction.serializer(), original)
        val decoded = json.decodeFromString(AuditLogAction.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogConfiguration round-trips through JSON`() {
        val original = AuditLogConfiguration(organizationId = "test_organization_id", retentionPeriodInDays = 1L, state = AuditLogConfigurationState.fromRawValue("active"))

        val encoded = json.encodeToString(AuditLogConfiguration.serializer(), original)
        val decoded = json.decodeFromString(AuditLogConfiguration.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogConfigurationLogStream round-trips through JSON`() {
        val original = AuditLogConfigurationLogStream(id = "test_id", type = AuditLogConfigurationLogStreamType.fromRawValue("AzureSentinel"), state = AuditLogConfigurationLogStreamState.fromRawValue("active"), lastSyncedAt = "test_last_synced_at", createdAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AuditLogConfigurationLogStream.serializer(), original)
        val decoded = json.decodeFromString(AuditLogConfigurationLogStream.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogEvent round-trips through JSON`() {
        val original = AuditLogEvent(action = "test_action", occurredAt = Instant.parse("2023-01-01T00:00:00Z"), actor = AuditLogEventActor(id = "test_id", type = "test_type"), targets = listOf(AuditLogEventTarget(id = "test_id", type = "test_type")), context = AuditLogEventContext(location = "test_location"))

        val encoded = json.encodeToString(AuditLogEvent.serializer(), original)
        val decoded = json.decodeFromString(AuditLogEvent.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogEventActor round-trips through JSON`() {
        val original = AuditLogEventActor(id = "test_id", type = "test_type")

        val encoded = json.encodeToString(AuditLogEventActor.serializer(), original)
        val decoded = json.decodeFromString(AuditLogEventActor.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogEventContext round-trips through JSON`() {
        val original = AuditLogEventContext(location = "test_location")

        val encoded = json.encodeToString(AuditLogEventContext.serializer(), original)
        val decoded = json.decodeFromString(AuditLogEventContext.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogEventCreateResponse round-trips through JSON`() {
        val original = AuditLogEventCreateResponse(success = true)

        val encoded = json.encodeToString(AuditLogEventCreateResponse.serializer(), original)
        val decoded = json.decodeFromString(AuditLogEventCreateResponse.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogEventIngestion round-trips through JSON`() {
        val original = AuditLogEventIngestion(organizationId = "test_organization_id", event = AuditLogEvent(action = "test_action", occurredAt = Instant.parse("2023-01-01T00:00:00Z"), actor = AuditLogEventActor(id = "test_id", type = "test_type"), targets = listOf(AuditLogEventTarget(id = "test_id", type = "test_type")), context = AuditLogEventContext(location = "test_location")))

        val encoded = json.encodeToString(AuditLogEventIngestion.serializer(), original)
        val decoded = json.decodeFromString(AuditLogEventIngestion.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogEventTarget round-trips through JSON`() {
        val original = AuditLogEventTarget(id = "test_id", type = "test_type")

        val encoded = json.encodeToString(AuditLogEventTarget.serializer(), original)
        val decoded = json.decodeFromString(AuditLogEventTarget.serializer(), encoded)

        assertEquals(original, decoded)
    }

    @Test
    fun `AuditLogExport round-trips through JSON`() {
        val original = AuditLogExport(`object` = "audit_log_export", id = "test_id", state = AuditLogExportState.fromRawValue("pending"), createdAt = Instant.parse("2023-01-01T00:00:00Z"), updatedAt = Instant.parse("2023-01-01T00:00:00Z"))

        val encoded = json.encodeToString(AuditLogExport.serializer(), original)
        val decoded = json.decodeFromString(AuditLogExport.serializer(), encoded)

        assertEquals(original, decoded)
    }
}
