// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.support.awaitRequest
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

/**
 * Wire-level tests for the PipesProvider resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class PipesProviderTest {
    @Test
    fun `list organization data integration configurations sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"list\",\"data\":[{\"object\":\"data_integration_configuration\",\"id\":\"data_integration_01EHZNVPK3SFK441A1RGBFSHRT\",\"organization_id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\",\"slug\":\"github\",\"name\":\"GitHub\",\"enabled\":true,\"scopes\":[\"repo\",\"user:email\"],\"config\":{\"account_identifier\":\"acme-prod\"},\"created_at\":\"2024-01-15T10:30:00.000Z\",\"updated_at\":\"2024-01-15T10:30:00.000Z\",\"credentials\":{\"credentials_type\":\"organization\",\"has_credentials\":true,\"client_id\":\"client_01EHZNVPK3SFK441A1RGBFSHRT\",\"client_secret_last_four\":\"1a2b\",\"redirect_uri\":\"https://api.workos.com/data-integrations/github/dik_01EHZNVPK3SFK441A1RGBFSHRT/callback\"}}]}")
            val result = client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")

            val request = server.awaitRequest()
            assertEquals("GET", request.method)
            assertEquals("/organizations/sample-organizationId/data_integration_configurations", request.pathOnly())
            assertEquals(1, result.data.size)
            assertEquals("data_integration_01EHZNVPK3SFK441A1RGBFSHRT", result.data.first().id)
        }

    @Test
    fun `update organization data integration configuration sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"data_integration_configuration\",\"id\":\"data_integration_01EHZNVPK3SFK441A1RGBFSHRT\",\"organization_id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\",\"slug\":\"github\",\"name\":\"GitHub\",\"enabled\":true,\"scopes\":[\"repo\",\"user:email\"],\"config\":{\"account_identifier\":\"acme-prod\"},\"created_at\":\"2024-01-15T10:30:00.000Z\",\"updated_at\":\"2024-01-15T10:30:00.000Z\",\"credentials\":{\"credentials_type\":\"organization\",\"has_credentials\":true,\"client_id\":\"client_01EHZNVPK3SFK441A1RGBFSHRT\",\"client_secret_last_four\":\"1a2b\",\"redirect_uri\":\"https://api.workos.com/data-integrations/github/dik_01EHZNVPK3SFK441A1RGBFSHRT/callback\"}}")
            val result = client.pipesProvider.updateOrganizationDataIntegrationConfiguration(organizationId = "sample-organizationId", slug = "sample-slug")

            val request = server.awaitRequest()
            assertEquals("PUT", request.method)
            assertEquals("/organizations/sample-organizationId/data_integration_configurations/sample-slug", request.pathOnly())
            assertEquals("data_integration_01EHZNVPK3SFK441A1RGBFSHRT", result.id)
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"list\",\"data\":[{\"object\":\"data_integration_configuration\",\"id\":\"data_integration_01EHZNVPK3SFK441A1RGBFSHRT\",\"organization_id\":\"org_01EHZNVPK3SFK441A1RGBFSHRT\",\"slug\":\"github\",\"name\":\"GitHub\",\"enabled\":true,\"scopes\":[\"repo\",\"user:email\"],\"config\":{\"account_identifier\":\"acme-prod\"},\"created_at\":\"2024-01-15T10:30:00.000Z\",\"updated_at\":\"2024-01-15T10:30:00.000Z\",\"credentials\":{\"credentials_type\":\"organization\",\"has_credentials\":true,\"client_id\":\"client_01EHZNVPK3SFK441A1RGBFSHRT\",\"client_secret_last_four\":\"1a2b\",\"redirect_uri\":\"https://api.workos.com/data-integrations/github/dik_01EHZNVPK3SFK441A1RGBFSHRT/callback\"}}]}")

            client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId", requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.awaitRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `list organization data integration configurations throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `list organization data integration configurations throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `list organization data integration configurations throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `list organization data integration configurations throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `list organization data integration configurations throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `list organization data integration configurations throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.pipesProvider.listOrganizationDataIntegrationConfigurations(organizationId = "sample-organizationId")
                }

            assertEquals(500, error.statusCode)
        }
}
