// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.support.awaitRequest
import com.workos.android.support.bodyJson
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.queryParam
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Wire-level tests for the SSO resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class SSOTest {
    @Test
    fun `list connections sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"connection\",\"id\":\"conn_01E4ZCR3C56J083X43JQXF3JK5\",\"organization_id\":\"org_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"connection_type\":\"OktaSAML\",\"name\":\"Foo Corp\",\"state\":\"active\",\"status\":\"linked\",\"domains\":[{\"id\":\"org_domain_01EHZNVPK2QXHMVWCEDQEKY69A\",\"object\":\"connection_domain\",\"domain\":\"foo-corp.com\"}],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")
            val result = client.sso.listConnections()

            val request = server.awaitRequest()
            assertEquals("GET", request.method)
            assertEquals("/connections", request.pathOnly())
            assertEquals(1, result.data.size)
            assertEquals("conn_01E4ZCR3C56J083X43JQXF3JK5", result.data.first().id)
        }

    @Test
    fun `get connection sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"connection\",\"id\":\"conn_01E4ZCR3C56J083X43JQXF3JK5\",\"organization_id\":\"org_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"connection_type\":\"OktaSAML\",\"name\":\"Foo Corp\",\"state\":\"active\",\"status\":\"linked\",\"domains\":[{\"id\":\"org_domain_01EHZNVPK2QXHMVWCEDQEKY69A\",\"object\":\"connection_domain\",\"domain\":\"foo-corp.com\"}],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.sso.getConnection(id = "sample-id")

            val request = server.awaitRequest()
            assertEquals("GET", request.method)
            assertEquals("/connections/sample-id", request.pathOnly())
            assertEquals("conn_01E4ZCR3C56J083X43JQXF3JK5", result.id)
        }

    @Test
    fun `delete connection sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{}")
            client.sso.deleteConnection(id = "sample-id")

            val request = server.awaitRequest()
            assertEquals("DELETE", request.method)
            assertEquals("/connections/sample-id", request.pathOnly())
        }

    @Test
    fun `get authorization url builds expected url`() {
        val (client, _) = testClient()

        val url = client.sso.getAuthorizationUrl(redirectUri = "test_redirect_uri")

        assertTrue(url.substringBefore('?').endsWith("/sso/authorize"))
        assertTrue(url.contains("response_type=code"))
        assertTrue(url.contains("redirect_uri="))

        val withMap = client.sso.getAuthorizationUrl(redirectUri = "test_redirect_uri", providerQueryParams = mapOf("k1" to "v1"))
        assertTrue(withMap.contains("provider_query_params%5Bk1%5D=v1"))
        assertTrue(!withMap.contains("provider_query_params="))
    }

    @Test
    fun `get logout url builds expected url`() {
        val (client, _) = testClient()

        val url = client.sso.getLogoutUrl(token = "test_token")

        assertTrue(url.substringBefore('?').endsWith("/sso/logout"))
        assertTrue(url.contains("token="))
    }

    @Test
    fun `authorize logout sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"logout_url\":\"https://auth.workos.com/sso/logout?token=eyJhbGciOiJSUzI1NiJ9\",\"logout_token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwcm9maWxlX2lkIjoicHJvZl8wMUdXUTFHMEgyRk02QVNFRjBIUzEzSENXOS0zMDRrZzAzZyIsImV4cCI6IjE1MTYyMzkwMjIifQ.Wru9Qlnf5DpohtGCKhZU4cVOd3zpiu7QQ-XEX--5A_4\"}")
            val result = client.sso.authorizeLogout(profileId = "test_profile_id")

            val request = server.awaitRequest()
            assertEquals("POST", request.method)
            assertEquals("/sso/logout/authorize", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("profile_id"))
            assertEquals("https://auth.workos.com/sso/logout?token=eyJhbGciOiJSUzI1NiJ9", result.logoutUrl)
        }

    @Test
    fun `get profile sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"profile\",\"id\":\"prof_01DMC79VCBZ0NY2099737PSVF1\",\"organization_id\":\"org_01EHQMYV6MBK39QC5PZXHY59C3\",\"connection_id\":\"conn_01E4ZCR3C56J083X43JQXF3JK5\",\"connection_type\":\"OktaSAML\",\"idp_id\":\"103456789012345678901\",\"email\":\"todd@example.com\",\"first_name\":\"Todd\",\"last_name\":\"Rundgren\",\"name\":\"Todd Rundgren\",\"role\":{\"slug\":\"admin\"},\"roles\":[{\"slug\":\"admin\"}],\"groups\":[\"Engineering\",\"Admins\"],\"custom_attributes\":{\"key\":{}},\"raw_attributes\":{\"key\":{}}}")
            val result = client.sso.getProfile()

            val request = server.awaitRequest()
            assertEquals("GET", request.method)
            assertEquals("/sso/profile", request.pathOnly())
            assertEquals("prof_01DMC79VCBZ0NY2099737PSVF1", result.id)
        }

    @Test
    fun `get profile and token sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"token_type\":\"Bearer\",\"access_token\":\"eyJhbGciOiJSUzI1NiIsImtpZCI6InNzby...\",\"expires_in\":600,\"profile\":{\"object\":\"profile\",\"id\":\"prof_01DMC79VCBZ0NY2099737PSVF1\",\"organization_id\":\"org_01EHQMYV6MBK39QC5PZXHY59C3\",\"connection_id\":\"conn_01E4ZCR3C56J083X43JQXF3JK5\",\"connection_type\":\"OktaSAML\",\"idp_id\":\"103456789012345678901\",\"email\":\"todd@example.com\",\"first_name\":\"Todd\",\"last_name\":\"Rundgren\",\"name\":\"Todd Rundgren\",\"role\":{\"slug\":\"admin\"},\"roles\":[{\"slug\":\"admin\"}],\"groups\":[\"Engineering\",\"Admins\"],\"custom_attributes\":{\"key\":{}},\"raw_attributes\":{\"key\":{}}},\"oauth_tokens\":{\"provider\":\"GoogleOAuth\",\"refresh_token\":\"1//04g...\",\"access_token\":\"ya29.a0ARrdaM...\",\"expires_at\":1735141800,\"scopes\":[\"profile\",\"email\",\"openid\"]}}")
            val result = client.sso.getProfileAndToken(code = "test_code", code2 = "test_code")

            val request = server.awaitRequest()
            assertEquals("POST", request.method)
            assertEquals("/sso/token", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("code"))
            assertEquals("test_code", request.queryParam("code"))
            assertEquals("eyJhbGciOiJSUzI1NiIsImtpZCI6InNzby...", result.accessToken)
        }

    @Test
    fun `list connections returns an empty page`() =
        runTest {
            val (client, _) = testClient(responding = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}")

            val result = client.sso.listConnections()

            assertTrue(result.data.isEmpty())
        }

    @Test
    fun `list connections percent-encodes special characters in query params`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"connection\",\"id\":\"conn_01E4ZCR3C56J083X43JQXF3JK5\",\"organization_id\":\"org_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"connection_type\":\"OktaSAML\",\"name\":\"Foo Corp\",\"state\":\"active\",\"status\":\"linked\",\"domains\":[{\"id\":\"org_domain_01EHZNVPK2QXHMVWCEDQEKY69A\",\"object\":\"connection_domain\",\"domain\":\"foo-corp.com\"}],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.sso.listConnections(before = "a b/c&d=e")

            val request = server.awaitRequest()
            assertEquals("a b/c&d=e", request.queryParam("before"))
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"connection\",\"id\":\"conn_01E4ZCR3C56J083X43JQXF3JK5\",\"organization_id\":\"org_01EHWNCE74X7JSDV0X3SZ3KJNY\",\"connection_type\":\"OktaSAML\",\"name\":\"Foo Corp\",\"state\":\"active\",\"status\":\"linked\",\"domains\":[{\"id\":\"org_domain_01EHZNVPK2QXHMVWCEDQEKY69A\",\"object\":\"connection_domain\",\"domain\":\"foo-corp.com\"}],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.sso.listConnections(requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.awaitRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `list connections throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.sso.listConnections()
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `list connections throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.sso.listConnections()
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `list connections throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.sso.listConnections()
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `list connections throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.sso.listConnections()
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `list connections throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.sso.listConnections()
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `list connections throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.sso.listConnections()
                }

            assertEquals(500, error.statusCode)
        }
}
