// This file is auto-generated by oagen. Do not edit.

package com.workos.android

import com.workos.android.enums.CreateWebhookEndpointEvents
import com.workos.android.support.awaitRequest
import com.workos.android.support.bodyJson
import com.workos.android.support.headerValue
import com.workos.android.support.pathOnly
import com.workos.android.support.queryParam
import com.workos.android.support.testClient
import com.workos.android.support.testClientWithStatus
import kotlinx.coroutines.test.runTest
import org.junit.jupiter.api.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

/**
 * Wire-level tests for the Webhooks resource: each test performs a real call
 * through the mocked transport and asserts the request that went out and the
 * decoded response that came back.
 */
class WebhooksTest {
    @Test
    fun `list endpoints sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"webhook_endpoint\",\"id\":\"we_0123456789\",\"endpoint_url\":\"https://example.com/webhooks\",\"secret\":\"whsec_0FWAiVGkEfGBqqsJH4aNAGBJ4\",\"status\":\"enabled\",\"events\":[\"user.created\",\"dsync.user.created\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")
            val result = client.webhooks.listEndpoints()

            val request = server.awaitRequest()
            assertEquals("GET", request.method)
            assertEquals("/webhook_endpoints", request.pathOnly())
            assertEquals(1, result.data.size)
            assertEquals("we_0123456789", result.data.first().id)
        }

    @Test
    fun `create endpoint sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"webhook_endpoint\",\"id\":\"we_0123456789\",\"endpoint_url\":\"https://example.com/webhooks\",\"secret\":\"whsec_0FWAiVGkEfGBqqsJH4aNAGBJ4\",\"status\":\"enabled\",\"events\":[\"user.created\",\"dsync.user.created\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.webhooks.createEndpoint(endpointUrl = "test_endpoint_url", events = listOf(CreateWebhookEndpointEvents.fromRawValue("agent.registration.created")))

            val request = server.awaitRequest()
            assertEquals("POST", request.method)
            assertEquals("/webhook_endpoints", request.pathOnly())
            assertTrue(request.bodyJson().containsKey("endpoint_url"))
            assertEquals("we_0123456789", result.id)
        }

    @Test
    fun `update endpoint sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{\"object\":\"webhook_endpoint\",\"id\":\"we_0123456789\",\"endpoint_url\":\"https://example.com/webhooks\",\"secret\":\"whsec_0FWAiVGkEfGBqqsJH4aNAGBJ4\",\"status\":\"enabled\",\"events\":[\"user.created\",\"dsync.user.created\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}")
            val result = client.webhooks.updateEndpoint(id = "sample-id")

            val request = server.awaitRequest()
            assertEquals("PATCH", request.method)
            assertEquals("/webhook_endpoints/sample-id", request.pathOnly())
            assertEquals("we_0123456789", result.id)
        }

    @Test
    fun `delete endpoint sends expected request`() =
        runTest {
            val (client, server) = testClient(responding = "{}")
            client.webhooks.deleteEndpoint(id = "sample-id")

            val request = server.awaitRequest()
            assertEquals("DELETE", request.method)
            assertEquals("/webhook_endpoints/sample-id", request.pathOnly())
        }

    @Test
    fun `list endpoints returns an empty page`() =
        runTest {
            val (client, _) = testClient(responding = "{\"data\":[],\"list_metadata\":{\"before\":null,\"after\":null}}")

            val result = client.webhooks.listEndpoints()

            assertTrue(result.data.isEmpty())
        }

    @Test
    fun `list endpoints percent-encodes special characters in query params`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"webhook_endpoint\",\"id\":\"we_0123456789\",\"endpoint_url\":\"https://example.com/webhooks\",\"secret\":\"whsec_0FWAiVGkEfGBqqsJH4aNAGBJ4\",\"status\":\"enabled\",\"events\":[\"user.created\",\"dsync.user.created\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.webhooks.listEndpoints(before = "a b/c&d=e")

            val request = server.awaitRequest()
            assertEquals("a b/c&d=e", request.queryParam("before"))
        }

    @Test
    fun `request options are honored on the wire`() =
        runTest {
            val (client, server) = testClient(responding = "{\"data\":[{\"object\":\"webhook_endpoint\",\"id\":\"we_0123456789\",\"endpoint_url\":\"https://example.com/webhooks\",\"secret\":\"whsec_0FWAiVGkEfGBqqsJH4aNAGBJ4\",\"status\":\"enabled\",\"events\":[\"user.created\",\"dsync.user.created\"],\"created_at\":\"2026-01-15T12:00:00.000Z\",\"updated_at\":\"2026-01-15T12:00:00.000Z\"}],\"list_metadata\":{\"before\":null,\"after\":null}}")

            client.webhooks.listEndpoints(requestOptions = RequestOptions(headers = mapOf("X-Custom" to "value")))

            val request = server.awaitRequest()
            assertEquals("value", request.headerValue("X-Custom"))
        }

    @Test
    fun `list endpoints throws AuthenticationException on 401`() =
        runTest {
            val (client, _) = testClientWithStatus(401, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<AuthenticationException> {
                    client.webhooks.listEndpoints()
                }

            assertEquals(401, error.statusCode)
        }

    @Test
    fun `list endpoints throws NotFoundException on 404`() =
        runTest {
            val (client, _) = testClientWithStatus(404, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<NotFoundException> {
                    client.webhooks.listEndpoints()
                }

            assertEquals(404, error.statusCode)
        }

    @Test
    fun `list endpoints throws RateLimitExceededException on 429`() =
        runTest {
            val (client, _) = testClientWithStatus(429, "{\"message\":\"error\"}", mapOf("Retry-After" to "0"))

            val error =
                assertFailsWith<RateLimitExceededException> {
                    client.webhooks.listEndpoints()
                }

            assertEquals(429, error.statusCode)
        }

    @Test
    fun `list endpoints throws BadRequestException on 400`() =
        runTest {
            val (client, _) = testClientWithStatus(400, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<BadRequestException> {
                    client.webhooks.listEndpoints()
                }

            assertEquals(400, error.statusCode)
        }

    @Test
    fun `list endpoints throws UnprocessableEntityException on 422`() =
        runTest {
            val (client, _) = testClientWithStatus(422, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<UnprocessableEntityException> {
                    client.webhooks.listEndpoints()
                }

            assertEquals(422, error.statusCode)
        }

    @Test
    fun `list endpoints throws ServerException on 500`() =
        runTest {
            val (client, _) = testClientWithStatus(500, "{\"message\":\"error\"}")

            val error =
                assertFailsWith<ServerException> {
                    client.webhooks.listEndpoints()
                }

            assertEquals(500, error.statusCode)
        }
}
